var annotated_dup =
[
    [ "AssertLib", "namespaceAssertLib.html", [
      [ "AssertionError", "classAssertLib_1_1AssertionError.html", "classAssertLib_1_1AssertionError" ]
    ] ],
    [ "Engine", "namespaceEngine.html", [
      [ "Application", "classEngine_1_1Application.html", "classEngine_1_1Application" ],
      [ "AssetManager", "classEngine_1_1AssetManager.html", "classEngine_1_1AssetManager" ],
      [ "BatchRenderer2D", "classEngine_1_1BatchRenderer2D.html", "classEngine_1_1BatchRenderer2D" ],
      [ "BatchVertex", "structEngine_1_1BatchVertex.html", "structEngine_1_1BatchVertex" ],
      [ "BufferElement", "structEngine_1_1BufferElement.html", "structEngine_1_1BufferElement" ],
      [ "BufferLayout", "classEngine_1_1BufferLayout.html", "classEngine_1_1BufferLayout" ],
      [ "Event", "classEngine_1_1Event.html", "classEngine_1_1Event" ],
      [ "EventCompare", "structEngine_1_1EventCompare.html", "structEngine_1_1EventCompare" ],
      [ "EventDebugger", "classEngine_1_1EventDebugger.html", "classEngine_1_1EventDebugger" ],
      [ "EventDispatcher", "classEngine_1_1EventDispatcher.html", "classEngine_1_1EventDispatcher" ],
      [ "EventQueue", "classEngine_1_1EventQueue.html", "classEngine_1_1EventQueue" ],
      [ "FileSystem", "classEngine_1_1FileSystem.html", "classEngine_1_1FileSystem" ],
      [ "FileWatcher", "classEngine_1_1FileWatcher.html", "classEngine_1_1FileWatcher" ],
      [ "FPSCounter", "classEngine_1_1FPSCounter.html", "classEngine_1_1FPSCounter" ],
      [ "GLCommand", "structEngine_1_1GLCommand.html", "structEngine_1_1GLCommand" ],
      [ "ImGuiLayer", "classEngine_1_1ImGuiLayer.html", "classEngine_1_1ImGuiLayer" ],
      [ "ImGuiOverlay", "classEngine_1_1ImGuiOverlay.html", "classEngine_1_1ImGuiOverlay" ],
      [ "IndexBuffer", "classEngine_1_1IndexBuffer.html", "classEngine_1_1IndexBuffer" ],
      [ "InputSystem", "classEngine_1_1InputSystem.html", "classEngine_1_1InputSystem" ],
      [ "IRenderer", "classEngine_1_1IRenderer.html", "classEngine_1_1IRenderer" ],
      [ "KeyEvent", "classEngine_1_1KeyEvent.html", "classEngine_1_1KeyEvent" ],
      [ "KeyPressedEvent", "classEngine_1_1KeyPressedEvent.html", "classEngine_1_1KeyPressedEvent" ],
      [ "KeyReleasedEvent", "classEngine_1_1KeyReleasedEvent.html", "classEngine_1_1KeyReleasedEvent" ],
      [ "KeyToggleState", "structEngine_1_1KeyToggleState.html", "structEngine_1_1KeyToggleState" ],
      [ "Light", "classEngine_1_1Light.html", "classEngine_1_1Light" ],
      [ "Logger", "classEngine_1_1Logger.html", "classEngine_1_1Logger" ],
      [ "LuaScriptSystem", "classEngine_1_1LuaScriptSystem.html", "classEngine_1_1LuaScriptSystem" ],
      [ "Material", "classEngine_1_1Material.html", "classEngine_1_1Material" ],
      [ "MouseButtonEvent", "classEngine_1_1MouseButtonEvent.html", "classEngine_1_1MouseButtonEvent" ],
      [ "MouseButtonPressedEvent", "classEngine_1_1MouseButtonPressedEvent.html", "classEngine_1_1MouseButtonPressedEvent" ],
      [ "MouseButtonReleasedEvent", "classEngine_1_1MouseButtonReleasedEvent.html", "classEngine_1_1MouseButtonReleasedEvent" ],
      [ "MouseMovedEvent", "classEngine_1_1MouseMovedEvent.html", "classEngine_1_1MouseMovedEvent" ],
      [ "MouseScrolledEvent", "classEngine_1_1MouseScrolledEvent.html", "classEngine_1_1MouseScrolledEvent" ],
      [ "OpenGLIndexBuffer", "classEngine_1_1OpenGLIndexBuffer.html", "classEngine_1_1OpenGLIndexBuffer" ],
      [ "OpenGLVertexArray", "classEngine_1_1OpenGLVertexArray.html", "classEngine_1_1OpenGLVertexArray" ],
      [ "OpenGLVertexBuffer", "classEngine_1_1OpenGLVertexBuffer.html", "classEngine_1_1OpenGLVertexBuffer" ],
      [ "OpenGLWindow", "classEngine_1_1OpenGLWindow.html", "classEngine_1_1OpenGLWindow" ],
      [ "OrthographicCamera", "classEngine_1_1OrthographicCamera.html", "classEngine_1_1OrthographicCamera" ],
      [ "PerspectiveCamera", "classEngine_1_1PerspectiveCamera.html", "classEngine_1_1PerspectiveCamera" ],
      [ "PreprocessedRenderCommand", "structEngine_1_1PreprocessedRenderCommand.html", "structEngine_1_1PreprocessedRenderCommand" ],
      [ "Profiler", "classEngine_1_1Profiler.html", "classEngine_1_1Profiler" ],
      [ "ProfilerTimer", "classEngine_1_1ProfilerTimer.html", "classEngine_1_1ProfilerTimer" ],
      [ "QuadVertex", "structEngine_1_1QuadVertex.html", "structEngine_1_1QuadVertex" ],
      [ "RenderableObject", "classEngine_1_1RenderableObject.html", "classEngine_1_1RenderableObject" ],
      [ "RenderAPI", "classEngine_1_1RenderAPI.html", "classEngine_1_1RenderAPI" ],
      [ "RenderCommand", "structEngine_1_1RenderCommand.html", "structEngine_1_1RenderCommand" ],
      [ "Renderer", "classEngine_1_1Renderer.html", "classEngine_1_1Renderer" ],
      [ "Renderer2D", "classEngine_1_1Renderer2D.html", "classEngine_1_1Renderer2D" ],
      [ "Renderer2DData", "structEngine_1_1Renderer2DData.html", "structEngine_1_1Renderer2DData" ],
      [ "RenderObject", "classEngine_1_1RenderObject.html", "classEngine_1_1RenderObject" ],
      [ "Resource", "classEngine_1_1Resource.html", "classEngine_1_1Resource" ],
      [ "Scene", "classEngine_1_1Scene.html", "classEngine_1_1Scene" ],
      [ "SceneManager", "classEngine_1_1SceneManager.html", "classEngine_1_1SceneManager" ],
      [ "SceneObject", "classEngine_1_1SceneObject.html", "classEngine_1_1SceneObject" ],
      [ "Shader", "classEngine_1_1Shader.html", "classEngine_1_1Shader" ],
      [ "ShaderFactory", "classEngine_1_1ShaderFactory.html", "classEngine_1_1ShaderFactory" ],
      [ "ShaderHotReload", "classEngine_1_1ShaderHotReload.html", "classEngine_1_1ShaderHotReload" ],
      [ "ShaderLibrary", "classEngine_1_1ShaderLibrary.html", "classEngine_1_1ShaderLibrary" ],
      [ "TaskSystem", "classEngine_1_1TaskSystem.html", "classEngine_1_1TaskSystem" ],
      [ "TerrainSystem", "classEngine_1_1TerrainSystem.html", "classEngine_1_1TerrainSystem" ],
      [ "Texture", "classEngine_1_1Texture.html", "classEngine_1_1Texture" ],
      [ "ThreadPool", "classEngine_1_1ThreadPool.html", "classEngine_1_1ThreadPool" ],
      [ "Transform", "classEngine_1_1Transform.html", "classEngine_1_1Transform" ],
      [ "Vertex", "structEngine_1_1Vertex.html", "structEngine_1_1Vertex" ],
      [ "VertexArray", "classEngine_1_1VertexArray.html", "classEngine_1_1VertexArray" ],
      [ "VertexBuffer", "classEngine_1_1VertexBuffer.html", "classEngine_1_1VertexBuffer" ],
      [ "Window", "classEngine_1_1Window.html", "classEngine_1_1Window" ],
      [ "WindowCloseEvent", "classEngine_1_1WindowCloseEvent.html", "classEngine_1_1WindowCloseEvent" ],
      [ "WindowProps", "structEngine_1_1WindowProps.html", "structEngine_1_1WindowProps" ],
      [ "WindowResizeEvent", "classEngine_1_1WindowResizeEvent.html", "classEngine_1_1WindowResizeEvent" ]
    ] ],
    [ "ImGuiWidgetFlameGraph", "namespaceImGuiWidgetFlameGraph.html", [
      [ "FlameGraphSettings", "structImGuiWidgetFlameGraph_1_1FlameGraphSettings.html", "structImGuiWidgetFlameGraph_1_1FlameGraphSettings" ]
    ] ],
    [ "AssertionError", "classAssertionError.html", null ],
    [ "BlockTexture", "structBlockTexture.html", "structBlockTexture" ],
    [ "BMPWriter", "classBMPWriter.html", "classBMPWriter" ],
    [ "FPSCounter", "classFPSCounter.html", null ],
    [ "INoiseGenerator", "classINoiseGenerator.html", "classINoiseGenerator" ],
    [ "NoiseGenerator", "classNoiseGenerator.html", "classNoiseGenerator" ],
    [ "PerlinNoise", "classPerlinNoise.html", "classPerlinNoise" ],
    [ "SimplexNoise", "classSimplexNoise.html", "classSimplexNoise" ],
    [ "ValueNoise", "classValueNoise.html", "classValueNoise" ],
    [ "VoidNoise", "classVoidNoise.html", "classVoidNoise" ],
    [ "VoxelChunk", "classVoxelChunk.html", "classVoxelChunk" ],
    [ "VoxelTerrain", "classVoxelTerrain.html", "classVoxelTerrain" ]
];