Voxel Engine: Engine::WindowCloseEvent Class Reference
Engine::WindowCloseEvent Class Reference
Event triggered when window is closed.
#include <ApplicationEvent.h>
Public Member Functions
WindowCloseEvent ()
Constructs a window close event.
virtual EventType GetEventType () const override
virtual const char * GetName () const override
virtual int GetCategoryFlags () const override
WindowCloseEvent ()=default
virtual EventType GetEventType () const override
virtual const char * GetName () const override
virtual int GetCategoryFlags () const override
Public Member Functions inherited from Engine::Event
virtual ~Event ()=default
bool IsHandled () const
void SetHandled (bool handled)
virtual std::string ToString () const
virtual EventPriority GetPriority () const
virtual void SetPriority (EventPriority priority)
bool IsInCategory (EventCategory category) const
Checks if event belongs to a category.
uint64_t GetTimestamp () const
void SetTimestamp (uint64_t timestamp)
virtual std::string GetDebugInfo () const
virtual ~Event ()=default
virtual std::string ToString () const
bool IsInCategory (EventCategory category)
Checks if event belongs to a category.
Static Public Member Functions
static EventType GetStaticType ()
static EventType GetStaticType ()
Additional Inherited Members
Protected Member Functions inherited from Engine::Event
Event ()
Protected Attributes inherited from Engine::Event
bool m_Handled = false
Whether event has been handled.
EventPriority m_Priority = EventPriority::Normal
uint64_t m_Timestamp
Detailed Description
Event triggered when window is closed.
Signals that the window is being closed and the application should terminate.
Definition at line 41 of file ApplicationEvent.h.
Constructor & Destructor Documentation
WindowCloseEvent() [1/2]
Engine::WindowCloseEvent::WindowCloseEvent () inline
Constructs a window close event.
Definition at line 44 of file ApplicationEvent.h.
WindowCloseEvent() [2/2]
Engine::WindowCloseEvent::WindowCloseEvent () default
Member Function Documentation
GetCategoryFlags() [1/2]
virtual int Engine::WindowCloseEvent::GetCategoryFlags () const inline override virtual
Returns
Bit flags of categories this event belongs to
Implements Engine::Event.
Definition at line 50 of file ApplicationEvent.h.
References Engine::EventCategoryApplication.
GetCategoryFlags() [2/2]
virtual int Engine::WindowCloseEvent::GetCategoryFlags () const inline override virtual
Returns
Bit flags of categories this event belongs to
Implements Engine::Event.
Definition at line 45 of file WindowEvent.h.
References Engine::Application.
GetEventType() [1/2]
virtual EventType Engine::WindowCloseEvent::GetEventType () const inline override virtual
Returns
Type identifier for this event
Implements Engine::Event.
Definition at line 48 of file ApplicationEvent.h.
References GetStaticType().
GetEventType() [2/2]
virtual EventType Engine::WindowCloseEvent::GetEventType () const inline override virtual
Returns
Type identifier for this event
Implements Engine::Event.
Definition at line 43 of file WindowEvent.h.
References GetStaticType().
GetName() [1/2]
virtual const char * Engine::WindowCloseEvent::GetName () const inline override virtual
Returns
Human-readable name of the event
Implements Engine::Event.
Definition at line 49 of file ApplicationEvent.h.
GetName() [2/2]
virtual const char * Engine::WindowCloseEvent::GetName () const inline override virtual
Returns
Human-readable name of the event
Implements Engine::Event.
Definition at line 44 of file WindowEvent.h.
GetStaticType() [1/2]
static EventType Engine::WindowCloseEvent::GetStaticType () inline static
Returns
Static type identifier for this event
Definition at line 47 of file ApplicationEvent.h.
References Engine::WindowClose.
Referenced by GetEventType().
GetStaticType() [2/2]
static EventType Engine::WindowCloseEvent::GetStaticType () inline static
Returns
Static type identifier for this event
Definition at line 42 of file WindowEvent.h.
References Engine::WindowClose.
The documentation for this class was generated from the following files:
src/Events/ApplicationEvent.h
src/Events/WindowEvent.h