Voxel Engine: Engine::Logger Class Reference
Engine::Logger Class Reference
Singleton logger class for application-wide logging.
#include <Logging.h>
Public Member Functions
template<typename... Args>
void LogConcat (LogLevel level, Args &&... args)
Logs a concatenated message.
template<typename... Args>
void LogFormat (LogLevel level, const char *format, Args... args)
Logs a formatted message.
void Log (LogLevel level, const std::string &message)
template<typename T >
void LogValue (LogLevel level, const char *varName, const T &value)
Logs a variable's name and value.
template<typename... Args>
void LogValues (LogLevel level, Args &&... args)
Logs multiple variables' names and values.
Static Public Member Functions
static Logger & Get ()
Private Member Functions
template<typename T >
void LogValueImpl (std::stringstream &ss, const char *name, const T &value)
Logger ()=default
Detailed Description
Singleton logger class for application-wide logging.
Definition at line 185 of file Logging.h.
Constructor & Destructor Documentation
Logger()
Engine::Logger::Logger () private default
Member Function Documentation
Get()
static Logger & Engine::Logger::Get () inline static
Returns
Reference to the logger instance
Definition at line 188 of file Logging.h.
Log()
void Engine::Logger::Log (LogLevel level, const std::string & message) inline
Definition at line 219 of file Logging.h.
References Engine::Error, Engine::Fatal, Engine::Info, Engine::LogColors::Purple, Engine::LogColors::Red, Engine::LogColors::Reset, Engine::Trace, Engine::Warn, and Engine::LogColors::Yellow.
Referenced by LogConcat(), LogFormat(), LogValue(), and LogValues().
LogConcat()
template<typename... Args> void Engine::Logger::LogConcat (LogLevel level, Args &&... args) inline
Logs a concatenated message.
Template Parameters
Args Types of arguments to concatenate
Parameters
level Severity level of the message
args Arguments to concatenate into message
Definition at line 200 of file Logging.h.
References Log().
LogFormat()
template<typename... Args> void Engine::Logger::LogFormat (LogLevel level, const char * format, Args... args) inline
Logs a formatted message.
Template Parameters
Args Types of format arguments
Parameters
level Severity level of the message
format Format string
args Format arguments
Definition at line 215 of file Logging.h.
References Log().
LogValue()
template<typename T > void Engine::Logger::LogValue (LogLevel level, const char * varName, const T & value) inline
Logs a variable's name and value.
Template Parameters
T Type of the variable
Parameters
level Severity level of the message
varName Name of the variable
value Value of the variable
Definition at line 262 of file Logging.h.
References Log(), and Engine::ToString().
LogValueImpl()
template<typename T > void Engine::Logger::LogValueImpl (std::stringstream & ss, const char * name, const T & value) inline private
Definition at line 283 of file Logging.h.
References Engine::ToString().
Referenced by LogValues().
LogValues()
template<typename... Args> void Engine::Logger::LogValues (LogLevel level, Args &&... args) inline
Logs multiple variables' names and values.
Template Parameters
Args Types of the variables
Parameters
level Severity level of the message
args Pairs of variable names and values
Definition at line 275 of file Logging.h.
References Log(), and LogValueImpl().
The documentation for this class was generated from the following file:
src/Core/Utils/Logging.h