Voxel Engine: Engine::LuaScriptSystem Class Reference
Engine::LuaScriptSystem Class Reference
#include <LuaScriptSystem.h>
Public Member Functions
LuaScriptSystem ()
Constructs a new LuaScriptSystem instance and initializes the Lua state.
~LuaScriptSystem ()
Default destructor for the LuaScriptSystem.
LuaScriptSystem (const LuaScriptSystem &)=delete
LuaScriptSystem & operator= (const LuaScriptSystem &)=delete
LuaScriptSystem (LuaScriptSystem &&)=default
LuaScriptSystem & operator= (LuaScriptSystem &&)=default
void Initialize ()
Initialize the Lua scripting system.
bool ExecuteScript (const std::string &script)
Execute a Lua script from a string.
bool ExecuteFile (const std::string &filepath)
Execute a Lua script from a file.
void CallGlobalFunction (const std::string &functionName)
Private Member Functions
void RegisterEngineAPI ()
Registers the engine's API functions for Lua scripting.
Private Attributes
std::unique_ptr< sol::state > m_LuaState
Detailed Description
Definition at line 11 of file LuaScriptSystem.h.
Constructor & Destructor Documentation
LuaScriptSystem() [1/3]
Engine::LuaScriptSystem::LuaScriptSystem ()
Constructs a new LuaScriptSystem instance and initializes the Lua state.
Creates a unique pointer to a Lua state and opens standard Lua libraries to prepare the scripting environment. The opened libraries include:
Base library (standard Lua functions)
Package library (module loading)
Math library (mathematical operations)
String library (string manipulation)
Table library (table operations)
IO library (input/output operations)
OS library (operating system interactions)
Note
This constructor sets up a fully functional Lua scripting environment ready for engine integration and script execution.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 36 of file LuaScriptSystem.cpp.
References m_LuaState.
~LuaScriptSystem()
Engine::LuaScriptSystem::~LuaScriptSystem () default
Default destructor for the LuaScriptSystem.
Cleans up the LuaScriptSystem instance, allowing for proper resource management when the object goes out of scope or is explicitly deleted. The default implementation ensures that any resources managed by the base class or compiler-generated destructors are properly released.
Note
This destructor is defaulted, meaning the compiler will generate the default implementation for destroying the LuaScriptSystem object.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
LuaScriptSystem() [2/3]
Engine::LuaScriptSystem::LuaScriptSystem (const LuaScriptSystem &) delete
LuaScriptSystem() [3/3]
Engine::LuaScriptSystem::LuaScriptSystem (LuaScriptSystem &&) default
Member Function Documentation
CallGlobalFunction()
void Engine::LuaScriptSystem::CallGlobalFunction (const std::string & functionName)
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 612 of file LuaScriptSystem.cpp.
References LOG_WARN.
ExecuteFile()
bool Engine::LuaScriptSystem::ExecuteFile (const std::string & originalPath)
Execute a Lua script from a file.
Attempts to locate and execute a Lua script file from multiple potential search paths.
Parameters
filepath Path to the Lua script file
Returns
true if execution succeeded, false otherwise
This method searches for the specified script file in several predefined locations:
The original path provided
Relative paths with "../" and "../../" prefixes
Predefined script directories with the filename extracted from the original path
Parameters
originalPath The initial file path of the Lua script to be executed
Returns
bool True if the script is successfully found and executed, false otherwise
Searches through a list of potential file paths
Uses FileSystem::Exists() to verify file presence
Logs an error if the script cannot be found
Attempts to load and execute the script using sol2 library
Logs an error if script loading or execution fails
Note
Supports relative and absolute file paths
Extracts filename from the original path for additional search locations
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 581 of file LuaScriptSystem.cpp.
References Engine::FileSystem::Exists(), LOG_ERROR, and m_LuaState.
Referenced by RegisterEngineAPI().
ExecuteScript()
bool Engine::LuaScriptSystem::ExecuteScript (const std::string & script)
Execute a Lua script from a string.
Parameters
script The Lua script to execute
Returns
true if execution succeeded, false otherwise
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 542 of file LuaScriptSystem.cpp.
References LOG_ERROR_CONCAT, and m_LuaState.
Initialize()
void Engine::LuaScriptSystem::Initialize ()
Initialize the Lua scripting system.
Initializes the Lua scripting system by registering the engine's API.
Returns
true if initialization succeeded, false otherwise
This method calls the RegisterEngineAPI() function to set up the Lua environment with various engine-specific functions and APIs, enabling Lua scripts to interact with different engine components such as terrain, rendering, scene management, input handling, and debugging.
Note
This method must be called after creating a LuaScriptSystem instance to ensure that the Lua scripting environment is properly configured and ready for use.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 65 of file LuaScriptSystem.cpp.
References RegisterEngineAPI().
operator=() [1/2]
LuaScriptSystem & Engine::LuaScriptSystem::operator= (const LuaScriptSystem &) delete
operator=() [2/2]
LuaScriptSystem & Engine::LuaScriptSystem::operator= (LuaScriptSystem &&) default
RegisterEngineAPI()
void Engine::LuaScriptSystem::RegisterEngineAPI () private
Registers the engine's API functions for Lua scripting.
This method creates a named table 'engine' in the Lua state and populates it with various functions that allow Lua scripts to interact with different engine systems.
The registered API includes functionality for:
Terrain manipulation (height setting, mesh generation)
Renderer controls (clear color, viewport, camera type)
Scene management (create, set active, delete scenes)
Input handling (key/mouse button states, mouse position)
Logging and debugging
Profiling
Camera control
ImGui overlay controls
Note
Functions are registered as lambda functions that interact with various engine systems like SceneManager, Renderer, Application, and ImGuiOverlay.
Warning
Some functions have safety checks to prevent operations on null systems or inactive scenes, with appropriate error logging.
See also
LuaScriptSystem
SceneManager
Renderer
Application
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 95 of file LuaScriptSystem.cpp.
References Engine::SceneManager::AddScene(), Engine::Renderer::Clear(), Engine::ShaderLibrary::CreateBasicShader(), Engine::FileSystem::CreateDirectory(), Engine::Renderer2D::DrawQuad(), Engine::Renderer2D::EndScene(), ExecuteFile(), Engine::FileSystem::Exists(), Engine::Application::Get(), Engine::AssetManager::Get(), Engine::Renderer::Get(), Engine::Renderer2D::Get(), Engine::SceneManager::Get(), Engine::SceneManager::GetActiveScene(), Engine::Renderer::GetCameraType(), Engine::Application::GetInputSystem(), Engine::SceneObject::GetMaterial(), Engine::SceneObject::GetMesh(), Engine::Transform::GetModelMatrix(), Engine::InputSystem::GetMousePosition(), Engine::InputSystem::GetMovementSpeed(), Engine::Renderer::GetPerspectiveCamera(), Engine::Transform::GetPosition(), Engine::Application::GetRenderer(), Engine::Application::GetRenderType(), Engine::Transform::GetRotation(), Engine::Transform::GetScale(), Engine::InputSystem::GetSensitivity(), Engine::SceneObject::GetTransform(), Engine::Renderer2D::Initialize(), Engine::InputSystem::IsKeyPressed(), Engine::InputSystem::IsMouseButtonPressed(), LOG_ERROR, LOG_ERROR_CONCAT, LOG_FATAL_CONCAT, LOG_INFO_CONCAT, LOG_TRACE_CONCAT, LOG_WARN_CONCAT, m_LuaState, Engine::SceneObject::name, Engine::Orthographic, Engine::Renderer::Orthographic, Engine::Perspective, Engine::Renderer::Perspective, PROFILE_FUNCTION, PROFILE_SCOPE, Engine::Render2D, Engine::Render3D, Engine::Application::SetCameraType(), Engine::SceneObject::SetMaterial(), Engine::SceneObject::SetMesh(), Engine::InputSystem::SetMovementSpeed(), Engine::Transform::SetPosition(), Engine::Application::SetRenderType(), Engine::Transform::SetRotation(), Engine::Transform::SetScale(), Engine::InputSystem::SetSensitivity(), Engine::Renderer::SetViewport(), Engine::InputSystem::ToggleCameraControls(), Engine::InputSystem::ToggleMovementLock(), and Engine::InputSystem::ToggleSmoothCamera().
Referenced by Initialize().
Member Data Documentation
m_LuaState
std::unique_ptr<sol::state> Engine::LuaScriptSystem::m_LuaState private
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 40 of file LuaScriptSystem.h.
Referenced by ExecuteFile(), ExecuteScript(), LuaScriptSystem(), and RegisterEngineAPI().
The documentation for this class was generated from the following files:
src/Scripting/LuaScriptSystem.h
src/Scripting/LuaScriptSystem.cpp