Voxel Engine: Engine::Renderer2D Class Reference
Engine::Renderer2D Class Reference
Specialized renderer for 2D graphics with batching support.
#include <Renderer2D.h>
Public Member Functions
void Initialize () override
void Shutdown () override
void BeginScene () override
void EndScene () override
void Flush () override
Statistics GetStats () const override
void ResetStats () override
void BeginScene (const std::shared_ptr< OrthographicCamera > &camera)
void DrawQuad (const glm::vec2 &position, const glm::vec2 &size, const glm::vec4 &color)
void DrawQuad (const glm::vec3 &position, const glm::vec2 &size, const glm::vec4 &color)
void DrawQuad (const glm::vec2 &position, const glm::vec2 &size, const std::shared_ptr< Texture > &texture, float tilingFactor=1.0f, const glm::vec4 &tintColor=glm::vec4(1.0f))
void DrawQuad (const glm::vec3 &position, const glm::vec2 &size, const std::shared_ptr< Texture > &texture, float tilingFactor=1.0f, const glm::vec4 &tintColor=glm::vec4(1.0f))
Public Member Functions inherited from Engine::IRenderer
virtual ~IRenderer ()=default
Static Public Member Functions
static Renderer2D & Get ()
Private Member Functions
Renderer2D ()=default
void StartBatch ()
void NextBatch ()
Private Attributes
Statistics m_Stats
std::shared_ptr< Material > m_Material
Detailed Description
Specialized renderer for 2D graphics with batching support.
Definition at line 14 of file Renderer2D.h.
Constructor & Destructor Documentation
Renderer2D()
Engine::Renderer2D::Renderer2D () private default
Member Function Documentation
BeginScene() [1/2]
void Engine::Renderer2D::BeginScene () override virtual
Implements Engine::IRenderer.
Definition at line 113 of file Renderer2D.cpp.
BeginScene() [2/2]
void Engine::Renderer2D::BeginScene (const std::shared_ptr< OrthographicCamera > & camera)
Definition at line 117 of file Renderer2D.cpp.
References Engine::s_Data, StartBatch(), and Engine::Renderer2DData::TextureMaterial.
DrawQuad() [1/4]
void Engine::Renderer2D::DrawQuad (const glm::vec2 & position, const glm::vec2 & size, const glm::vec4 & color)
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 158 of file Renderer2D.cpp.
References DrawQuad().
Referenced by DrawQuad(), DrawQuad(), and Engine::LuaScriptSystem::RegisterEngineAPI().
DrawQuad() [2/4]
void Engine::Renderer2D::DrawQuad (const glm::vec2 & position, const glm::vec2 & size, const std::shared_ptr< Texture > & texture, float tilingFactor = 1.0f, const glm::vec4 & tintColor = glm::vec4(1.0f))
Definition at line 187 of file Renderer2D.cpp.
References DrawQuad().
DrawQuad() [3/4]
void Engine::Renderer2D::DrawQuad (const glm::vec3 & position, const glm::vec2 & size, const glm::vec4 & color)
Definition at line 163 of file Renderer2D.cpp.
References Engine::QuadVertex::Color, Engine::Renderer2DData::MaxIndices, NextBatch(), Engine::QuadVertex::Position, Engine::Renderer2DData::QuadIndexCount, Engine::Renderer2DData::QuadVertexBufferPtr, Engine::Renderer2DData::QuadVertexPositions, Engine::s_Data, Engine::QuadVertex::TexCoord, Engine::QuadVertex::TexIndex, and Engine::QuadVertex::TilingFactor.
DrawQuad() [4/4]
void Engine::Renderer2D::DrawQuad (const glm::vec3 & position, const glm::vec2 & size, const std::shared_ptr< Texture > & texture, float tilingFactor = 1.0f, const glm::vec4 & tintColor = glm::vec4(1.0f))
Definition at line 193 of file Renderer2D.cpp.
References Engine::QuadVertex::Color, Engine::Renderer2DData::MaxIndices, Engine::Renderer2DData::MaxTextureSlots, NextBatch(), Engine::QuadVertex::Position, Engine::Renderer2DData::QuadIndexCount, Engine::Renderer2DData::QuadVertexBufferPtr, Engine::Renderer2DData::QuadVertexPositions, Engine::s_Data, Engine::QuadVertex::TexCoord, Engine::QuadVertex::TexIndex, Engine::Renderer2DData::TextureSlotIndex, Engine::Renderer2DData::TextureSlots, and Engine::QuadVertex::TilingFactor.
EndScene()
void Engine::Renderer2D::EndScene () override virtual
Implements Engine::IRenderer.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 129 of file Renderer2D.cpp.
References Flush().
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Flush()
void Engine::Renderer2D::Flush () override virtual
Implements Engine::IRenderer.
Definition at line 137 of file Renderer2D.cpp.
References Engine::IRenderer::Statistics::DrawCalls, Engine::IRenderer::Statistics::IndexCount, m_Stats, Engine::Renderer2DData::QuadIndexCount, Engine::Renderer2DData::QuadVertexArray, Engine::Renderer2DData::QuadVertexBuffer, Engine::Renderer2DData::QuadVertexBufferBase, Engine::Renderer2DData::QuadVertexBufferPtr, Engine::s_Data, Engine::Renderer2DData::TextureMaterial, Engine::Renderer2DData::TextureSlotIndex, Engine::Renderer2DData::TextureSlots, and Engine::IRenderer::Statistics::VertexCount.
Referenced by EndScene(), and NextBatch().
Get()
static Renderer2D & Engine::Renderer2D::Get () inline static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 16 of file Renderer2D.h.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetStats()
Statistics Engine::Renderer2D::GetStats () const inline override virtual
Implements Engine::IRenderer.
Definition at line 27 of file Renderer2D.h.
References m_Stats.
Initialize()
void Engine::Renderer2D::Initialize () override virtual
Implements Engine::IRenderer.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 43 of file Renderer2D.cpp.
References Engine::VertexArray::Create(), Engine::VertexBuffer::Create(), Engine::IndexBuffer::Create(), Engine::ShaderLibrary::CreateBatchRenderer2DShader(), Engine::Float, Engine::Float2, Engine::Float3, Engine::Float4, LOG_ERROR, Engine::Renderer2DData::MaxIndices, Engine::Renderer2DData::MaxVertices, Engine::Renderer2DData::QuadVertexArray, Engine::Renderer2DData::QuadVertexBuffer, Engine::Renderer2DData::QuadVertexBufferBase, Engine::Renderer2DData::QuadVertexPositions, Engine::s_Data, Engine::Renderer2DData::TextureMaterial, Engine::Renderer2DData::TextureSlots, and Engine::Renderer2DData::WhiteTexture.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
NextBatch()
void Engine::Renderer2D::NextBatch () private
Definition at line 230 of file Renderer2D.cpp.
References Flush(), and StartBatch().
Referenced by DrawQuad(), and DrawQuad().
ResetStats()
void Engine::Renderer2D::ResetStats () inline override virtual
Implements Engine::IRenderer.
Definition at line 28 of file Renderer2D.h.
References m_Stats, and Engine::IRenderer::Statistics::Reset().
Shutdown()
void Engine::Renderer2D::Shutdown () override virtual
Implements Engine::IRenderer.
Definition at line 111 of file Renderer2D.cpp.
References Engine::Renderer2DData::QuadVertexBufferBase, and Engine::s_Data.
StartBatch()
void Engine::Renderer2D::StartBatch () private
Definition at line 131 of file Renderer2D.cpp.
References Engine::Renderer2DData::QuadIndexCount, Engine::Renderer2DData::QuadVertexBufferBase, Engine::Renderer2DData::QuadVertexBufferPtr, Engine::s_Data, and Engine::Renderer2DData::TextureSlotIndex.
Referenced by BeginScene(), and NextBatch().
Member Data Documentation
m_Material
std::shared_ptr<Material> Engine::Renderer2D::m_Material private
Definition at line 47 of file Renderer2D.h.
m_Stats
Statistics Engine::Renderer2D::m_Stats private
Definition at line 46 of file Renderer2D.h.
Referenced by Flush(), GetStats(), and ResetStats().
The documentation for this class was generated from the following files:
src/Renderer/Renderer2D.h
src/Renderer/Renderer2D.cpp