Voxel Engine: Engine::TerrainSystem Class Reference
Engine::TerrainSystem Class Reference
Manages voxel terrain generation and rendering.
#include <TerrainSystem.h>
Public Member Functions
TerrainSystem ()
Constructs terrain system with default parameters.
~TerrainSystem ()=default
void Initialize (Renderer &renderer)
Initializes terrain system with renderer.
void Update (float deltaTime)
Updates terrain state.
void Render (Renderer &renderer)
Renders terrain using provided renderer.
void RegenerateTerrain (uint32_t seed)
Regenerates terrain with new seed.
void SetChunkRange (int range)
Sets the range of chunks to generate.
int GetChunkRange () const
void SetBaseHeight (float height)
Sets base height for terrain generation.
void SetHeightScale (float scale)
Sets height scale factor for terrain.
void SetNoiseScale (float scale)
Sets noise scale for terrain variation.
float GetBaseHeight () const
float GetHeightScale () const
float GetNoiseScale () const
void GenerateMesh ()
Generates terrain mesh based on current parameters.
void GenerateMesh (uint32_t seed)
Generates a terrain mesh with a specified random seed.
void Shutdown ()
Private Attributes
std::unique_ptr< VoxelTerrain > m_Terrain
Voxel data container.
std::shared_ptr< VertexArray > m_TerrainVA
Terrain vertex array.
std::shared_ptr< Shader > m_TerrainShader
Terrain shader.
std::shared_ptr< Material > m_TerrainMaterial
Terrain material.
std::shared_ptr< Texture > m_TerrainTexture
Terrain texture.
Transform m_TerrainTransform
Terrain transformation.
int m_ChunkRange = 1
Chunk generation range.
float m_BaseHeight = 32.0f
Base terrain height.
float m_HeightScale = 32.0f
Height variation scale.
float m_NoiseScale = 0.05f
Noise variation scale.
bool m_IsInitialized = false
std::shared_ptr< RenderObject > m_TerrainMesh
NoiseGenerator< VoidNoise > m_NoiseGen
Detailed Description
Manages voxel terrain generation and rendering.
Handles terrain mesh generation, updates, and rendering using a voxel-based system with configurable parameters.
Definition at line 24 of file TerrainSystem.h.
Constructor & Destructor Documentation
TerrainSystem()
Engine::TerrainSystem::TerrainSystem ()
Constructs terrain system with default parameters.
Initializes terrain with random seed, loads textures and shaders, and generates initial terrain mesh.
Definition at line 24 of file TerrainSystem.cpp.
References Engine::Texture::Create(), GenerateMesh(), Engine::ShaderLibrary::LoadTexturedShader(), LOG_ERROR, m_BaseHeight, m_HeightScale, m_NoiseScale, m_TerrainMaterial, m_TerrainShader, m_TerrainTexture, m_TerrainTransform, Engine::Transform::SetPosition(), and Engine::Transform::SetScale().
~TerrainSystem()
Engine::TerrainSystem::~TerrainSystem () default
Member Function Documentation
GenerateMesh() [1/2]
void Engine::TerrainSystem::GenerateMesh ()
Generates terrain mesh based on current parameters.
Generates a terrain mesh using procedural noise.
Creates a detailed terrain mesh by generating vertex and index buffers based on a heightmap. The method uses noise generation to create terrain geometry with configurable base height, height scale, and noise scale.
The terrain is constructed as a grid of quads, with each vertex having a calculated height based on the noise generator. Texture coordinates are also generated for proper mapping.
The method performs the following key steps:
Generates a heightmap using the noise generator
Calculates vertex heights based on base height and height scale
Creates vertices with 3D positions and 2D texture coordinates
Generates indices to form triangles for rendering
Creates a vertex array with vertex and index buffers
Note
The terrain size is determined by m_ChunkRange, with a default map size of (m_ChunkRange * 2 + 1) * 16
Warning
Modifies the internal terrain vertex array (m_TerrainVA)
See also
TerrainSystem::SetBaseHeight
TerrainSystem::SetHeightScale
TerrainSystem::SetNoiseScale
Definition at line 117 of file TerrainSystem.cpp.
References Engine::VertexArray::Create(), Engine::VertexBuffer::Create(), Engine::IndexBuffer::Create(), Engine::Float2, Engine::Float3, NoiseGenerator< T >::getHeightmap(), LOG_TRACE_CONCAT, m_BaseHeight, m_ChunkRange, m_HeightScale, m_NoiseGen, m_NoiseScale, and m_TerrainVA.
Referenced by GenerateMesh(), RegenerateTerrain(), SetBaseHeight(), SetChunkRange(), SetHeightScale(), SetNoiseScale(), and TerrainSystem().
GenerateMesh() [2/2]
void Engine::TerrainSystem::GenerateMesh (uint32_t seed)
Generates a terrain mesh with a specified random seed.
This method allows regenerating the terrain mesh using a custom seed for the noise generator. It sets the noise generator to a new seed and then calls the standard mesh generation method.
Parameters
seed The random seed used to initialize the noise generator for terrain height variation.
Note
This method provides more control over terrain generation by allowing reproducible terrain through seed specification.
Definition at line 189 of file TerrainSystem.cpp.
References GenerateMesh(), and m_NoiseGen.
GetBaseHeight()
float Engine::TerrainSystem::GetBaseHeight () const inline
Returns
Base terrain height
Definition at line 67 of file TerrainSystem.h.
References m_BaseHeight.
GetChunkRange()
int Engine::TerrainSystem::GetChunkRange () const inline
Returns
Current chunk generation range
Definition at line 57 of file TerrainSystem.h.
References m_ChunkRange.
GetHeightScale()
float Engine::TerrainSystem::GetHeightScale () const inline
Returns
Height scale factor
Definition at line 69 of file TerrainSystem.h.
References m_HeightScale.
GetNoiseScale()
float Engine::TerrainSystem::GetNoiseScale () const inline
Returns
Noise scale factor
Definition at line 71 of file TerrainSystem.h.
References m_NoiseScale.
Initialize()
void Engine::TerrainSystem::Initialize (Renderer & renderer)
Initializes terrain system with renderer.
Definition at line 53 of file TerrainSystem.cpp.
Referenced by Engine::Application::ConfigureForRenderType().
RegenerateTerrain()
void Engine::TerrainSystem::RegenerateTerrain (uint32_t seed)
Regenerates terrain with new seed.
Parameters
seed Random seed for terrain generation
Definition at line 85 of file TerrainSystem.cpp.
References GenerateMesh(), and m_NoiseGen.
Render()
void Engine::TerrainSystem::Render (Renderer & renderer)
Renders terrain using provided renderer.
Parameters
renderer Renderer to use
Definition at line 79 of file TerrainSystem.cpp.
References Engine::Transform::GetModelMatrix(), m_TerrainMaterial, m_TerrainTransform, m_TerrainVA, and Engine::Renderer::Submit().
SetBaseHeight()
void Engine::TerrainSystem::SetBaseHeight (float height)
Sets base height for terrain generation.
Sets the base height for terrain generation and regenerates the terrain mesh.
Parameters
height The new base height value to be used for terrain generation.
This method updates the base height parameter of the terrain system and immediately triggers a mesh regeneration to reflect the new height setting. The base height affects the overall vertical positioning of the terrain.
Note
Calling this method will cause the terrain mesh to be completely regenerated with the new base height parameter.
Definition at line 209 of file TerrainSystem.cpp.
References GenerateMesh(), and m_BaseHeight.
SetChunkRange()
void Engine::TerrainSystem::SetChunkRange (int range) inline
Sets the range of chunks to generate.
Parameters
range Number of chunks in each direction
Definition at line 54 of file TerrainSystem.h.
References GenerateMesh(), and m_ChunkRange.
SetHeightScale()
void Engine::TerrainSystem::SetHeightScale (float scale)
Sets height scale factor for terrain.
Definition at line 214 of file TerrainSystem.cpp.
References GenerateMesh(), and m_HeightScale.
SetNoiseScale()
void Engine::TerrainSystem::SetNoiseScale (float scale)
Sets noise scale for terrain variation.
Definition at line 219 of file TerrainSystem.cpp.
References GenerateMesh(), and m_NoiseScale.
Shutdown()
void Engine::TerrainSystem::Shutdown () inline
Definition at line 77 of file TerrainSystem.h.
References m_IsInitialized, m_TerrainMaterial, and m_TerrainMesh.
Referenced by Engine::Application::ConfigureForRenderType(), and Engine::Application::~Application().
Update()
void Engine::TerrainSystem::Update (float deltaTime)
Updates terrain state.
Updates the terrain system state and logs terrain transform information.
Parameters
deltaTime Time since last update
This method logs the terrain's current transform (position and scale) only once during the first update cycle. Subsequent calls will not repeat the logging.
Parameters
deltaTime The time elapsed since the last update frame, unused in this implementation.
Note
The logging is performed at the TRACE level, providing detailed system information.
The logging occurs only once due to the static 'logged' flag.
Definition at line 68 of file TerrainSystem.cpp.
References Engine::Transform::GetPosition(), Engine::Transform::GetScale(), LOG_TRACE_CONCAT, and m_TerrainTransform.
Member Data Documentation
m_BaseHeight
float Engine::TerrainSystem::m_BaseHeight = 32.0f private
Base terrain height.
Definition at line 93 of file TerrainSystem.h.
Referenced by GenerateMesh(), GetBaseHeight(), SetBaseHeight(), and TerrainSystem().
m_ChunkRange
int Engine::TerrainSystem::m_ChunkRange = 1 private
Chunk generation range.
Definition at line 91 of file TerrainSystem.h.
Referenced by GenerateMesh(), GetChunkRange(), and SetChunkRange().
m_HeightScale
float Engine::TerrainSystem::m_HeightScale = 32.0f private
Height variation scale.
Definition at line 94 of file TerrainSystem.h.
Referenced by GenerateMesh(), GetHeightScale(), SetHeightScale(), and TerrainSystem().
m_IsInitialized
bool Engine::TerrainSystem::m_IsInitialized = false private
Definition at line 97 of file TerrainSystem.h.
Referenced by Shutdown().
m_NoiseGen
NoiseGenerator<VoidNoise> Engine::TerrainSystem::m_NoiseGen private
Definition at line 101 of file TerrainSystem.h.
Referenced by GenerateMesh(), GenerateMesh(), and RegenerateTerrain().
m_NoiseScale
float Engine::TerrainSystem::m_NoiseScale = 0.05f private
Noise variation scale.
Definition at line 95 of file TerrainSystem.h.
Referenced by GenerateMesh(), GetNoiseScale(), SetNoiseScale(), and TerrainSystem().
m_Terrain
std::unique_ptr<VoxelTerrain> Engine::TerrainSystem::m_Terrain private
Voxel data container.
Definition at line 85 of file TerrainSystem.h.
m_TerrainMaterial
std::shared_ptr<Material> Engine::TerrainSystem::m_TerrainMaterial private
Terrain material.
Definition at line 88 of file TerrainSystem.h.
Referenced by Render(), Shutdown(), and TerrainSystem().
m_TerrainMesh
std::shared_ptr<RenderObject> Engine::TerrainSystem::m_TerrainMesh private
Definition at line 98 of file TerrainSystem.h.
Referenced by Shutdown().
m_TerrainShader
std::shared_ptr<Shader> Engine::TerrainSystem::m_TerrainShader private
Terrain shader.
Definition at line 87 of file TerrainSystem.h.
Referenced by TerrainSystem().
m_TerrainTexture
std::shared_ptr<Texture> Engine::TerrainSystem::m_TerrainTexture private
Terrain texture.
Definition at line 89 of file TerrainSystem.h.
Referenced by TerrainSystem().
m_TerrainTransform
Transform Engine::TerrainSystem::m_TerrainTransform private
Terrain transformation.
Definition at line 90 of file TerrainSystem.h.
Referenced by Render(), TerrainSystem(), and Update().
m_TerrainVA
std::shared_ptr<VertexArray> Engine::TerrainSystem::m_TerrainVA private
Terrain vertex array.
Definition at line 86 of file TerrainSystem.h.
Referenced by GenerateMesh(), and Render().
The documentation for this class was generated from the following files:
src/TerrainSystem/TerrainSystem.h
src/TerrainSystem/TerrainSystem.cpp