Voxel Engine: VoxelTerrain Class Reference
VoxelTerrain Class Reference
Manages the voxel-based terrain system.
#include <VoxelTerrain.h>
Public Member Functions
VoxelTerrain (unsigned int seed=1234)
Construct a new Voxel Terrain.
void generateChunk (int chunkX, int chunkY, int chunkZ)
Generate a new chunk at specified coordinates.
bool getVoxel (int x, int y, int z) const
Get voxel state at specified world coordinates.
void setVoxel (int x, int y, int z, bool value)
Set voxel state at specified world coordinates.
void setTerrainParameters (float noiseScale, float terrainScale, int waterLevel, int maxHeight)
Private Member Functions
VoxelChunk * getChunk (int chunkX, int chunkY, int chunkZ) const
Get chunk at specified coordinates.
void SaveHeightmapDebug (int chunkX, int chunkZ)
Static Private Member Functions
static uint64_t getChunkKey (int x, int y, int z)
Generate unique key for chunk coordinates.
Private Attributes
VoidNoise m_NoiseGenerator
std::unordered_map< uint64_t, std::unique_ptr< VoxelChunk > > m_Chunks
float m_TerrainScale = 8.0f
float m_NoiseScale = 3.0f
int m_WaterLevel = 32
int m_MaxHeight = 128
Detailed Description
Manages the voxel-based terrain system.
Handles chunk generation, storage, and voxel access across the world
Definition at line 11 of file VoxelTerrain.h.
Constructor & Destructor Documentation
VoxelTerrain()
VoxelTerrain::VoxelTerrain (unsigned int seed = 1234)
Construct a new Voxel Terrain.
Initialize terrain system with seed.
Parameters
seed Random seed for terrain generation
Definition at line 8 of file VoxelTerrain.cpp.
Member Function Documentation
generateChunk()
void VoxelTerrain::generateChunk (int chunkX, int chunkY, int chunkZ)
Generate a new chunk at specified coordinates.
Generate new chunk at specified coordinates.
Parameters
chunkX X coordinate of chunk
chunkY Y coordinate of chunk
chunkZ Z coordinate of chunk
chunkX X coordinate in chunk space
chunkY Y coordinate in chunk space
chunkZ Z coordinate in chunk space
Definition at line 17 of file VoxelTerrain.cpp.
References getChunkKey(), m_Chunks, m_NoiseGenerator, m_TerrainScale, and SaveHeightmapDebug().
Referenced by setVoxel().
getChunk()
VoxelChunk * VoxelTerrain::getChunk (int chunkX, int chunkY, int chunkZ) const private
Get chunk at specified coordinates.
Parameters
chunkX Chunk X coordinate
chunkY Chunk Y coordinate
chunkZ Chunk Z coordinate
Returns
VoxelChunk* Pointer to chunk or nullptr if not found
Parameters
chunkX X coordinate in chunk space
chunkY Y coordinate in chunk space
chunkZ Z coordinate in chunk space
Returns
VoxelChunk* Pointer to chunk or nullptr if not found
Definition at line 81 of file VoxelTerrain.cpp.
References getChunkKey(), and m_Chunks.
Referenced by getVoxel().
getChunkKey()
uint64_t VoxelTerrain::getChunkKey (int x, int y, int z) static private
Generate unique key for chunk coordinates.
Parameters
x Chunk X coordinate
y Chunk Y coordinate
z Chunk Z coordinate
Returns
uint64_t Unique chunk identifier
Definition at line 87 of file VoxelTerrain.cpp.
Referenced by generateChunk(), getChunk(), and setVoxel().
getVoxel()
bool VoxelTerrain::getVoxel (int x, int y, int z) const
Get voxel state at specified world coordinates.
Get voxel state at world coordinates.
Parameters
x X coordinate in world space
y Y coordinate in world space
z Z coordinate in world space
Returns
bool True if voxel is solid, false otherwise
Parameters
x X coordinate in world space
y Y coordinate in world space
z Z coordinate in world space
Returns
bool True if voxel is solid
Definition at line 37 of file VoxelTerrain.cpp.
References VoxelChunk::CHUNK_SIZE, getChunk(), and VoxelChunk::getData().
SaveHeightmapDebug()
void VoxelTerrain::SaveHeightmapDebug (int chunkX, int chunkZ) private
Definition at line 93 of file VoxelTerrain.cpp.
References VoxelChunk::CHUNK_SIZE, LOG_TRACE_CONCAT, m_NoiseGenerator, m_NoiseScale, m_WaterLevel, VoidNoise::noise(), and BMPWriter::SaveGrayscaleBMP().
Referenced by generateChunk().
setTerrainParameters()
void VoxelTerrain::setTerrainParameters (float noiseScale, float terrainScale, int waterLevel, int maxHeight) inline
Definition at line 45 of file VoxelTerrain.h.
References m_MaxHeight, m_NoiseScale, m_TerrainScale, and m_WaterLevel.
setVoxel()
void VoxelTerrain::setVoxel (int x, int y, int z, bool value)
Set voxel state at specified world coordinates.
Set voxel state and generate chunk if needed.
Parameters
x X coordinate in world space
y Y coordinate in world space
z Z coordinate in world space
value New voxel state
Definition at line 63 of file VoxelTerrain.cpp.
References VoxelChunk::CHUNK_SIZE, generateChunk(), getChunkKey(), and m_Chunks.
Member Data Documentation
m_Chunks
std::unordered_map<uint64_t, std::unique_ptr<VoxelChunk> > VoxelTerrain::m_Chunks private
Definition at line 54 of file VoxelTerrain.h.
Referenced by generateChunk(), getChunk(), and setVoxel().
m_MaxHeight
int VoxelTerrain::m_MaxHeight = 128 private
Definition at line 58 of file VoxelTerrain.h.
Referenced by setTerrainParameters().
m_NoiseGenerator
VoidNoise VoxelTerrain::m_NoiseGenerator private
Definition at line 53 of file VoxelTerrain.h.
Referenced by generateChunk(), and SaveHeightmapDebug().
m_NoiseScale
float VoxelTerrain::m_NoiseScale = 3.0f private
Definition at line 56 of file VoxelTerrain.h.
Referenced by SaveHeightmapDebug(), and setTerrainParameters().
m_TerrainScale
float VoxelTerrain::m_TerrainScale = 8.0f private
Definition at line 55 of file VoxelTerrain.h.
Referenced by generateChunk(), and setTerrainParameters().
m_WaterLevel
int VoxelTerrain::m_WaterLevel = 32 private
Definition at line 57 of file VoxelTerrain.h.
Referenced by SaveHeightmapDebug(), and setTerrainParameters().
The documentation for this class was generated from the following files:
src/VoxelTerrain.h
src/VoxelTerrain.cpp