Voxel Engine: Engine::SceneObject Class Reference
Engine::SceneObject Class Reference
#include <SceneObject.h>
Public Member Functions
SceneObject (const std::string &objectName="Object")
virtual ~SceneObject ()=default
void OnRender (Renderer &renderer) override
Called when object should be rendered.
void AddChild (const std::shared_ptr< SceneObject > &child)
glm::mat4 GetWorldTransform () const
void SetMesh (const std::shared_ptr< VertexArray > &mesh)
void SetMaterial (const std::shared_ptr< Material > &material)
const std::shared_ptr< VertexArray > & GetMesh () const
const std::shared_ptr< Material > & GetMaterial () const
Transform & GetTransform ()
const Transform & GetTransform () const
Public Member Functions inherited from Engine::RenderableObject
virtual ~RenderableObject ()=default
RenderObject & GetRenderObject ()
void SetRenderObject (std::unique_ptr< RenderObject > renderObject)
Sets the render object for this object.
Public Attributes
std::string name
std::vector< std::shared_ptr< SceneObject > > children
Protected Attributes
Transform m_Transform
std::shared_ptr< VertexArray > m_Mesh
std::shared_ptr< Material > m_Material
Protected Attributes inherited from Engine::RenderableObject
std::unique_ptr< RenderObject > m_RenderObject
Rendering data.
Detailed Description
Definition at line 11 of file SceneObject.h.
Constructor & Destructor Documentation
SceneObject()
Engine::SceneObject::SceneObject (const std::string & objectName = "Object") inline
Definition at line 13 of file SceneObject.h.
~SceneObject()
virtual Engine::SceneObject::~SceneObject () virtual default
Member Function Documentation
AddChild()
void Engine::SceneObject::AddChild (const std::shared_ptr< SceneObject > & child) inline
Definition at line 26 of file SceneObject.h.
References children.
GetMaterial()
const std::shared_ptr< Material > & Engine::SceneObject::GetMaterial () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 35 of file SceneObject.h.
References m_Material.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetMesh()
const std::shared_ptr< VertexArray > & Engine::SceneObject::GetMesh () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 34 of file SceneObject.h.
References m_Mesh.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetTransform() [1/2]
Transform & Engine::SceneObject::GetTransform () inline
Definition at line 37 of file SceneObject.h.
References m_Transform.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetTransform() [2/2]
const Transform & Engine::SceneObject::GetTransform () const inline
Definition at line 38 of file SceneObject.h.
References m_Transform.
GetWorldTransform()
glm::mat4 Engine::SceneObject::GetWorldTransform () const inline
Definition at line 29 of file SceneObject.h.
References Engine::Transform::GetModelMatrix(), and m_Transform.
OnRender()
void Engine::SceneObject::OnRender (Renderer & renderer) inline override virtual
Called when object should be rendered.
Parameters
renderer Reference to the renderer
Reimplemented from Engine::RenderableObject.
Definition at line 16 of file SceneObject.h.
References children, Engine::Transform::GetModelMatrix(), m_Material, m_Mesh, m_Transform, and Engine::Renderer::Submit().
SetMaterial()
void Engine::SceneObject::SetMaterial (const std::shared_ptr< Material > & material) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 32 of file SceneObject.h.
References m_Material.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SetMesh()
void Engine::SceneObject::SetMesh (const std::shared_ptr< VertexArray > & mesh) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 31 of file SceneObject.h.
References m_Mesh.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Member Data Documentation
children
std::vector<std::shared_ptr<SceneObject> > Engine::SceneObject::children
Definition at line 41 of file SceneObject.h.
Referenced by AddChild(), and OnRender().
m_Material
std::shared_ptr<Material> Engine::SceneObject::m_Material protected
Definition at line 46 of file SceneObject.h.
Referenced by GetMaterial(), OnRender(), and SetMaterial().
m_Mesh
std::shared_ptr<VertexArray> Engine::SceneObject::m_Mesh protected
Definition at line 45 of file SceneObject.h.
Referenced by GetMesh(), OnRender(), and SetMesh().
m_Transform
Transform Engine::SceneObject::m_Transform protected
Definition at line 44 of file SceneObject.h.
Referenced by GetTransform(), GetTransform(), GetWorldTransform(), and OnRender().
name
std::string Engine::SceneObject::name
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 40 of file SceneObject.h.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
The documentation for this class was generated from the following file:
src/Scene/SceneObject.h