Voxel Engine: Engine::Shader Class Reference
Engine::Shader Class Reference
OpenGL shader program wrapper.
#include <Shader.h>
Public Member Functions
Shader ()=default
Shader (const char *vertexSrc, const char *fragmentSrc)
Creates a shader program from source code.
~Shader ()
void Bind () const
Activates this shader program.
void Unbind () const
Deactivates this shader program.
uint32_t GetProgram () const
void SetMat4 (const std::string &name, const glm::mat4 &matrix)
Sets a 4x4 matrix uniform.
void SetInt (const std::string &name, int value)
Sets an integer uniform.
void SetFloat (const std::string &name, float value)
Sets a float uniform.
void SetVector2 (const std::string &name, const glm::vec2 &value)
Sets a 2D vector uniform.
void SetVector3 (const std::string &name, const glm::vec3 &value)
Sets a 3D vector uniform.
void SetVector4 (const std::string &name, const glm::vec4 &value)
Sets a 4D vector uniform.
bool LoadFromSource (const char *vertexSrc, const char *fragmentSrc)
virtual bool Load (const std::string &path) override
Loads the resource from the specified path.
bool Reload (const std::string &path)
Reloads the shader from its source files.
void EnableHotReload (const std::string &vertPath, const std::string &fragPath)
Enables hot-reloading for this shader.
virtual void Unload () override
Unloads the resource from memory.
Public Member Functions inherited from Engine::Resource
Resource ()=default
virtual ~Resource ()=default
const std::string & GetPath () const
ResourceType GetType () const
bool IsLoaded () const
void AddRef ()
Increments the reference count.
void Release ()
Decrements the reference count and unloads if zero.
int GetRefCount () const
Static Public Member Functions
static std::shared_ptr< Shader > CreateFromFiles (const std::string &vertexPath, const std::string &fragmentPath)
Creates a shader from source files.
static std::shared_ptr< Shader > CreateFromSource (const char *vertexSrc, const char *fragmentSrc)
static std::string ReadFile (const std::string &filepath)
Reads a file into a string.
Private Member Functions
bool CompileShader (const char *source, uint32_t type, uint32_t &shader)
Compiles a shader.
Private Attributes
uint32_t m_Program = 0
OpenGL program ID.
Additional Inherited Members
Protected Attributes inherited from Engine::Resource
std::string m_Path
File path of the resource.
ResourceType m_Type
Type of the resource.
bool m_IsLoaded = false
Whether the resource is currently loaded.
int m_RefCount = 0
Reference count of the resource.
Detailed Description
OpenGL shader program wrapper.
Manages compilation, linking and uniform setting for shader programs.
Definition at line 18 of file Shader.h.
Constructor & Destructor Documentation
Shader() [1/2]
Engine::Shader::Shader () default
Shader() [2/2]
Engine::Shader::Shader (const char * vertexSrc, const char * fragmentSrc)
Creates a shader program from source code.
Parameters
vertexSrc Vertex shader source code
fragmentSrc Fragment shader source code
Definition at line 15 of file Shader.cpp.
References CompileShader(), and m_Program.
~Shader()
Engine::Shader::~Shader ()
Definition at line 43 of file Shader.cpp.
References m_Program.
Member Function Documentation
Bind()
void Engine::Shader::Bind () const
Activates this shader program.
Definition at line 47 of file Shader.cpp.
References m_Program.
CompileShader()
bool Engine::Shader::CompileShader (const char * source, uint32_t type, uint32_t & shader) private
Compiles a shader.
Parameters
source Shader source code
type Shader type (GL_VERTEX_SHADER or GL_FRAGMENT_SHADER)
[out] shader Compiled shader ID
Returns
true if compilation succeeded
Definition at line 55 of file Shader.cpp.
Referenced by LoadFromSource(), and Shader().
CreateFromFiles()
std::shared_ptr< Shader > Engine::Shader::CreateFromFiles (const std::string & vertexPath, const std::string & fragmentPath) static
Creates a shader from source files.
Parameters
vertexPath Path to vertex shader file
fragmentPath Path to fragment shader file
Returns
New shader instance or nullptr on failure
Definition at line 166 of file Shader.cpp.
References EnableHotReload(), Engine::AssetManager::Get(), and Engine::AssetManager::LoadResource().
Referenced by Engine::ShaderLibrary::Load().
CreateFromSource()
std::shared_ptr< Shader > Engine::Shader::CreateFromSource (const char * vertexSrc, const char * fragmentSrc) static
Definition at line 179 of file Shader.cpp.
Referenced by Engine::ShaderFactory::Build(), and Engine::ShaderLibrary::LoadFromSource().
EnableHotReload()
void Engine::Shader::EnableHotReload (const std::string & vertPath, const std::string & fragPath)
Enables hot-reloading for this shader.
Parameters
vertPath Path to vertex shader
fragPath Path to fragment shader
Definition at line 204 of file Shader.cpp.
References Engine::ShaderHotReload::Get(), and Engine::ShaderHotReload::WatchShader().
Referenced by CreateFromFiles().
GetProgram()
uint32_t Engine::Shader::GetProgram () const inline
Returns
OpenGL program ID
Definition at line 34 of file Shader.h.
References m_Program.
Load()
bool Engine::Shader::Load (const std::string & path) override virtual
Loads the resource from the specified path.
Parameters
path File path to the resource
Returns
true if loading was successful
Implements Engine::Resource.
Definition at line 146 of file Shader.cpp.
References LoadFromSource(), LOG_ERROR_CONCAT, and ReadFile().
Referenced by Reload().
LoadFromSource()
bool Engine::Shader::LoadFromSource (const char * vertexSrc, const char * fragmentSrc)
Definition at line 117 of file Shader.cpp.
References CompileShader(), Engine::Resource::m_IsLoaded, and m_Program.
Referenced by Load().
ReadFile()
std::string Engine::Shader::ReadFile (const std::string & filepath) static
Reads a file into a string.
Parameters
filepath Path to file to read
Returns
File contents as string
Definition at line 101 of file Shader.cpp.
References LOG_ERROR.
Referenced by Load().
Reload()
bool Engine::Shader::Reload (const std::string & path)
Reloads the shader from its source files.
Parameters
path Combined vertex;fragment path
Returns
true if reload successful
Definition at line 187 of file Shader.cpp.
References Load(), and m_Program.
SetFloat()
void Engine::Shader::SetFloat (const std::string & name, float value)
Sets a float uniform.
Parameters
name Uniform name in shader
value Float value to set
Definition at line 81 of file Shader.cpp.
References m_Program.
SetInt()
void Engine::Shader::SetInt (const std::string & name, int value)
Sets an integer uniform.
Parameters
name Uniform name in shader
value Integer value to set
Definition at line 76 of file Shader.cpp.
References m_Program.
SetMat4()
void Engine::Shader::SetMat4 (const std::string & name, const glm::mat4 & matrix)
Sets a 4x4 matrix uniform.
Parameters
name Uniform name in shader
matrix Matrix value to set
Definition at line 71 of file Shader.cpp.
References m_Program.
SetVector2()
void Engine::Shader::SetVector2 (const std::string & name, const glm::vec2 & value)
Sets a 2D vector uniform.
Parameters
name Uniform name in shader
value 2D vector value to set
Definition at line 86 of file Shader.cpp.
References m_Program.
SetVector3()
void Engine::Shader::SetVector3 (const std::string & name, const glm::vec3 & value)
Sets a 3D vector uniform.
Parameters
name Uniform name in shader
value 3D vector value to set
Definition at line 91 of file Shader.cpp.
References m_Program.
SetVector4()
void Engine::Shader::SetVector4 (const std::string & name, const glm::vec4 & value)
Sets a 4D vector uniform.
Parameters
name Uniform name in shader
value 4D vector value to set
Definition at line 96 of file Shader.cpp.
References m_Program.
Unbind()
void Engine::Shader::Unbind () const
Deactivates this shader program.
Definition at line 51 of file Shader.cpp.
Unload()
virtual void Engine::Shader::Unload () inline override virtual
Unloads the resource from memory.
Implements Engine::Resource.
Definition at line 110 of file Shader.h.
References Engine::Resource::m_IsLoaded, and m_Program.
Member Data Documentation
m_Program
uint32_t Engine::Shader::m_Program = 0 private
OpenGL program ID.
Definition at line 119 of file Shader.h.
Referenced by Bind(), GetProgram(), LoadFromSource(), Reload(), SetFloat(), SetInt(), SetMat4(), SetVector2(), SetVector3(), SetVector4(), Shader(), Unload(), and ~Shader().
The documentation for this class was generated from the following files:
src/Shader/Shader.h
src/Shader/Shader.cpp