Voxel Engine: Engine::Event Class Reference
Engine::Event Class Reference abstract
Base class for all event types.
#include <Event.h>
Public Member Functions
virtual ~Event ()=default
bool IsHandled () const
void SetHandled (bool handled)
virtual EventType GetEventType () const =0
virtual const char * GetName () const =0
virtual int GetCategoryFlags () const =0
virtual std::string ToString () const
virtual EventPriority GetPriority () const
virtual void SetPriority (EventPriority priority)
bool IsInCategory (EventCategory category) const
Checks if event belongs to a category.
uint64_t GetTimestamp () const
void SetTimestamp (uint64_t timestamp)
virtual std::string GetDebugInfo () const
virtual ~Event ()=default
virtual EventType GetEventType () const =0
virtual const char * GetName () const =0
virtual int GetCategoryFlags () const =0
virtual std::string ToString () const
bool IsInCategory (EventCategory category)
Checks if event belongs to a category.
Protected Member Functions
Event ()
Protected Attributes
bool m_Handled = false
Whether event has been handled.
EventPriority m_Priority = EventPriority::Normal
uint64_t m_Timestamp
Detailed Description
Base class for all event types.
Base class for all events in the system.
Provides common functionality for event handling, identification, and categorization. All specific event types derive from this class.
Definition at line 44 of file Event.h.
Constructor & Destructor Documentation
~Event() [1/2]
virtual Engine::Event::~Event () virtual default
Event()
Engine::Event::Event () inline protected
Definition at line 80 of file Event.h.
~Event() [2/2]
virtual Engine::Event::~Event () virtual default
Member Function Documentation
GetCategoryFlags() [1/2]
virtual int Engine::Event::GetCategoryFlags () const pure virtual
Returns
Bit flags of categories this event belongs to
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyEvent, Engine::MouseMovedEvent, Engine::MouseButtonEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
Referenced by IsInCategory().
GetCategoryFlags() [2/2]
virtual int Engine::Event::GetCategoryFlags () const pure virtual
Returns
Category flags for this event
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyEvent, Engine::MouseMovedEvent, Engine::MouseButtonEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
GetDebugInfo()
virtual std::string Engine::Event::GetDebugInfo () const inline virtual
Definition at line 77 of file Event.h.
References ToString().
GetEventType() [1/2]
virtual EventType Engine::Event::GetEventType () const pure virtual
Returns
Type identifier for this event
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyPressedEvent, Engine::KeyReleasedEvent, Engine::MouseMovedEvent, Engine::MouseButtonPressedEvent, Engine::MouseButtonReleasedEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
Referenced by Engine::EventDispatcher::Dispatch(), Engine::Application::InitWindow(), and Engine::InputSystem::OnEvent().
GetEventType() [2/2]
virtual EventType Engine::Event::GetEventType () const pure virtual
Returns
The type of this event
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyPressedEvent, Engine::KeyReleasedEvent, Engine::MouseMovedEvent, Engine::MouseButtonPressedEvent, Engine::MouseButtonReleasedEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
GetName() [1/2]
virtual const char * Engine::Event::GetName () const pure virtual
Returns
Human-readable name of the event
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyPressedEvent, Engine::KeyReleasedEvent, Engine::MouseMovedEvent, Engine::MouseButtonPressedEvent, Engine::MouseButtonReleasedEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
Referenced by ToString().
GetName() [2/2]
virtual const char * Engine::Event::GetName () const pure virtual
Returns
Human-readable name of the event
Implemented in Engine::WindowResizeEvent, Engine::WindowCloseEvent, Engine::KeyPressedEvent, Engine::KeyReleasedEvent, Engine::MouseMovedEvent, Engine::MouseButtonPressedEvent, Engine::MouseButtonReleasedEvent, Engine::MouseScrolledEvent, Engine::WindowResizeEvent, and Engine::WindowCloseEvent.
GetPriority()
virtual EventPriority Engine::Event::GetPriority () const inline virtual
Returns
Priority level of this event
Definition at line 62 of file Event.h.
References m_Priority.
GetTimestamp()
uint64_t Engine::Event::GetTimestamp () const inline
Definition at line 75 of file Event.h.
References m_Timestamp.
IsHandled()
bool Engine::Event::IsHandled () const inline
Returns
Whether the event has been handled
Definition at line 49 of file Event.h.
References m_Handled.
IsInCategory() [1/2]
bool Engine::Event::IsInCategory (EventCategory category)
Checks if event belongs to a category.
Parameters
category Category to check
Returns
true if event is in category
IsInCategory() [2/2]
bool Engine::Event::IsInCategory (EventCategory category) const inline
Checks if event belongs to a category.
Parameters
category Category to check against
Returns
true if event is in the category
Definition at line 71 of file Event.h.
References GetCategoryFlags().
SetHandled()
void Engine::Event::SetHandled (bool handled) inline
Parameters
handled New handled state
Definition at line 51 of file Event.h.
References m_Handled.
Referenced by Engine::EventDispatcher::Dispatch().
SetPriority()
virtual void Engine::Event::SetPriority (EventPriority priority) inline virtual
Parameters
priority New priority level
Definition at line 64 of file Event.h.
References m_Priority.
SetTimestamp()
void Engine::Event::SetTimestamp (uint64_t timestamp) inline
Definition at line 76 of file Event.h.
References m_Timestamp.
ToString() [1/2]
virtual std::string Engine::Event::ToString () const inline virtual
Returns
String representation of the event
Definition at line 60 of file Event.h.
References GetName().
Referenced by GetDebugInfo().
ToString() [2/2]
virtual std::string Engine::Event::ToString () const inline virtual
Returns
String representation of the event
Definition at line 54 of file Events.h.
References GetName().
Member Data Documentation
m_Handled
bool Engine::Event::m_Handled = false protected
Whether event has been handled.
Definition at line 83 of file Event.h.
Referenced by IsHandled(), and SetHandled().
m_Priority
EventPriority Engine::Event::m_Priority = EventPriority::Normal protected
Definition at line 84 of file Event.h.
Referenced by GetPriority(), and SetPriority().
m_Timestamp
uint64_t Engine::Event::m_Timestamp protected
Definition at line 85 of file Event.h.
Referenced by GetTimestamp(), and SetTimestamp().
The documentation for this class was generated from the following files:
src/Events/Event.h
src/Events/Events.h