Voxel Engine: Engine::FileSystem Class Reference
Engine::FileSystem Class Reference
#include <FileSystem.h>
Static Public Member Functions
static bool Exists (const std::string &filepath)
static bool CreateDirectory (const std::string &path)
static bool WriteFile (const std::string &filepath, const std::string &content)
Static Private Member Functions
static std::string SantizePath (const std::string &path)
Detailed Description
Definition at line 7 of file FileSystem.h.
Member Function Documentation
CreateDirectory()
static bool Engine::FileSystem::CreateDirectory (const std::string & path) inline static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 13 of file FileSystem.h.
References SantizePath().
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Exists()
static bool Engine::FileSystem::Exists (const std::string & filepath) inline static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 9 of file FileSystem.h.
References SantizePath().
Referenced by Engine::LuaScriptSystem::ExecuteFile(), and Engine::LuaScriptSystem::RegisterEngineAPI().
SantizePath()
static std::string Engine::FileSystem::SantizePath (const std::string & path) inline static private
Definition at line 40 of file FileSystem.h.
Referenced by CreateDirectory(), Exists(), and WriteFile().
WriteFile()
static bool Engine::FileSystem::WriteFile (const std::string & filepath, const std::string & content) inline static
Definition at line 17 of file FileSystem.h.
References LOG_ERROR, and SantizePath().
The documentation for this class was generated from the following file:
src/Core/FileSystem.h