Voxel Engine: Engine::IndexBuffer Class Reference
Engine::IndexBuffer Class Reference abstract
Abstract index buffer interface.
#include <Buffer.h>
Public Member Functions
virtual ~IndexBuffer ()=default
virtual void Bind () const =0
virtual void Unbind () const =0
virtual uint32_t GetCount () const =0
Static Public Member Functions
static IndexBuffer * Create (const uint32_t *indices, uint32_t count)
Creates an index buffer.
Detailed Description
Abstract index buffer interface.
Definition at line 141 of file Buffer.h.
Constructor & Destructor Documentation
~IndexBuffer()
virtual Engine::IndexBuffer::~IndexBuffer () virtual default
Member Function Documentation
Bind()
virtual void Engine::IndexBuffer::Bind () const pure virtual
Implemented in Engine::OpenGLIndexBuffer.
Create()
IndexBuffer * Engine::IndexBuffer::Create (const uint32_t * indices, uint32_t size) static
Creates an index buffer.
Parameters
indices Pointer to index data
size Size of index data in bytes
Returns
New index buffer instance
Definition at line 26 of file Buffer.cpp.
Referenced by Engine::TerrainSystem::GenerateMesh(), Engine::AssetManager::GetOrCreateCubeMesh(), and Engine::Renderer2D::Initialize().
GetCount()
virtual uint32_t Engine::IndexBuffer::GetCount () const pure virtual
Implemented in Engine::OpenGLIndexBuffer.
Unbind()
virtual void Engine::IndexBuffer::Unbind () const pure virtual
Implemented in Engine::OpenGLIndexBuffer.
The documentation for this class was generated from the following files:
src/Renderer/Buffer.h
src/Renderer/Buffer.cpp