Voxel Engine: Engine::SceneManager Class Reference
Engine::SceneManager Class Reference
#include <SceneManager.h>
Public Member Functions
void AddScene (const std::shared_ptr< Scene > &scene)
void SetActiveScene (const std::string &name)
std::shared_ptr< Scene > GetActiveScene () const
std::shared_ptr< Scene > GetScene (const std::string &name) const
bool RemoveScene (const std::string &name)
void Update (float deltaTime)
void Render (Renderer &renderer)
Static Public Member Functions
static SceneManager & Get ()
Private Member Functions
SceneManager ()=default
Private Attributes
std::mutex sceneMutex
std::unordered_map< std::string, std::shared_ptr< Scene > > scenes
std::shared_ptr< Scene > activeScene
Detailed Description
Definition at line 8 of file SceneManager.h.
Constructor & Destructor Documentation
SceneManager()
Engine::SceneManager::SceneManager () private default
Member Function Documentation
AddScene()
void Engine::SceneManager::AddScene (const std::shared_ptr< Scene > & scene) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 15 of file SceneManager.h.
References sceneMutex, and scenes.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Get()
static SceneManager & Engine::SceneManager::Get () inline static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 10 of file SceneManager.h.
Referenced by Engine::Application::ConfigureForRenderType(), Engine::LuaScriptSystem::RegisterEngineAPI(), Engine::ImGuiOverlay::RenderTerrainControls(), and Engine::Application::Run().
GetActiveScene()
std::shared_ptr< Scene > Engine::SceneManager::GetActiveScene () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 34 of file SceneManager.h.
References activeScene, and sceneMutex.
Referenced by Engine::Application::ConfigureForRenderType(), Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::ImGuiOverlay::RenderTerrainControls().
GetScene()
std::shared_ptr< Scene > Engine::SceneManager::GetScene (const std::string & name) const inline
Definition at line 39 of file SceneManager.h.
References sceneMutex, and scenes.
RemoveScene()
bool Engine::SceneManager::RemoveScene (const std::string & name) inline
Definition at line 45 of file SceneManager.h.
References activeScene, LOG_ERROR_CONCAT, sceneMutex, and scenes.
Render()
void Engine::SceneManager::Render (Renderer & renderer) inline
Definition at line 64 of file SceneManager.h.
References activeScene, and sceneMutex.
SetActiveScene()
void Engine::SceneManager::SetActiveScene (const std::string & name) inline
Definition at line 20 of file SceneManager.h.
References activeScene, LOG_ERROR_CONCAT, LOG_TRACE_CONCAT, sceneMutex, and scenes.
Update()
void Engine::SceneManager::Update (float deltaTime) inline
Definition at line 57 of file SceneManager.h.
References activeScene, and sceneMutex.
Referenced by Engine::Application::Run().
Member Data Documentation
activeScene
std::shared_ptr<Scene> Engine::SceneManager::activeScene private
Definition at line 75 of file SceneManager.h.
Referenced by GetActiveScene(), RemoveScene(), Render(), SetActiveScene(), and Update().
sceneMutex
std::mutex Engine::SceneManager::sceneMutex mutable private
Definition at line 73 of file SceneManager.h.
Referenced by AddScene(), GetActiveScene(), GetScene(), RemoveScene(), Render(), SetActiveScene(), and Update().
scenes
std::unordered_map<std::string, std::shared_ptr<Scene> > Engine::SceneManager::scenes private
Definition at line 74 of file SceneManager.h.
Referenced by AddScene(), GetScene(), RemoveScene(), and SetActiveScene().
The documentation for this class was generated from the following file:
src/Scene/SceneManager.h