Voxel Engine: Engine::PerspectiveCamera Class Reference
Engine::PerspectiveCamera Class Reference
A perspective camera class for 3D rendering.
#include <PerspectiveCamera.h>
Public Member Functions
PerspectiveCamera (float fov=45.0f, float aspectRatio=16.0f/9.0f, float nearClip=0.1f, float farClip=100.0f)
Constructs a perspective camera.
void SetPosition (const glm::vec3 &position)
Sets the camera position.
const glm::vec3 & GetPosition () const
Gets the camera position.
void SetRotation (float pitch, float yaw)
Sets the camera rotation.
void MoveForward (float deltaTime)
Moves the camera forward based on current orientation.
void MoveBackward (float deltaTime)
Moves the camera backward based on current orientation.
void MoveLeft (float deltaTime)
Moves the camera left based on current orientation.
void MoveRight (float deltaTime)
Moves the camera right based on current orientation.
void MoveUp (float deltaTime)
Moves the camera up along world Y-axis.
void MoveDown (float deltaTime)
Moves the camera down along world Y-axis.
void RotateWithMouse (float xOffset, float yOffset, float sensitivity)
Rotates the camera based on mouse movement.
const glm::mat4 & GetViewMatrix () const
const glm::mat4 & GetProjectionMatrix () const
const glm::mat4 & GetViewProjectionMatrix () const
const glm::vec3 & GetFront () const
Private Member Functions
void RecalculateViewMatrix ()
Recalculates view matrix after position/rotation changes.
Private Attributes
glm::mat4 m_ViewMatrix = glm::mat4(1.0f)
glm::mat4 m_ProjectionMatrix
glm::mat4 m_ViewProjectionMatrix
glm::vec3 m_Position = glm::vec3(0.0f)
glm::vec3 m_Front = glm::vec3(0.0f, 0.0f, -1.0f)
glm::vec3 m_Up = glm::vec3(0.0f, 1.0f, 0.0f)
glm::vec3 m_Right = glm::vec3(1.0f, 0.0f, 0.0f)
float m_Pitch = 0.0f
float m_Yaw = -90.0f
float m_MovementSpeed = 2.5f
Detailed Description
A perspective camera class for 3D rendering.
Implements a perspective camera with position, rotation and movement controls. Handles view and projection matrix calculations for 3D scene rendering.
Definition at line 12 of file PerspectiveCamera.h.
Constructor & Destructor Documentation
PerspectiveCamera()
Engine::PerspectiveCamera::PerspectiveCamera (float fov = 45.0f, float aspectRatio = 16.0f/9.0f, float nearClip = 0.1f, float farClip = 100.0f)
Constructs a perspective camera.
Parameters
fov Field of view in degrees
aspectRatio Aspect ratio of the viewport (width/height)
nearClip Distance to near clipping plane
farClip Distance to far clipping plane
Definition at line 9 of file PerspectiveCamera.cpp.
References m_ProjectionMatrix, and RecalculateViewMatrix().
Member Function Documentation
GetFront()
const glm::vec3 & Engine::PerspectiveCamera::GetFront () const inline
Returns
The camera's front vector
Definition at line 70 of file PerspectiveCamera.h.
References m_Front.
GetPosition()
const glm::vec3 & Engine::PerspectiveCamera::GetPosition () const inline
Gets the camera position.
Returns
Current position vector
Definition at line 33 of file PerspectiveCamera.h.
References m_Position.
GetProjectionMatrix()
const glm::mat4 & Engine::PerspectiveCamera::GetProjectionMatrix () const inline
Returns
The current projection matrix
Definition at line 66 of file PerspectiveCamera.h.
References m_ProjectionMatrix.
GetViewMatrix()
const glm::mat4 & Engine::PerspectiveCamera::GetViewMatrix () const inline
Returns
The current view matrix
Definition at line 64 of file PerspectiveCamera.h.
References m_ViewMatrix.
GetViewProjectionMatrix()
const glm::mat4 & Engine::PerspectiveCamera::GetViewProjectionMatrix () const inline
Returns
The combined view-projection matrix
Definition at line 68 of file PerspectiveCamera.h.
References m_ViewProjectionMatrix.
MoveBackward()
void Engine::PerspectiveCamera::MoveBackward (float deltaTime)
Moves the camera backward based on current orientation.
Definition at line 33 of file PerspectiveCamera.cpp.
References m_Front, m_MovementSpeed, m_Position, and RecalculateViewMatrix().
MoveDown()
void Engine::PerspectiveCamera::MoveDown (float deltaTime)
Moves the camera down along world Y-axis.
Definition at line 53 of file PerspectiveCamera.cpp.
References m_MovementSpeed, m_Position, m_Up, and RecalculateViewMatrix().
MoveForward()
void Engine::PerspectiveCamera::MoveForward (float deltaTime)
Moves the camera forward based on current orientation.
Definition at line 28 of file PerspectiveCamera.cpp.
References m_Front, m_MovementSpeed, m_Position, and RecalculateViewMatrix().
MoveLeft()
void Engine::PerspectiveCamera::MoveLeft (float deltaTime)
Moves the camera left based on current orientation.
Definition at line 38 of file PerspectiveCamera.cpp.
References m_MovementSpeed, m_Position, m_Right, and RecalculateViewMatrix().
MoveRight()
void Engine::PerspectiveCamera::MoveRight (float deltaTime)
Moves the camera right based on current orientation.
Definition at line 43 of file PerspectiveCamera.cpp.
References m_MovementSpeed, m_Position, m_Right, and RecalculateViewMatrix().
MoveUp()
void Engine::PerspectiveCamera::MoveUp (float deltaTime)
Moves the camera up along world Y-axis.
Definition at line 48 of file PerspectiveCamera.cpp.
References m_MovementSpeed, m_Position, m_Up, and RecalculateViewMatrix().
RecalculateViewMatrix()
void Engine::PerspectiveCamera::RecalculateViewMatrix () private
Recalculates view matrix after position/rotation changes.
Definition at line 14 of file PerspectiveCamera.cpp.
References m_Front, m_Pitch, m_Position, m_ProjectionMatrix, m_Right, m_Up, m_ViewMatrix, m_ViewProjectionMatrix, and m_Yaw.
Referenced by MoveBackward(), MoveDown(), MoveForward(), MoveLeft(), MoveRight(), MoveUp(), PerspectiveCamera(), RotateWithMouse(), SetPosition(), and SetRotation().
RotateWithMouse()
void Engine::PerspectiveCamera::RotateWithMouse (float xOffset, float yOffset, float sensitivity)
Rotates the camera based on mouse movement.
Parameters
xOffset Mouse X movement delta
yOffset Mouse Y movement delta
sensitivity Mouse movement sensitivity factor
Definition at line 58 of file PerspectiveCamera.cpp.
References m_Pitch, m_Yaw, and RecalculateViewMatrix().
SetPosition()
void Engine::PerspectiveCamera::SetPosition (const glm::vec3 & position) inline
Sets the camera position.
Parameters
position New position vector
Definition at line 27 of file PerspectiveCamera.h.
References m_Position, and RecalculateViewMatrix().
SetRotation()
void Engine::PerspectiveCamera::SetRotation (float pitch, float yaw) inline
Sets the camera rotation.
Parameters
pitch Rotation around X-axis in degrees
yaw Rotation around Y-axis in degrees
Definition at line 40 of file PerspectiveCamera.h.
References m_Pitch, m_Yaw, and RecalculateViewMatrix().
Member Data Documentation
m_Front
glm::vec3 Engine::PerspectiveCamera::m_Front = glm::vec3(0.0f, 0.0f, -1.0f) private
Definition at line 81 of file PerspectiveCamera.h.
Referenced by GetFront(), MoveBackward(), MoveForward(), and RecalculateViewMatrix().
m_MovementSpeed
float Engine::PerspectiveCamera::m_MovementSpeed = 2.5f private
Definition at line 87 of file PerspectiveCamera.h.
Referenced by MoveBackward(), MoveDown(), MoveForward(), MoveLeft(), MoveRight(), and MoveUp().
m_Pitch
float Engine::PerspectiveCamera::m_Pitch = 0.0f private
Definition at line 85 of file PerspectiveCamera.h.
Referenced by RecalculateViewMatrix(), RotateWithMouse(), and SetRotation().
m_Position
glm::vec3 Engine::PerspectiveCamera::m_Position = glm::vec3(0.0f) private
Definition at line 80 of file PerspectiveCamera.h.
Referenced by GetPosition(), MoveBackward(), MoveDown(), MoveForward(), MoveLeft(), MoveRight(), MoveUp(), RecalculateViewMatrix(), and SetPosition().
m_ProjectionMatrix
glm::mat4 Engine::PerspectiveCamera::m_ProjectionMatrix private
Definition at line 77 of file PerspectiveCamera.h.
Referenced by GetProjectionMatrix(), PerspectiveCamera(), and RecalculateViewMatrix().
m_Right
glm::vec3 Engine::PerspectiveCamera::m_Right = glm::vec3(1.0f, 0.0f, 0.0f) private
Definition at line 83 of file PerspectiveCamera.h.
Referenced by MoveLeft(), MoveRight(), and RecalculateViewMatrix().
m_Up
glm::vec3 Engine::PerspectiveCamera::m_Up = glm::vec3(0.0f, 1.0f, 0.0f) private
Definition at line 82 of file PerspectiveCamera.h.
Referenced by MoveDown(), MoveUp(), and RecalculateViewMatrix().
m_ViewMatrix
glm::mat4 Engine::PerspectiveCamera::m_ViewMatrix = glm::mat4(1.0f) private
Definition at line 76 of file PerspectiveCamera.h.
Referenced by GetViewMatrix(), and RecalculateViewMatrix().
m_ViewProjectionMatrix
glm::mat4 Engine::PerspectiveCamera::m_ViewProjectionMatrix private
Definition at line 78 of file PerspectiveCamera.h.
Referenced by GetViewProjectionMatrix(), and RecalculateViewMatrix().
m_Yaw
float Engine::PerspectiveCamera::m_Yaw = -90.0f private
Definition at line 86 of file PerspectiveCamera.h.
Referenced by RecalculateViewMatrix(), RotateWithMouse(), and SetRotation().
The documentation for this class was generated from the following files:
src/Camera/PerspectiveCamera.h
src/Camera/PerspectiveCamera.cpp