Voxel Engine: Engine::EventQueue Class Reference
Engine::EventQueue Class Reference
Thread-safe event queue for storing and processing events.
#include <EventDispatcher.h>
Public Types
using EventHandlerFn = std::function< bool(std::shared_ptr< Event >)>
Public Member Functions
void PushEvent (std::shared_ptr< Event > event)
Adds an event to the queue.
bool PopEvent (std::shared_ptr< Event > &event)
Removes and returns the next event.
void Clear ()
Empties the event queue.
bool HasEvents () const
void ProcessEvents (EventHandlerFn handler)
Processes all events in the queue.
Static Public Member Functions
static EventQueue & Get ()
Private Member Functions
EventQueue ()=default
uint64_t GetCurrentTimestamp ()
Private Attributes
std::mutex m_QueueMutex
std::priority_queue< std::shared_ptr< Event >, std::vector< std::shared_ptr< Event > >, EventCompare > m_EventQueue
Detailed Description
Thread-safe event queue for storing and processing events.
Implements a priority queue for events with thread-safe access
Definition at line 41 of file EventDispatcher.h.
Member Typedef Documentation
EventHandlerFn
using Engine::EventQueue::EventHandlerFn = std::function<bool(std::shared_ptr<Event>)>
Definition at line 43 of file EventDispatcher.h.
Constructor & Destructor Documentation
EventQueue()
Engine::EventQueue::EventQueue () private default
Member Function Documentation
Clear()
void Engine::EventQueue::Clear () inline
Empties the event queue.
Definition at line 80 of file EventDispatcher.h.
References m_EventQueue, and m_QueueMutex.
Get()
static EventQueue & Engine::EventQueue::Get () inline static
Returns
Reference to singleton instance
Definition at line 46 of file EventDispatcher.h.
Referenced by Engine::Application::InitWindow(), and Engine::Application::ProcessEvents().
GetCurrentTimestamp()
uint64_t Engine::EventQueue::GetCurrentTimestamp () inline private
Definition at line 109 of file EventDispatcher.h.
Referenced by PushEvent().
HasEvents()
bool Engine::EventQueue::HasEvents () const inline
Returns
true if queue contains events
Definition at line 89 of file EventDispatcher.h.
References m_EventQueue, and m_QueueMutex.
Referenced by ProcessEvents().
PopEvent()
bool Engine::EventQueue::PopEvent (std::shared_ptr< Event > & event) inline
Removes and returns the next event.
Parameters
[out] event Pointer to store the retrieved event
Returns
true if an event was retrieved
Definition at line 69 of file EventDispatcher.h.
References m_EventQueue, and m_QueueMutex.
Referenced by ProcessEvents().
ProcessEvents()
void Engine::EventQueue::ProcessEvents (EventHandlerFn handler) inline
Processes all events in the queue.
Parameters
handler Event handler function
Definition at line 98 of file EventDispatcher.h.
References HasEvents(), and PopEvent().
Referenced by Engine::Application::ProcessEvents().
PushEvent()
void Engine::EventQueue::PushEvent (std::shared_ptr< Event > event) inline
Adds an event to the queue.
Parameters
event Event to be queued
Definition at line 55 of file EventDispatcher.h.
References Engine::EventDebugger::Get(), GetCurrentTimestamp(), Engine::EventDebugger::LogEvent(), m_EventQueue, and m_QueueMutex.
Referenced by Engine::Application::InitWindow(), and Engine::Application::ProcessEvents().
Member Data Documentation
m_EventQueue
std::priority_queue<std::shared_ptr<Event>, std::vector<std::shared_ptr<Event> >, EventCompare> Engine::EventQueue::m_EventQueue private
Definition at line 118 of file EventDispatcher.h.
Referenced by Clear(), HasEvents(), PopEvent(), and PushEvent().
m_QueueMutex
std::mutex Engine::EventQueue::m_QueueMutex mutable private
Definition at line 115 of file EventDispatcher.h.
Referenced by Clear(), HasEvents(), PopEvent(), and PushEvent().
The documentation for this class was generated from the following file:
src/Events/EventDispatcher.h