Voxel Engine: Engine::OpenGLWindow Class Reference
Engine::OpenGLWindow Class Reference
OpenGL-specific window implementation.
#include <OpenGLWindow.h>
Classes
struct WindowData
Internal window data structure.
Public Member Functions
OpenGLWindow (const WindowProps &props)
Constructs OpenGL window.
virtual ~OpenGLWindow ()
Clean up window resources.
void OnUpdate () override
Update window events and swap buffers.
uint32_t GetWidth () const override
uint32_t GetHeight () const override
void SetVSync (bool enabled) override
Enable or disable vertical synchronization.
bool IsVSync () const override
Check if VSync is enabled.
void SetClear (float a, float b, float c, float d)
Set clear color and clear buffers.
void SetContext ()
Set up OpenGL context and enable necessary features.
void CreateVBO ()
Create Vertex Buffer Object.
virtual void * GetNativeWindow () const override
void SetEventCallback (const EventCallbackFn &callback) override
Sets event callback function.
Public Member Functions inherited from Engine::Window
virtual ~Window ()=default
Private Member Functions
virtual void Init (const WindowProps &props)
Initializes GLFW window and OpenGL context.
virtual void Shutdown ()
Cleans up window resources.
Private Attributes
GLFWwindow * m_Window
GLFW window handle.
WindowData m_Data
Window data.
Additional Inherited Members
Static Public Member Functions inherited from Engine::Window
static Window * Create (const WindowProps &props=WindowProps())
Creates platform-specific window.
Detailed Description
OpenGL-specific window implementation.
Provides GLFW-based window implementation with OpenGL context
Definition at line 12 of file OpenGLWindow.h.
Constructor & Destructor Documentation
OpenGLWindow()
Engine::OpenGLWindow::OpenGLWindow (const WindowProps & props)
Constructs OpenGL window.
OpenGL-specific window implementation.
Parameters
props Window properties
Handles window creation, event callbacks, and OpenGL context management
Definition at line 24 of file OpenGLWindow.cpp.
References Init().
~OpenGLWindow()
Engine::OpenGLWindow::~OpenGLWindow () virtual
Clean up window resources.
Destroys GLFW window and terminates GLFW
Definition at line 32 of file OpenGLWindow.cpp.
References Shutdown().
Member Function Documentation
CreateVBO()
void Engine::OpenGLWindow::CreateVBO () virtual
Create Vertex Buffer Object.
Note
Currently empty implementation
Implements Engine::Window.
Definition at line 239 of file OpenGLWindow.cpp.
GetHeight()
uint32_t Engine::OpenGLWindow::GetHeight () const inline override virtual
Returns
Window height
Implements Engine::Window.
Definition at line 24 of file OpenGLWindow.h.
References Engine::OpenGLWindow::WindowData::Height, and m_Data.
GetNativeWindow()
virtual void * Engine::OpenGLWindow::GetNativeWindow () const inline override virtual
Returns
Native window handle
Implements Engine::Window.
Definition at line 34 of file OpenGLWindow.h.
References m_Window.
GetWidth()
uint32_t Engine::OpenGLWindow::GetWidth () const inline override virtual
Returns
Window width
Implements Engine::Window.
Definition at line 23 of file OpenGLWindow.h.
References m_Data, and Engine::OpenGLWindow::WindowData::Width.
Init()
void Engine::OpenGLWindow::Init (const WindowProps & props) private virtual
Initializes GLFW window and OpenGL context.
Initialize the OpenGL window with specified properties.
Parameters
props Window properties
props Window configuration parameters including title, width, and height
Performs comprehensive window initialization:
Initializes GLFW library
Configures OpenGL context version and profile
Creates GLFW window
Sets up window context
Registers multiple input callbacks for window events, keyboard, mouse, and scroll interactions
Note
Terminates GLFW and logs an error if window creation fails
Enables vertical synchronization by default after initialization
Exceptions
None Handles initialization errors internally
Definition at line 53 of file OpenGLWindow.cpp.
References Engine::OpenGLWindow::WindowData::EventCallback, Engine::OpenGLWindow::WindowData::Height, Engine::WindowProps::Height, LOG_ERROR, m_Data, m_Window, SetVSync(), Engine::OpenGLWindow::WindowData::Title, Engine::WindowProps::Title, Engine::OpenGLWindow::WindowData::Width, and Engine::WindowProps::Width.
Referenced by OpenGLWindow().
IsVSync()
bool Engine::OpenGLWindow::IsVSync () const override virtual
Check if VSync is enabled.
Returns
True if VSync is enabled, false otherwise
Implements Engine::Window.
Definition at line 200 of file OpenGLWindow.cpp.
References m_Data, and Engine::OpenGLWindow::WindowData::VSync.
OnUpdate()
void Engine::OpenGLWindow::OnUpdate () override virtual
Update window events and swap buffers.
Implements Engine::Window.
Definition at line 182 of file OpenGLWindow.cpp.
References m_Window.
SetClear()
void Engine::OpenGLWindow::SetClear (float a, float b, float c, float d) virtual
Set clear color and clear buffers.
Parameters
a Red component (0-1)
b Green component (0-1)
c Blue component (0-1)
d Alpha component (0-1)
Implements Engine::Window.
Definition at line 211 of file OpenGLWindow.cpp.
SetContext()
void Engine::OpenGLWindow::SetContext () virtual
Set up OpenGL context and enable necessary features.
Enables depth testing, blending, and face culling
Implements Engine::Window.
Definition at line 220 of file OpenGLWindow.cpp.
References m_Window.
SetEventCallback()
void Engine::OpenGLWindow::SetEventCallback (const EventCallbackFn & callback) inline override virtual
Sets event callback function.
Implements Engine::Window.
Definition at line 35 of file OpenGLWindow.h.
References Engine::OpenGLWindow::WindowData::EventCallback, and m_Data.
SetVSync()
void Engine::OpenGLWindow::SetVSync (bool enabled) override virtual
Enable or disable vertical synchronization.
Parameters
enabled True to enable VSync, false to disable
Implements Engine::Window.
Definition at line 191 of file OpenGLWindow.cpp.
References m_Data, and Engine::OpenGLWindow::WindowData::VSync.
Referenced by Init().
Shutdown()
void Engine::OpenGLWindow::Shutdown () private virtual
Cleans up window resources.
Clean up window resources.
Destroys GLFW window and terminates GLFW
Definition at line 171 of file OpenGLWindow.cpp.
References m_Window.
Referenced by ~OpenGLWindow().
Member Data Documentation
m_Data
WindowData Engine::OpenGLWindow::m_Data private
Window data.
Definition at line 61 of file OpenGLWindow.h.
Referenced by GetHeight(), GetWidth(), Init(), IsVSync(), SetEventCallback(), and SetVSync().
m_Window
GLFWwindow* Engine::OpenGLWindow::m_Window private
GLFW window handle.
Definition at line 47 of file OpenGLWindow.h.
Referenced by GetNativeWindow(), Init(), OnUpdate(), SetContext(), and Shutdown().
The documentation for this class was generated from the following files:
src/Window/OpenGLWindow.h
src/Window/OpenGLWindow.cpp