Voxel Engine: Engine::ProfilerTimer Class Reference
Engine::ProfilerTimer Class Reference
RAII-style timer for profiling code blocks.
#include <Profiler.h>
Public Member Functions
ProfilerTimer (std::string_view name)
Constructs a timer for performance profiling.
~ProfilerTimer ()
Private Attributes
const std::string_view m_Name
std::chrono::time_point< std::chrono::steady_clock > m_StartTimepoint
Detailed Description
RAII-style timer for profiling code blocks.
Automatically measures duration between construction and destruction and reports the timing to the Profiler singleton.
Definition at line 15 of file Profiler.h.
Constructor & Destructor Documentation
ProfilerTimer()
Engine::ProfilerTimer::ProfilerTimer (std::string_view name) explicit
Constructs a timer for performance profiling.
Initializes a profiler timer with the given name and records the current time point as the start of the measurement. When the timer goes out of scope, it will automatically log the elapsed time using the Profiler singleton.
Parameters
name A string view representing the name of the profiled code segment.
Note
The timer uses std::chrono::steady_clock for precise time measurement.
Definition at line 32 of file Profiler.cpp.
~ProfilerTimer()
Engine::ProfilerTimer::~ProfilerTimer ()
Definition at line 35 of file Profiler.cpp.
References Engine::Profiler::Get(), Engine::Profiler::IsHighPrecision(), m_Name, m_StartTimepoint, and Engine::Profiler::WriteProfile().
Member Data Documentation
m_Name
const std::string_view Engine::ProfilerTimer::m_Name private
Definition at line 20 of file Profiler.h.
Referenced by ~ProfilerTimer().
m_StartTimepoint
std::chrono::time_point<std::chrono::steady_clock> Engine::ProfilerTimer::m_StartTimepoint private
Definition at line 21 of file Profiler.h.
Referenced by ~ProfilerTimer().
The documentation for this class was generated from the following files:
src/Debug/Profiler.h
src/Debug/Profiler.cpp