Voxel Engine: ValueNoise Class Reference
ValueNoise Class Reference
#include <ValueNoise.h>
Public Member Functions
ValueNoise (unsigned int seed=1234)
~ValueNoise () override=default
float noise (float x, float y) const override
Generate 2D noise value at given coordinates.
std::vector< float > generateHeightmap (int width, int height, float scale=1.0f) const override
Generate a heightmap using multiple octaves of noise.
Public Member Functions inherited from INoiseGenerator
virtual ~INoiseGenerator ()=default
Private Member Functions
float interpolate (float a0, float a1, float w) const
float rand2D (int x, int y) const
Private Attributes
unsigned int m_Seed
std::vector< int > p
Static Private Attributes
static const int PERMUTATION_SIZE = 256
Detailed Description
Definition at line 6 of file ValueNoise.h.
Constructor & Destructor Documentation
ValueNoise()
ValueNoise::ValueNoise (unsigned int seed = 1234) explicit
Definition at line 4 of file ValueNoise.cpp.
References p, and PERMUTATION_SIZE.
~ValueNoise()
ValueNoise::~ValueNoise () override default
Member Function Documentation
generateHeightmap()
std::vector< float > ValueNoise::generateHeightmap (int width, int height, float scale = 1.0f) const override virtual
Generate a heightmap using multiple octaves of noise.
Parameters
width Width of the heightmap
height Height of the heightmap
scale Scale factor for noise coordinates
Returns
std::vector<float> Generated heightmap values
Implements INoiseGenerator.
Definition at line 47 of file ValueNoise.cpp.
References noise().
interpolate()
float ValueNoise::interpolate (float a0, float a1, float w) const private
Definition at line 15 of file ValueNoise.cpp.
Referenced by noise().
noise()
float ValueNoise::noise (float x, float y) const override virtual
Generate 2D noise value at given coordinates.
Parameters
x X coordinate
y Y coordinate
Returns
float Noise value between 0 and 1
Implements INoiseGenerator.
Definition at line 27 of file ValueNoise.cpp.
References interpolate(), and rand2D().
Referenced by generateHeightmap().
rand2D()
float ValueNoise::rand2D (int x, int y) const private
Definition at line 20 of file ValueNoise.cpp.
References m_Seed.
Referenced by noise().
Member Data Documentation
m_Seed
unsigned int ValueNoise::m_Seed private
Definition at line 18 of file ValueNoise.h.
Referenced by rand2D().
p
std::vector<int> ValueNoise::p private
Definition at line 20 of file ValueNoise.h.
Referenced by ValueNoise().
PERMUTATION_SIZE
const int ValueNoise::PERMUTATION_SIZE = 256 static private
Definition at line 19 of file ValueNoise.h.
Referenced by ValueNoise().
The documentation for this class was generated from the following files:
src/Noise/ValueNoise/ValueNoise.h
src/Noise/ValueNoise/ValueNoise.cpp