Voxel Engine: Engine::VertexBuffer Class Reference
Engine::VertexBuffer Class Reference abstract
Abstract vertex buffer interface.
#include <Buffer.h>
Public Member Functions
virtual ~VertexBuffer ()=default
virtual void Bind () const =0
virtual void Unbind () const =0
virtual void SetLayout (const BufferLayout &layout)=0
virtual const BufferLayout & GetLayout () const =0
Static Public Member Functions
static VertexBuffer * Create (const float *vertices, uint32_t size)
Creates a vertex buffer.
Detailed Description
Abstract vertex buffer interface.
Definition at line 125 of file Buffer.h.
Constructor & Destructor Documentation
~VertexBuffer()
virtual Engine::VertexBuffer::~VertexBuffer () virtual default
Member Function Documentation
Bind()
virtual void Engine::VertexBuffer::Bind () const pure virtual
Implemented in Engine::OpenGLVertexBuffer.
Create()
VertexBuffer * Engine::VertexBuffer::Create (const float * vertices, uint32_t size) static
Creates a vertex buffer.
Parameters
vertices Pointer to vertex data
size Size of vertex data in bytes
Returns
New vertex buffer instance
Definition at line 15 of file Buffer.cpp.
Referenced by Engine::TerrainSystem::GenerateMesh(), Engine::AssetManager::GetOrCreateCubeMesh(), and Engine::Renderer2D::Initialize().
GetLayout()
virtual const BufferLayout & Engine::VertexBuffer::GetLayout () const pure virtual
Implemented in Engine::OpenGLVertexBuffer.
SetLayout()
virtual void Engine::VertexBuffer::SetLayout (const BufferLayout & layout) pure virtual
Implemented in Engine::OpenGLVertexBuffer.
Unbind()
virtual void Engine::VertexBuffer::Unbind () const pure virtual
Implemented in Engine::OpenGLVertexBuffer.
The documentation for this class was generated from the following files:
src/Renderer/Buffer.h
src/Renderer/Buffer.cpp