Voxel Engine: Engine::Profiler Class Reference
Engine::Profiler Class Reference
Singleton class for managing performance profiling.
#include <Profiler.h>
Classes
struct BatchEntry
struct FastPathCache
struct FrameData
struct ProfileData
class ProfileDataPool
struct ProfileName
struct ProfileNameHash
class SmallVector
struct ThreadLocalBuffer
Public Types
enum class OutputFormat { Console , JSON }
Public Member Functions
void BeginSession (const std::string &name="Profile")
Starts a new profiling session.
void EndSession ()
Ends current session and outputs results.
void WriteProfile (std::string_view name, float duration)
Records a timing measurement.
bool IsEnabled () const
void SetEnabled (bool enabled)
Enables or disables profiling.
void SetOutputFormat (OutputFormat format)
Sets the output format for profiling results.
void SetJSONOutputPath (const std::string &filepath)
Sets the JSON output filepath.
std::unordered_map< std::string, std::vector< float > > GetProfiles () const
void ClearProfiles ()
Clears all collected profile data.
void Cleanup ()
Cleanup and save results - called during shutdown.
void SetMaxSamples (size_t count)
Set maximum number of samples to keep per profile (0 for unlimited)
void SetPrecision (int precision)
Set decimal precision for timing measurements.
void SetBatchSize (size_t size)
Set batch size for JSON writes (0 for immediate write)
void SetHighPrecision (bool enabled)
Set high precision timing mode.
bool IsHighPrecision () const
void ProfileFrames (uint32_t frameCount)
Starts profiling for a specific number of frames.
bool EndFrame ()
Marks the end of a frame, used for frame profiling.
bool IsProfilingFrames () const
uint32_t GetCurrentProfiledFrame () const
bool IsInitialized () const
Check if profiler is properly initialized.
Static Public Member Functions
static Profiler & Get ()
static void InitSignalHandlers ()
Initialize signal handlers - call once at program start.
Static Public Attributes
static constexpr uint32_t MAX_PROFILE_FRAMES = 1000
Private Types
using ProfileMap = std::unordered_map< ProfileName, ProfileData *, ProfileNameHash >
Private Member Functions
Profiler ()
Default constructor for the Profiler class.
void WriteCompleteJSON () const
Writes complete profiling data to a JSON file.
void PreserveProfilingState ()
void RestoreProfilingState ()
~Profiler ()
std::string_view InternString (std::string_view str)
void FlushBatch ()
Processes and flushes batched performance measurements.
void ReserveBatch ()
void WriteFrameDataJSON () const
Writes frame profiling data to a JSON file.
Static Private Member Functions
static void SignalHandler (int signal)
Private Attributes
ProfileDataPool m_DataPool
ProfileMap m_Profiles
ProfileMap m_RegularProfiles
bool m_Enabled {true}
std::unordered_set< std::string > m_StringPool
OutputFormat m_OutputFormat {OutputFormat::JSON}
std::string m_JSONOutputPath {"profile_results.json"}
bool m_HasUnsavedData {false}
size_t m_MaxSamples {500}
int m_Precision {4}
std::shared_mutex m_Mutex
size_t m_BatchSize = 0
bool m_HighPrecision = false
std::string m_CurrentSession
std::string m_RegularSession
std::chrono::steady_clock::time_point m_LastWriteTime {std::chrono::steady_clock::now()}
bool m_ProfilingFrames {false}
uint32_t m_FramesToProfile {0}
uint32_t m_CurrentProfiledFrame {0}
std::vector< FrameData > m_FrameData
std::string m_FramesJSONPath {"profiler_n_frames.json"}
Static Private Attributes
static constexpr size_t INITIAL_VECTOR_CAPACITY = 1000
static constexpr size_t INITIAL_POOL_CAPACITY = 1000
static constexpr size_t BATCH_RESERVE_SIZE = 128
static constexpr size_t SMALL_STRING_SIZE = 64
static constexpr size_t SMALL_VECTOR_SIZE = 16
static constexpr size_t MEMORY_POOL_SIZE = 256
static constexpr size_t STRING_BUFFER_SIZE = 1024
static constexpr size_t FAST_PATH_SIZE = 32
static bool s_SignalsInitialized = false
static thread_local std::vector< BatchEntry > m_BatchedMeasurements
static thread_local ThreadLocalBuffer t_StringBuffer
static thread_local FastPathCache t_FastPath
static constexpr std::chrono::seconds WRITE_INTERVAL {5}
Detailed Description
Singleton class for managing performance profiling.
Collects and manages timing data for profiled code blocks. Provides statistical analysis of collected timing data.
Definition at line 30 of file Profiler.h.
Member Typedef Documentation
ProfileMap
using Engine::Profiler::ProfileMap = std::unordered_map<ProfileName, ProfileData*, ProfileNameHash> private
Definition at line 414 of file Profiler.h.
Member Enumeration Documentation
OutputFormat
enum class Engine::Profiler::OutputFormat strong
Enumerator
Console
JSON
Definition at line 32 of file Profiler.h.
Constructor & Destructor Documentation
Profiler()
Engine::Profiler::Profiler () private
Default constructor for the Profiler class.
Initializes a Profiler instance with default settings:
Profiling is disabled by default
Output format is set to console
Default JSON output path is set to "profile_results.json"
No unsaved profiling data initially
Note
This constructor sets up the initial state of the profiler without starting a profiling session. Use BeginSession() to activate profiling and start collecting performance data.
Definition at line 67 of file Profiler.cpp.
~Profiler()
Engine::Profiler::~Profiler () inline private
Definition at line 420 of file Profiler.h.
References Engine::Profiler::ProfileDataPool::deallocate(), m_DataPool, and m_Profiles.
Member Function Documentation
BeginSession()
void Engine::Profiler::BeginSession (const std::string & name = "Profile")
Starts a new profiling session.
Begins a new profiling session and initializes the JSON output file.
Parameters
name Name of the profiling session
This method starts a new profiling session by:
Setting the current session name
Marking unsaved data flag
Creating a JSON structure with session metadata
Attempting to write the initial JSON structure to the output file
Parameters
name The name of the profiling session to be started
Note
Thread-safe method using a mutex lock
Logs an error if file initialization fails
Logs an informational message when the session starts
Exceptions
std::exception If file writing encounters an error
Definition at line 111 of file Profiler.cpp.
References LOG_ERROR_CONCAT, LOG_INFO_CONCAT, m_CurrentSession, m_HasUnsavedData, m_JSONOutputPath, and m_Mutex.
Referenced by Engine::Application::Application(), Engine::ImGuiOverlay::RenderProfiler(), RestoreProfilingState(), and Engine::Application::Run().
Cleanup()
void Engine::Profiler::Cleanup ()
Cleanup and save results - called during shutdown.
Definition at line 87 of file Profiler.cpp.
References m_HasUnsavedData, and WriteCompleteJSON().
Referenced by SignalHandler().
ClearProfiles()
void Engine::Profiler::ClearProfiles () inline
Clears all collected profile data.
Definition at line 89 of file Profiler.h.
References m_Profiles.
Referenced by Engine::ImGuiOverlay::RenderProfiler().
EndFrame()
bool Engine::Profiler::EndFrame ()
Marks the end of a frame, used for frame profiling.
Returns
true if still profiling frames, false if done
Definition at line 440 of file Profiler.cpp.
References LOG_INFO, m_CurrentProfiledFrame, m_FrameData, m_FramesToProfile, m_ProfilingFrames, RestoreProfilingState(), and WriteFrameDataJSON().
Referenced by Engine::Renderer::Draw().
EndSession()
void Engine::Profiler::EndSession ()
Ends current session and outputs results.
Ends the current profiling session and outputs statistical results.
Terminates the active profiling session and generates output based on the configured output format. If profiling is not enabled or frame profiling is active, the method returns without action.
Supports two output formats:
JSON: Writes complete profiling data to a JSON file using WriteCompleteJSON()
Console: Logs profile statistics for each tracked profile, including average, minimum, maximum times, and total number of calls
Note
Skips profiles with no recorded data
Requires profiling to be enabled via BeginSession()
Precondition
Profiling session must be active
Postcondition
Profiling session is terminated and results are output
Definition at line 153 of file Profiler.cpp.
References Console, JSON, LOG_INFO_CONCAT, m_CurrentSession, m_Enabled, m_OutputFormat, m_Profiles, m_ProfilingFrames, and WriteCompleteJSON().
FlushBatch()
void Engine::Profiler::FlushBatch () private
Processes and flushes batched performance measurements.
This method handles the processing of accumulated performance measurements. It performs the following tasks:
Checks if there are any batched measurements to process
Acquires a lock to ensure thread-safe access to shared data structures
Adds each batched measurement to its corresponding profile
Clears the batch of measurements
Marks the presence of unsaved profiling data
If the output format is JSON, writes the complete profiling data and clears the unsaved data flag
Note
Thread-safe method using a unique lock to protect shared resources
No-op if no batched measurements exist
Automatically triggers JSON output if JSON format is selected
Definition at line 410 of file Profiler.cpp.
References JSON, m_BatchedMeasurements, m_HasUnsavedData, m_Mutex, m_OutputFormat, m_Profiles, and WriteCompleteJSON().
Get()
Profiler & Engine::Profiler::Get () static
Returns
Reference to the singleton Profiler instance
Definition at line 48 of file Profiler.cpp.
Referenced by Engine::Application::Application(), Engine::Renderer::Draw(), Engine::ImGuiOverlay::RenderProfiler(), Engine::Application::Run(), SignalHandler(), and Engine::ProfilerTimer::~ProfilerTimer().
GetCurrentProfiledFrame()
uint32_t Engine::Profiler::GetCurrentProfiledFrame () const inline
Returns
Current frame being profiled
Definition at line 131 of file Profiler.h.
References m_CurrentProfiledFrame.
GetProfiles()
std::unordered_map< std::string, std::vector< float > > Engine::Profiler::GetProfiles () const inline
Returns
Map of all profile names to their timing measurements
Definition at line 80 of file Profiler.h.
References m_Profiles.
Referenced by Engine::ImGuiOverlay::RenderProfiler().
InitSignalHandlers()
void Engine::Profiler::InitSignalHandlers () static
Initialize signal handlers - call once at program start.
Note
This is separate from construction to avoid performance impact
Definition at line 73 of file Profiler.cpp.
References s_SignalsInitialized, and SignalHandler().
InternString()
std::string_view Engine::Profiler::InternString (std::string_view str) private
Definition at line 427 of file Profiler.cpp.
References m_Mutex, and m_StringPool.
IsEnabled()
bool Engine::Profiler::IsEnabled () const inline
Returns
Whether profiling is currently enabled
Definition at line 59 of file Profiler.h.
References m_Enabled.
Referenced by Engine::ImGuiOverlay::RenderProfiler().
IsHighPrecision()
bool Engine::Profiler::IsHighPrecision () const inline
Returns
Whether high precision timing is enabled
Definition at line 113 of file Profiler.h.
References m_HighPrecision.
Referenced by Engine::ProfilerTimer::~ProfilerTimer().
IsInitialized()
bool Engine::Profiler::IsInitialized () const inline
Check if profiler is properly initialized.
Definition at line 134 of file Profiler.h.
References m_CurrentSession, and m_Enabled.
IsProfilingFrames()
bool Engine::Profiler::IsProfilingFrames () const inline
Returns
Whether currently profiling frames
Definition at line 128 of file Profiler.h.
References m_ProfilingFrames.
PreserveProfilingState()
void Engine::Profiler::PreserveProfilingState () private
Definition at line 466 of file Profiler.cpp.
References Engine::Profiler::ProfileDataPool::allocate(), m_CurrentSession, m_DataPool, m_Profiles, m_RegularProfiles, and m_RegularSession.
Referenced by ProfileFrames().
ProfileFrames()
void Engine::Profiler::ProfileFrames (uint32_t frameCount)
Starts profiling for a specific number of frames.
Parameters
frameCount Number of frames to profile (capped at MAX_PROFILE_FRAMES)
Definition at line 528 of file Profiler.cpp.
References LOG_INFO_CONCAT, m_CurrentProfiledFrame, m_CurrentSession, m_FrameData, m_FramesToProfile, m_ProfilingFrames, MAX_PROFILE_FRAMES, and PreserveProfilingState().
Referenced by Engine::ImGuiOverlay::RenderProfiler().
ReserveBatch()
void Engine::Profiler::ReserveBatch () inline private
Definition at line 451 of file Profiler.h.
References BATCH_RESERVE_SIZE, and m_BatchedMeasurements.
RestoreProfilingState()
void Engine::Profiler::RestoreProfilingState () private
Definition at line 478 of file Profiler.cpp.
References Engine::Profiler::ProfileDataPool::allocate(), BeginSession(), Engine::Profiler::ProfileDataPool::deallocate(), Engine::Profiler::FastPathCache::insert(), m_BatchedMeasurements, m_CurrentProfiledFrame, m_CurrentSession, m_DataPool, m_Enabled, m_FrameData, m_HasUnsavedData, m_LastWriteTime, m_Profiles, m_ProfilingFrames, m_RegularProfiles, m_RegularSession, t_FastPath, and WriteCompleteJSON().
Referenced by EndFrame().
SetBatchSize()
void Engine::Profiler::SetBatchSize (size_t size) inline
Set batch size for JSON writes (0 for immediate write)
Definition at line 107 of file Profiler.h.
References m_BatchSize.
SetEnabled()
void Engine::Profiler::SetEnabled (bool enabled) inline
Enables or disables profiling.
Parameters
enabled New enabled state
Definition at line 65 of file Profiler.h.
References m_Enabled.
Referenced by Engine::ImGuiOverlay::RenderProfiler().
SetHighPrecision()
void Engine::Profiler::SetHighPrecision (bool enabled) inline
Set high precision timing mode.
Definition at line 110 of file Profiler.h.
References m_HighPrecision.
SetJSONOutputPath()
void Engine::Profiler::SetJSONOutputPath (const std::string & filepath) inline
Sets the JSON output filepath.
Parameters
filepath Path where JSON file will be written
Definition at line 77 of file Profiler.h.
References m_JSONOutputPath.
SetMaxSamples()
void Engine::Profiler::SetMaxSamples (size_t count) inline
Set maximum number of samples to keep per profile (0 for unlimited)
Definition at line 101 of file Profiler.h.
References m_MaxSamples.
SetOutputFormat()
void Engine::Profiler::SetOutputFormat (OutputFormat format) inline
Sets the output format for profiling results.
Parameters
format The desired output format
Definition at line 71 of file Profiler.h.
References m_OutputFormat.
SetPrecision()
void Engine::Profiler::SetPrecision (int precision) inline
Set decimal precision for timing measurements.
Definition at line 104 of file Profiler.h.
References m_Precision.
SignalHandler()
void Engine::Profiler::SignalHandler (int signal) static private
Definition at line 81 of file Profiler.cpp.
References Cleanup(), Get(), and LOG_INFO_CONCAT.
Referenced by InitSignalHandlers().
WriteCompleteJSON()
void Engine::Profiler::WriteCompleteJSON () const private
Writes complete profiling data to a JSON file.
This method serializes profiling information collected during a session into a JSON format. It includes session metadata, individual profile statistics, and optional frame performance data.
The method performs the following key operations:
Checks if profiling is enabled
Creates a JSON structure with session details and timestamp
Aggregates profile data including call counts, timing statistics, and individual samples
Optionally includes frame performance data
Writes the complete JSON output to a file specified by m_JSONOutputPath
Note
Thread-safe method using shared locking mechanism
Skips profiles with zero calls or invalid data
Handles both local and dynamic sample storage
Exceptions
std::exception If file writing encounters an error
Precondition
Profiling must be enabled
Postcondition
JSON file is created/overwritten with complete profiling data
Definition at line 196 of file Profiler.cpp.
References LOG_ERROR_CONCAT, m_CurrentSession, m_Enabled, m_FrameData, m_JSONOutputPath, m_Mutex, m_Profiles, and m_ProfilingFrames.
Referenced by Cleanup(), EndSession(), FlushBatch(), RestoreProfilingState(), and WriteProfile().
WriteFrameDataJSON()
void Engine::Profiler::WriteFrameDataJSON () const private
Writes frame profiling data to a JSON file.
Generates a comprehensive JSON output containing frame-level performance metrics and statistical analysis of frame times during profiling. The output includes:
Session information
Total number of frames profiled
Timestamp of data generation
Detailed frame-by-frame timing data
Frame performance statistics
The method performs the following key operations:
Captures frame number, frame time, and timestamp for each recorded frame
Calculates frame time statistics including average, minimum, and maximum
Computes frame rate (FPS) metrics based on frame time calculations
Writes the generated JSON data to a file specified by m_FramesJSONPath
Note
Uses nlohmann::json for JSON serialization
Handles potential file writing exceptions with error logging
Skips statistics generation if no frame data is available
Exceptions
std::exception If file writing encounters an error
Definition at line 288 of file Profiler.cpp.
References LOG_ERROR_CONCAT, m_CurrentSession, m_FrameData, m_FramesJSONPath, and m_FramesToProfile.
Referenced by EndFrame().
WriteProfile()
void Engine::Profiler::WriteProfile (std::string_view name, float duration)
Records a timing measurement.
Records a performance profile sample with rate limiting and thread-safe data management.
Parameters
name Name of the profiled block
duration Duration in milliseconds
Adds a performance measurement sample to the profiler, ensuring thread safety, preventing excessive sampling, and periodically writing profiling data to JSON.
Parameters
name A string view representing the profile/function name being measured
duration The duration of the profile sample in floating-point seconds
Note
Samples are rate-limited to 60Hz to prevent performance overhead
Skips recording if profiling is disabled or profile name is empty
Writes complete JSON profile data every 500 milliseconds during profiling
@thread_safety Thread-safe with shared and unique locks for concurrent access
Definition at line 354 of file Profiler.cpp.
References Engine::Profiler::ProfileData::AddSample(), Engine::Profiler::ProfileDataPool::allocate(), Engine::Profiler::FastPathCache::find(), Engine::Profiler::FastPathCache::insert(), m_DataPool, m_Enabled, m_HasUnsavedData, m_LastWriteTime, m_Mutex, m_Profiles, Engine::s_LastSampleTime, Engine::SAMPLE_INTERVAL, t_FastPath, and WriteCompleteJSON().
Referenced by Engine::ProfilerTimer::~ProfilerTimer().
Member Data Documentation
BATCH_RESERVE_SIZE
constexpr size_t Engine::Profiler::BATCH_RESERVE_SIZE = 128 static constexpr private
Definition at line 146 of file Profiler.h.
Referenced by ReserveBatch().
FAST_PATH_SIZE
constexpr size_t Engine::Profiler::FAST_PATH_SIZE = 32 static constexpr private
Definition at line 151 of file Profiler.h.
Referenced by Engine::Profiler::FastPathCache::insert().
INITIAL_POOL_CAPACITY
constexpr size_t Engine::Profiler::INITIAL_POOL_CAPACITY = 1000 static constexpr private
Definition at line 145 of file Profiler.h.
INITIAL_VECTOR_CAPACITY
constexpr size_t Engine::Profiler::INITIAL_VECTOR_CAPACITY = 1000 static constexpr private
Definition at line 144 of file Profiler.h.
Referenced by Engine::Profiler::SmallVector< T, N >::push_back().
m_BatchedMeasurements
thread_local std::vector< Profiler::BatchEntry > Engine::Profiler::m_BatchedMeasurements static private
Definition at line 444 of file Profiler.h.
Referenced by FlushBatch(), ReserveBatch(), and RestoreProfilingState().
m_BatchSize
size_t Engine::Profiler::m_BatchSize = 0 private
Definition at line 445 of file Profiler.h.
Referenced by SetBatchSize().
m_CurrentProfiledFrame
uint32_t Engine::Profiler::m_CurrentProfiledFrame {0} private
Definition at line 526 of file Profiler.h.
Referenced by EndFrame(), GetCurrentProfiledFrame(), ProfileFrames(), and RestoreProfilingState().
m_CurrentSession
std::string Engine::Profiler::m_CurrentSession private
Definition at line 457 of file Profiler.h.
Referenced by BeginSession(), EndSession(), IsInitialized(), PreserveProfilingState(), ProfileFrames(), RestoreProfilingState(), WriteCompleteJSON(), and WriteFrameDataJSON().
m_DataPool
ProfileDataPool Engine::Profiler::m_DataPool private
Definition at line 412 of file Profiler.h.
Referenced by PreserveProfilingState(), RestoreProfilingState(), WriteProfile(), and ~Profiler().
m_Enabled
bool Engine::Profiler::m_Enabled {true} private
Definition at line 426 of file Profiler.h.
Referenced by EndSession(), IsEnabled(), IsInitialized(), RestoreProfilingState(), SetEnabled(), WriteCompleteJSON(), and WriteProfile().
m_FrameData
std::vector<FrameData> Engine::Profiler::m_FrameData private
Definition at line 538 of file Profiler.h.
Referenced by EndFrame(), ProfileFrames(), RestoreProfilingState(), WriteCompleteJSON(), and WriteFrameDataJSON().
m_FramesJSONPath
std::string Engine::Profiler::m_FramesJSONPath {"profiler_n_frames.json"} private
Definition at line 539 of file Profiler.h.
Referenced by WriteFrameDataJSON().
m_FramesToProfile
uint32_t Engine::Profiler::m_FramesToProfile {0} private
Definition at line 525 of file Profiler.h.
Referenced by EndFrame(), ProfileFrames(), and WriteFrameDataJSON().
m_HasUnsavedData
bool Engine::Profiler::m_HasUnsavedData {false} private
Definition at line 430 of file Profiler.h.
Referenced by BeginSession(), Cleanup(), FlushBatch(), RestoreProfilingState(), and WriteProfile().
m_HighPrecision
bool Engine::Profiler::m_HighPrecision = false private
Definition at line 446 of file Profiler.h.
Referenced by IsHighPrecision(), and SetHighPrecision().
m_JSONOutputPath
std::string Engine::Profiler::m_JSONOutputPath {"profile_results.json"} private
Definition at line 429 of file Profiler.h.
Referenced by BeginSession(), SetJSONOutputPath(), and WriteCompleteJSON().
m_LastWriteTime
std::chrono::steady_clock::time_point Engine::Profiler::m_LastWriteTime {std::chrono::steady_clock::now()} private
Definition at line 522 of file Profiler.h.
Referenced by RestoreProfilingState(), and WriteProfile().
m_MaxSamples
size_t Engine::Profiler::m_MaxSamples {500} private
Definition at line 432 of file Profiler.h.
Referenced by SetMaxSamples().
m_Mutex
std::shared_mutex Engine::Profiler::m_Mutex mutable private
Definition at line 434 of file Profiler.h.
Referenced by BeginSession(), FlushBatch(), InternString(), WriteCompleteJSON(), and WriteProfile().
m_OutputFormat
OutputFormat Engine::Profiler::m_OutputFormat {OutputFormat::JSON} private
Definition at line 428 of file Profiler.h.
Referenced by EndSession(), FlushBatch(), and SetOutputFormat().
m_Precision
int Engine::Profiler::m_Precision {4} private
Definition at line 433 of file Profiler.h.
Referenced by SetPrecision().
m_Profiles
ProfileMap Engine::Profiler::m_Profiles private
Definition at line 415 of file Profiler.h.
Referenced by ClearProfiles(), EndSession(), FlushBatch(), GetProfiles(), PreserveProfilingState(), RestoreProfilingState(), WriteCompleteJSON(), WriteProfile(), and ~Profiler().
m_ProfilingFrames
bool Engine::Profiler::m_ProfilingFrames {false} private
Definition at line 524 of file Profiler.h.
Referenced by EndFrame(), EndSession(), IsProfilingFrames(), ProfileFrames(), RestoreProfilingState(), and WriteCompleteJSON().
m_RegularProfiles
ProfileMap Engine::Profiler::m_RegularProfiles private
Definition at line 416 of file Profiler.h.
Referenced by PreserveProfilingState(), and RestoreProfilingState().
m_RegularSession
std::string Engine::Profiler::m_RegularSession private
Definition at line 458 of file Profiler.h.
Referenced by PreserveProfilingState(), and RestoreProfilingState().
m_StringPool
std::unordered_set<std::string> Engine::Profiler::m_StringPool private
Definition at line 427 of file Profiler.h.
Referenced by InternString().
MAX_PROFILE_FRAMES
constexpr uint32_t Engine::Profiler::MAX_PROFILE_FRAMES = 1000 static constexpr
Definition at line 37 of file Profiler.h.
Referenced by ProfileFrames().
MEMORY_POOL_SIZE
constexpr size_t Engine::Profiler::MEMORY_POOL_SIZE = 256 static constexpr private
Definition at line 149 of file Profiler.h.
Referenced by Engine::Profiler::ProfileDataPool::allocate(), and Engine::Profiler::ProfileDataPool::deallocate().
s_SignalsInitialized
bool Engine::Profiler::s_SignalsInitialized = false static private
Definition at line 431 of file Profiler.h.
Referenced by InitSignalHandlers().
SMALL_STRING_SIZE
constexpr size_t Engine::Profiler::SMALL_STRING_SIZE = 64 static constexpr private
Definition at line 147 of file Profiler.h.
Referenced by Engine::Profiler::ProfileName::ProfileName().
SMALL_VECTOR_SIZE
constexpr size_t Engine::Profiler::SMALL_VECTOR_SIZE = 16 static constexpr private
Definition at line 148 of file Profiler.h.
STRING_BUFFER_SIZE
constexpr size_t Engine::Profiler::STRING_BUFFER_SIZE = 1024 static constexpr private
Definition at line 150 of file Profiler.h.
Referenced by Engine::Profiler::ThreadLocalBuffer::allocate().
t_FastPath
thread_local Profiler::FastPathCache Engine::Profiler::t_FastPath static private
Definition at line 519 of file Profiler.h.
Referenced by RestoreProfilingState(), and WriteProfile().
t_StringBuffer
thread_local Profiler::ThreadLocalBuffer Engine::Profiler::t_StringBuffer static private
Definition at line 474 of file Profiler.h.
WRITE_INTERVAL
constexpr std::chrono::seconds Engine::Profiler::WRITE_INTERVAL {5} static constexpr private
Definition at line 521 of file Profiler.h.
The documentation for this class was generated from the following files:
src/Debug/Profiler.h
src/Debug/Profiler.cpp