Voxel Engine: Engine::Application Class Reference
Engine::Application Class Reference
Main application class handling window, rendering and game loop.
#include <Application.h>
Public Member Functions
Application ()
Initialize the application and all subsystems.
virtual ~Application ()
Clean up application resources.
void Run ()
Main application loop.
Renderer & GetRenderer ()
LuaScriptSystem * GetScriptSystem ()
InputSystem * GetInputSystem ()
virtual void OnImGuiRender ()
const std::string & GetAssetPath () const
ImGuiOverlay * GetImGuiOverlay ()
void SetRenderType (RenderType type)
RenderType GetRenderType () const
void SetCameraType (CameraType type)
CameraType GetCameraType () const
Static Public Member Functions
static Application & Get ()
Public Attributes
unsigned int indicies
Protected Member Functions
void InitWindow (const char *title="Voxel Engine", int width=1280, int height=720)
Initialize the application window.
void ShutdownWindow ()
Clean up window resources.
void BeginScene ()
Begin a new frame.
void EndScene ()
End the current frame.
void Present ()
Present the rendered frame.
void SetViewport (int x, int y, int width, int height)
Set the viewport dimensions.
void ProcessEvents ()
Process pending events.
void ConfigureForRenderType ()
Protected Attributes
std::unique_ptr< Renderer > m_Renderer
Engine::TerrainSystem * m_TerrainSystem = nullptr
Private Member Functions
bool HandleKeyToggle (int key, float currentTime)
Handle key toggle state changes.
void InitializeToggleStates ()
Initialize toggle states for keys.
void AddToggleState (int key, bool defaultValue=false)
Add a new key toggle state.
void RemoveToggleState (int key)
Remove a key toggle state.
bool GetToggleState (int key) const
Get current toggle state for a key.
void SetToggleState (int key, bool value)
Set toggle state for a key.
void UpdateFPSCounter (float deltaTime)
Update FPS counter and related statistics.
void ConfigureCamera ()
Private Attributes
bool m_Running = true
bool m_ImGuiEnabled = true
float m_DebounceTime = 0.3f
std::unordered_map< int, KeyToggleState > m_KeyToggles
const float MAX_TOGGLE_HOLD_TIME = 1.5f
std::unique_ptr< Window > m_Window
std::unique_ptr< ImGuiLayer > m_ImGuiLayer
std::unique_ptr< InputSystem > m_InputSystem
std::vector< std::unique_ptr< RenderableObject > > m_RenderableObjects
bool m_ShowFPSCounter = true
FPSCounter m_FPSCounter
std::unique_ptr< ImGuiOverlay > m_ImGuiOverlay
std::unique_ptr< Light > m_Light
std::unique_ptr< LuaScriptSystem > m_ScriptSystem
std::string m_AssetPath = "../sandbox/assets/"
RenderType m_RenderType = RenderType::Render3D
CameraType m_CameraType = CameraType::Perspective
Static Private Attributes
static Application * s_Instance = nullptr
Detailed Description
Main application class handling window, rendering and game loop.
Definition at line 36 of file Application.h.
Constructor & Destructor Documentation
Application()
Engine::Application::Application ()
Initialize the application and all subsystems.
Definition at line 62 of file Application.cpp.
References Engine::Profiler::BeginSession(), Engine::AssetManager::Get(), Engine::Profiler::Get(), InitializeToggleStates(), InitWindow(), LOG_ERROR, LOG_ERROR_CONCAT, LOG_FATAL, LOG_INFO, LOG_TRACE, m_ImGuiLayer, m_ImGuiOverlay, m_InputSystem, m_Renderer, m_ScriptSystem, m_TerrainSystem, m_Window, Engine::AssetManager::PreloadFrequentAssets(), and s_Instance.
~Application()
Engine::Application::~Application () virtual
Clean up application resources.
Definition at line 137 of file Application.cpp.
References Engine::AssetManager::Get(), LOG_INFO, m_ImGuiLayer, Engine::TerrainSystem::Shutdown(), and Engine::AssetManager::UnloadUnused().
Member Function Documentation
AddToggleState()
void Engine::Application::AddToggleState (int key, bool defaultValue = false) private
Add a new key toggle state.
Parameters
key GLFW key code
defaultValue Initial toggle state
Definition at line 410 of file Application.cpp.
References m_KeyToggles.
Referenced by InitializeToggleStates().
BeginScene()
void Engine::Application::BeginScene () protected
Begin a new frame.
Begins the rendering scene for the current frame.
This method prepares the rendering pipeline by performing several key steps:
Clears the renderer with a dark gray background color
Renders the current scene through the SceneManager
Initializes the ImGui layer for overlay rendering
If ImGui is enabled, renders various debug and performance overlays
Note
Uses profiling to track performance of the scene beginning process
Conditionally renders ImGui overlays based on m_ImGuiEnabled flag
Rendered overlays include:
FPS counter
Performance profiler
Renderer settings
Event debugger
Terrain controls
Definition at line 325 of file Application.cpp.
References Engine::FPSCounter::GetAverageFPS(), Engine::FPSCounter::GetCurrentFPS(), Engine::FPSCounter::GetFrameTime(), Engine::FPSCounter::GetOnePercentHigh(), Engine::FPSCounter::GetOnePercentLow(), m_FPSCounter, m_ImGuiEnabled, m_ImGuiLayer, m_ImGuiOverlay, m_Renderer, m_RenderType, m_ScriptSystem, m_ShowFPSCounter, PROFILE_FUNCTION, and Engine::Render3D.
Referenced by Run().
ConfigureCamera()
void Engine::Application::ConfigureCamera () private
Definition at line 455 of file Application.cpp.
References LOG_ERROR, LOG_TRACE_CONCAT, m_CameraType, m_Renderer, Engine::Renderer::Orthographic, and Engine::Perspective.
Referenced by SetCameraType().
ConfigureForRenderType()
void Engine::Application::ConfigureForRenderType () protected
Definition at line 430 of file Application.cpp.
References Engine::SceneManager::Get(), Engine::SceneManager::GetActiveScene(), GetRenderer(), Engine::TerrainSystem::Initialize(), m_RenderType, m_TerrainSystem, Engine::Orthographic, Engine::Perspective, Engine::Render2D, Engine::Render3D, and Engine::TerrainSystem::Shutdown().
Referenced by SetRenderType().
EndScene()
void Engine::Application::EndScene () protected
End the current frame.
Definition at line 375 of file Application.cpp.
References m_ImGuiLayer, m_Window, and PROFILE_FUNCTION.
Referenced by Run().
Get()
static Application & Engine::Application::Get () inline static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 52 of file Application.h.
References s_Instance.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetAssetPath()
const std::string & Engine::Application::GetAssetPath () const inline
Definition at line 57 of file Application.h.
References m_AssetPath.
GetCameraType()
CameraType Engine::Application::GetCameraType () const inline
Definition at line 71 of file Application.h.
References m_CameraType.
GetImGuiOverlay()
ImGuiOverlay * Engine::Application::GetImGuiOverlay () inline
Definition at line 59 of file Application.h.
References m_ImGuiOverlay.
GetInputSystem()
InputSystem * Engine::Application::GetInputSystem () inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 53 of file Application.h.
References m_InputSystem.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetRenderer()
Renderer & Engine::Application::GetRenderer () inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 48 of file Application.h.
References m_Renderer.
Referenced by ConfigureForRenderType(), and Engine::LuaScriptSystem::RegisterEngineAPI().
GetRenderType()
RenderType Engine::Application::GetRenderType () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 65 of file Application.h.
References m_RenderType.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetScriptSystem()
LuaScriptSystem * Engine::Application::GetScriptSystem () inline
Definition at line 50 of file Application.h.
References m_ScriptSystem.
GetToggleState()
bool Engine::Application::GetToggleState (int key) const private
Get current toggle state for a key.
Parameters
key GLFW key code
Returns
bool Current toggle state
Definition at line 418 of file Application.cpp.
References Engine::KeyToggleState::currentValue, and m_KeyToggles.
HandleKeyToggle()
bool Engine::Application::HandleKeyToggle (int key, float currentTime) private
Handle key toggle state changes.
Parameters
key GLFW key code
currentTime Current time
Returns
bool True if toggle state changed
Definition at line 387 of file Application.cpp.
References m_InputSystem, m_KeyToggles, and MAX_TOGGLE_HOLD_TIME.
Referenced by Run().
InitializeToggleStates()
void Engine::Application::InitializeToggleStates () private
Initialize toggle states for keys.
Definition at line 382 of file Application.cpp.
References AddToggleState().
Referenced by Application().
InitWindow()
void Engine::Application::InitWindow (const char * title = "Voxel Engine", int width = 1280, int height = 720) protected
Initialize the application window.
Initializes the application window with specified parameters and sets up event handling.
Parameters
title Window title
width Window width
height Window height
Creates a window using the provided title, width, and height. Configures an event callback to handle window events such as resizing and input events (key presses, mouse movements). Registered events are cloned and pushed to the global event queue for further processing.
Parameters
title The title of the window to be created
width The width of the window in pixels
height The height of the window in pixels
Note
Logs window creation details using trace-level logging
Sets the window context after creation
See also
Window
Event
EventQueue
Definition at line 270 of file Application.cpp.
References Engine::Window::Create(), Engine::EventQueue::Get(), Engine::Event::GetEventType(), Engine::KeyPressed, LOG_TRACE_CONCAT, m_Window, Engine::MouseMoved, Engine::EventQueue::PushEvent(), and Engine::WindowResize.
Referenced by Application().
OnImGuiRender()
virtual void Engine::Application::OnImGuiRender () inline virtual
Definition at line 55 of file Application.h.
Referenced by Run().
Present()
void Engine::Application::Present () protected
Present the rendered frame.
Renders the current frame by invoking the renderer's drawing method.
This method triggers the drawing process for the current frame, delegating the rendering task to the renderer instance. It is typically called as part of the application's rendering pipeline to display the graphical output.
Note
Uses the PROFILE_FUNCTION() macro for performance profiling.
Precondition
A valid renderer instance must be initialized and available.
Postcondition
The current frame is rendered and prepared for display.
Definition at line 369 of file Application.cpp.
References m_Renderer, and PROFILE_FUNCTION.
Referenced by Run().
ProcessEvents()
void Engine::Application::ProcessEvents () protected
Process pending events.
Process pending events in the event queue.
Definition at line 208 of file Application.cpp.
References Engine::EventDispatcher::Dispatch(), Engine::EVENT_PROCESS_INTERVAL, Engine::EventQueue::Get(), LOG_INFO, m_InputSystem, m_Running, Engine::NUM_0, Engine::EventQueue::ProcessEvents(), and Engine::EventQueue::PushEvent().
Referenced by Run().
RemoveToggleState()
void Engine::Application::RemoveToggleState (int key) private
Remove a key toggle state.
Parameters
key GLFW key code
Definition at line 414 of file Application.cpp.
References m_KeyToggles.
Run()
void Engine::Application::Run ()
Main application loop.
Executes the main application loop, managing rendering, input processing, and system updates.
This method is the core of the application's runtime behavior. It:
Manages the application's main event loop
Processes system updates at each frame
Handles input and toggle states
Manages rendering and scene management
Supports performance profiling and debug features
Note
The loop continues until m_Running is false or the window is closed
Precondition
Application systems must be initialized before calling
Window and input systems must be operational
@performance O(1) per frame, with complexity dependent on scene and system updates
@thread_safety Not thread-safe; should be called from the main thread
Definition at line 165 of file Application.cpp.
References BeginScene(), Engine::Profiler::BeginSession(), EndScene(), Engine::Profiler::Get(), Engine::EventDebugger::Get(), Engine::SceneManager::Get(), Engine::ShaderHotReload::Get(), HandleKeyToggle(), LOG_INFO, m_ImGuiEnabled, m_InputSystem, m_KeyToggles, m_Running, m_ShowFPSCounter, m_Window, OnImGuiRender(), Present(), ProcessEvents(), PROFILE_FUNCTION, Engine::ShaderHotReload::Update(), Engine::SceneManager::Update(), UpdateFPSCounter(), and Engine::EventDebugger::UpdateTimestamps().
SetCameraType()
void Engine::Application::SetCameraType (CameraType type) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 67 of file Application.h.
References ConfigureCamera(), and m_CameraType.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SetRenderType()
void Engine::Application::SetRenderType (RenderType type) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 61 of file Application.h.
References ConfigureForRenderType(), and m_RenderType.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SetToggleState()
void Engine::Application::SetToggleState (int key, bool value) private
Set toggle state for a key.
Parameters
key GLFW key code
value New toggle state
Definition at line 423 of file Application.cpp.
References m_KeyToggles.
SetViewport()
void Engine::Application::SetViewport (int x, int y, int width, int height) inline protected
Set the viewport dimensions.
Definition at line 105 of file Application.h.
References m_Renderer.
ShutdownWindow()
void Engine::Application::ShutdownWindow () protected
Clean up window resources.
Definition at line 301 of file Application.cpp.
References LOG_INFO, and m_Window.
UpdateFPSCounter()
void Engine::Application::UpdateFPSCounter (float deltaTime) private
Update FPS counter and related statistics.
Parameters
deltaTime Time since last frame
currentTime Current application time
Definition at line 248 of file Application.cpp.
References m_FPSCounter, and Engine::FPSCounter::Update().
Referenced by Run().
Member Data Documentation
indicies
unsigned int Engine::Application::indicies
Definition at line 46 of file Application.h.
m_AssetPath
std::string Engine::Application::m_AssetPath = "../sandbox/assets/" private
Definition at line 191 of file Application.h.
Referenced by GetAssetPath().
m_CameraType
CameraType Engine::Application::m_CameraType = CameraType::Perspective private
Definition at line 195 of file Application.h.
Referenced by ConfigureCamera(), GetCameraType(), and SetCameraType().
m_DebounceTime
float Engine::Application::m_DebounceTime = 0.3f private
Definition at line 163 of file Application.h.
m_FPSCounter
FPSCounter Engine::Application::m_FPSCounter private
Definition at line 178 of file Application.h.
Referenced by BeginScene(), and UpdateFPSCounter().
m_ImGuiEnabled
bool Engine::Application::m_ImGuiEnabled = true private
Definition at line 161 of file Application.h.
Referenced by BeginScene(), and Run().
m_ImGuiLayer
std::unique_ptr<ImGuiLayer> Engine::Application::m_ImGuiLayer private
Definition at line 170 of file Application.h.
Referenced by Application(), BeginScene(), EndScene(), and ~Application().
m_ImGuiOverlay
std::unique_ptr<ImGuiOverlay> Engine::Application::m_ImGuiOverlay private
Definition at line 180 of file Application.h.
Referenced by Application(), BeginScene(), and GetImGuiOverlay().
m_InputSystem
std::unique_ptr<InputSystem> Engine::Application::m_InputSystem private
Definition at line 171 of file Application.h.
Referenced by Application(), GetInputSystem(), HandleKeyToggle(), ProcessEvents(), and Run().
m_KeyToggles
std::unordered_map<int, KeyToggleState> Engine::Application::m_KeyToggles private
Definition at line 165 of file Application.h.
Referenced by AddToggleState(), GetToggleState(), HandleKeyToggle(), RemoveToggleState(), Run(), and SetToggleState().
m_Light
std::unique_ptr<Light> Engine::Application::m_Light private
Definition at line 184 of file Application.h.
m_RenderableObjects
std::vector<std::unique_ptr<RenderableObject> > Engine::Application::m_RenderableObjects private
Definition at line 174 of file Application.h.
m_Renderer
std::unique_ptr<Renderer> Engine::Application::m_Renderer protected
Definition at line 116 of file Application.h.
Referenced by Application(), BeginScene(), ConfigureCamera(), GetRenderer(), Present(), and SetViewport().
m_RenderType
RenderType Engine::Application::m_RenderType = RenderType::Render3D private
Definition at line 193 of file Application.h.
Referenced by BeginScene(), ConfigureForRenderType(), GetRenderType(), and SetRenderType().
m_Running
bool Engine::Application::m_Running = true private
Definition at line 160 of file Application.h.
Referenced by ProcessEvents(), and Run().
m_ScriptSystem
std::unique_ptr<LuaScriptSystem> Engine::Application::m_ScriptSystem private
Definition at line 187 of file Application.h.
Referenced by Application(), BeginScene(), and GetScriptSystem().
m_ShowFPSCounter
bool Engine::Application::m_ShowFPSCounter = true private
Definition at line 177 of file Application.h.
Referenced by BeginScene(), and Run().
m_TerrainSystem
Engine::TerrainSystem* Engine::Application::m_TerrainSystem = nullptr protected
Definition at line 117 of file Application.h.
Referenced by Application(), and ConfigureForRenderType().
m_Window
std::unique_ptr<Window> Engine::Application::m_Window private
Definition at line 169 of file Application.h.
Referenced by Application(), EndScene(), InitWindow(), Run(), and ShutdownWindow().
MAX_TOGGLE_HOLD_TIME
const float Engine::Application::MAX_TOGGLE_HOLD_TIME = 1.5f private
Definition at line 167 of file Application.h.
Referenced by HandleKeyToggle().
s_Instance
Application * Engine::Application::s_Instance = nullptr static private
Definition at line 189 of file Application.h.
Referenced by Application(), and Get().
The documentation for this class was generated from the following files:
src/Application.h
src/Application.cpp