Voxel Engine: Engine::EventDebugger Class Reference
Engine::EventDebugger Class Reference
#include <EventDebugger.h>
Classes
struct EventDebugInfo
Debug information for an event instance.
Public Member Functions
void LogEvent (const std::shared_ptr< Event > &event)
Records an event for debugging.
const std::deque< EventDebugInfo > & GetEventHistory () const
void Clear ()
Clears event history.
void UpdateTimestamps (float deltaTime)
Updates time information for logged events.
Static Public Member Functions
static EventDebugger & Get ()
Private Member Functions
EventDebugger ()=default
Private Attributes
std::deque< EventDebugInfo > m_EventHistory
std::mutex m_Mutex
const size_t m_MaxEventHistory = 5
Detailed Description
Definition at line 7 of file EventDebugger.h.
Constructor & Destructor Documentation
EventDebugger()
Engine::EventDebugger::EventDebugger () private default
Member Function Documentation
Clear()
void Engine::EventDebugger::Clear () inline
Clears event history.
Definition at line 52 of file EventDebugger.h.
References m_EventHistory, and m_Mutex.
Get()
static EventDebugger & Engine::EventDebugger::Get () inline static
Returns
Reference to singleton instance
Definition at line 22 of file EventDebugger.h.
Referenced by Engine::EventQueue::PushEvent(), Engine::ImGuiOverlay::RenderEventDebugger(), and Engine::Application::Run().
GetEventHistory()
const std::deque< EventDebugInfo > & Engine::EventDebugger::GetEventHistory () const inline
Returns
List of recent events
Definition at line 49 of file EventDebugger.h.
References m_EventHistory.
Referenced by Engine::ImGuiOverlay::RenderEventDebugger().
LogEvent()
void Engine::EventDebugger::LogEvent (const std::shared_ptr< Event > & event) inline
Records an event for debugging.
Parameters
event Event to log
Definition at line 31 of file EventDebugger.h.
References m_EventHistory, and m_Mutex.
Referenced by Engine::EventQueue::PushEvent().
UpdateTimestamps()
void Engine::EventDebugger::UpdateTimestamps (float deltaTime) inline
Updates time information for logged events.
Parameters
deltaTime Time elapsed since last update
Definition at line 61 of file EventDebugger.h.
References m_EventHistory, and m_Mutex.
Referenced by Engine::Application::Run().
Member Data Documentation
m_EventHistory
std::deque<EventDebugInfo> Engine::EventDebugger::m_EventHistory private
Definition at line 70 of file EventDebugger.h.
Referenced by Clear(), GetEventHistory(), LogEvent(), and UpdateTimestamps().
m_MaxEventHistory
const size_t Engine::EventDebugger::m_MaxEventHistory = 5 private
Definition at line 72 of file EventDebugger.h.
m_Mutex
std::mutex Engine::EventDebugger::m_Mutex mutable private
Definition at line 71 of file EventDebugger.h.
Referenced by Clear(), LogEvent(), and UpdateTimestamps().
The documentation for this class was generated from the following file:
src/Events/EventDebugger.h