Voxel Engine: Engine::ShaderHotReload Class Reference
Engine::ShaderHotReload Class Reference
Manages hot-reloading of shader files.
#include <ShaderHotReload.h>
Public Member Functions
void WatchShader (const std::shared_ptr< Shader > &shader, const std::string &vertPath, const std::string &fragPath)
Sets up file watching for a shader's vertex and fragment files.
void Update ()
Updates the file watcher to check for changes.
Static Public Member Functions
static ShaderHotReload & Get ()
Gets the singleton instance of ShaderHotReload.
Private Member Functions
void ReloadShader (const std::shared_ptr< Shader > &shader, const std::string &vertPath, const std::string &fragPath)
Reloads a shader from its source files.
Private Attributes
FileWatcher m_Watcher
std::unordered_map< std::shared_ptr< Shader >, std::pair< std::string, std::string > > m_ShaderPaths
Detailed Description
Manages hot-reloading of shader files.
This class watches shader files for changes and automatically reloads them when modifications are detected, enabling real-time shader development.
Definition at line 14 of file ShaderHotReload.h.
Member Function Documentation
Get()
ShaderHotReload & Engine::ShaderHotReload::Get () static
Gets the singleton instance of ShaderHotReload.
Gets the singleton instance.
Returns
Reference to the ShaderHotReload instance
Definition at line 6 of file ShaderHotReload.cpp.
Referenced by Engine::Shader::EnableHotReload(), and Engine::Application::Run().
ReloadShader()
void Engine::ShaderHotReload::ReloadShader (const std::shared_ptr< Shader > & shader, const std::string & vertPath, const std::string & fragPath) private
Reloads a shader from its source files.
Handles shader reloading.
Parameters
shader The shader to reload
vertPath Path to the vertex shader file
fragPath Path to the fragment shader file
Definition at line 27 of file ShaderHotReload.cpp.
References LOG_ERROR, and LOG_INFO.
Referenced by WatchShader().
Update()
void Engine::ShaderHotReload::Update ()
Updates the file watcher to check for changes.
Updates file watching system.
Definition at line 42 of file ShaderHotReload.cpp.
References m_Watcher, and Engine::FileWatcher::Update().
Referenced by Engine::Application::Run().
WatchShader()
void Engine::ShaderHotReload::WatchShader (const std::shared_ptr< Shader > & shader, const std::string & vertPath, const std::string & fragPath)
Sets up file watching for a shader's vertex and fragment files.
Implements shader file watching.
Parameters
shader The shader to watch
vertPath Path to the vertex shader file
fragPath Path to the fragment shader file
Definition at line 12 of file ShaderHotReload.cpp.
References m_ShaderPaths, m_Watcher, ReloadShader(), and Engine::FileWatcher::WatchFile().
Referenced by Engine::Shader::EnableHotReload().
Member Data Documentation
m_ShaderPaths
std::unordered_map<std::shared_ptr<Shader>, std::pair<std::string, std::string> > Engine::ShaderHotReload::m_ShaderPaths private
Definition at line 51 of file ShaderHotReload.h.
Referenced by WatchShader().
m_Watcher
FileWatcher Engine::ShaderHotReload::m_Watcher private
Definition at line 50 of file ShaderHotReload.h.
Referenced by Update(), and WatchShader().
The documentation for this class was generated from the following files:
src/Shader/ShaderHotReload.h
src/Shader/ShaderHotReload.cpp