Voxel Engine: Engine::VertexArray Class Reference
Engine::VertexArray Class Reference abstract
Abstract base class for vertex array objects.
#include <VertexArray.h>
Public Member Functions
virtual ~VertexArray ()=default
virtual void Bind () const =0
Bind the vertex array.
virtual void Unbind () const =0
Unbind the vertex array.
virtual void AddVertexBuffer (const std::shared_ptr< VertexBuffer > &vertexBuffer)=0
Add a vertex buffer to the array.
virtual void SetIndexBuffer (const std::shared_ptr< IndexBuffer > &indexBuffer)=0
Set the index buffer for this array.
virtual const std::vector< std::shared_ptr< VertexBuffer > > & GetVertexBuffers () const =0
Get all vertex buffers.
virtual const std::shared_ptr< IndexBuffer > & GetIndexBuffer () const =0
Get the index buffer.
Static Public Member Functions
static VertexArray * Create ()
Creates a new platform-specific vertex array.
Detailed Description
Abstract base class for vertex array objects.
Represents a vertex array object that stores vertex attributes and their configurations for rendering.
Definition at line 12 of file VertexArray.h.
Constructor & Destructor Documentation
~VertexArray()
virtual Engine::VertexArray::~VertexArray () virtual default
Member Function Documentation
AddVertexBuffer()
virtual void Engine::VertexArray::AddVertexBuffer (const std::shared_ptr< VertexBuffer > & vertexBuffer) pure virtual
Add a vertex buffer to the array.
Parameters
vertexBuffer Buffer containing vertex data
Implemented in Engine::OpenGLVertexArray.
Bind()
virtual void Engine::VertexArray::Bind () const pure virtual
Bind the vertex array.
Implemented in Engine::OpenGLVertexArray.
Create()
VertexArray * Engine::VertexArray::Create () static
Creates a new platform-specific vertex array.
Factory method to create a new vertex array.
Returns
Pointer to the created vertex array
A new OpenGL vertex array instance
Definition at line 13 of file VertexArray.cpp.
Referenced by Engine::TerrainSystem::GenerateMesh(), Engine::AssetManager::GetOrCreateCubeMesh(), and Engine::Renderer2D::Initialize().
GetIndexBuffer()
virtual const std::shared_ptr< IndexBuffer > & Engine::VertexArray::GetIndexBuffer () const pure virtual
Get the index buffer.
Returns
Reference to index buffer
Implemented in Engine::OpenGLVertexArray.
GetVertexBuffers()
virtual const std::vector< std::shared_ptr< VertexBuffer > > & Engine::VertexArray::GetVertexBuffers () const pure virtual
Get all vertex buffers.
Returns
Vector of vertex buffer references
Implemented in Engine::OpenGLVertexArray.
SetIndexBuffer()
virtual void Engine::VertexArray::SetIndexBuffer (const std::shared_ptr< IndexBuffer > & indexBuffer) pure virtual
Set the index buffer for this array.
Parameters
indexBuffer Buffer containing index data
Implemented in Engine::OpenGLVertexArray.
Unbind()
virtual void Engine::VertexArray::Unbind () const pure virtual
Unbind the vertex array.
Implemented in Engine::OpenGLVertexArray.
The documentation for this class was generated from the following files:
src/Renderer/VertexArray.h
src/Renderer/VertexArray.cpp