Voxel Engine: Engine::AssetManager Class Reference
Engine::AssetManager Class Reference
Manages loading, caching, and unloading of game assets.
#include <AssetManager.h>
Public Member Functions
template<typename T >
std::shared_ptr< T > LoadResource (const std::string &path)
Load a resource of specified type from path.
template<typename T >
void MarkAsFrequentlyUsed (const std::string &path)
Mark a resource as frequently used to prevent automatic unloading.
void UnmarkAsFrequentlyUsed (const std::string &path)
Remove a resource from the frequently used list.
bool IsFrequentlyUsed (const std::string &path) const
Check if a resource is marked as frequently used.
void PreloadFrequentAssets ()
Preload frequently used assets into memory.
void UnloadResource (const std::string &path)
Decrease reference count of a resource and potentially unload it.
void UnloadUnused ()
Unload all resources that are not marked as frequently used and have no references.
template<typename T >
std::future< std::shared_ptr< T > > LoadResourceAsync (const std::string &path)
Asynchronously load a resource.
size_t GetTotalMemoryUsage () const
Get total memory usage of loaded resources.
void UpdateMemoryUsage (size_t delta)
Update the total memory usage counter.
std::shared_ptr< VertexArray > GetOrCreateCubeMesh ()
Get or create a cube mesh.
Static Public Member Functions
static AssetManager & Get ()
Get the singleton instance of the AssetManager.
Private Member Functions
AssetManager ()=default
~AssetManager ()
void UnloadAll ()
Unload all resources from memory.
Private Attributes
std::unordered_map< std::string, std::shared_ptr< Resource > > m_ResourceCache
Main resource cache.
std::unordered_map< std::string, std::shared_ptr< Resource > > m_FrequentResourceCache
Cache for frequently used resources.
std::unordered_set< std::string > m_FrequentlyUsedPaths
Set of paths marked as frequently used.
size_t m_TotalMemoryUsage = 0
Total memory used by all resources.
Detailed Description
Manages loading, caching, and unloading of game assets.
Implements a singleton pattern for global asset management with support for frequently used resources and asynchronous loading
Definition at line 19 of file AssetManager.h.
Constructor & Destructor Documentation
AssetManager()
Engine::AssetManager::AssetManager () private default
~AssetManager()
Engine::AssetManager::~AssetManager () inline private
Definition at line 219 of file AssetManager.h.
References UnloadAll().
Member Function Documentation
Get()
static AssetManager & Engine::AssetManager::Get () inline static
Get the singleton instance of the AssetManager.
Returns
Reference to the AssetManager instance
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 25 of file AssetManager.h.
Referenced by Engine::Application::Application(), Engine::Shader::CreateFromFiles(), Engine::Material::Material(), Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::Application::~Application().
GetOrCreateCubeMesh()
std::shared_ptr< VertexArray > Engine::AssetManager::GetOrCreateCubeMesh () inline
Get or create a cube mesh.
Returns
Shared pointer to the cube mesh
Definition at line 161 of file AssetManager.h.
References Engine::VertexArray::Create(), Engine::VertexBuffer::Create(), Engine::IndexBuffer::Create(), and Engine::Float3.
GetTotalMemoryUsage()
size_t Engine::AssetManager::GetTotalMemoryUsage () const inline
Get total memory usage of loaded resources.
Returns
Size in bytes of memory used
Definition at line 149 of file AssetManager.h.
References m_TotalMemoryUsage.
IsFrequentlyUsed()
bool Engine::AssetManager::IsFrequentlyUsed (const std::string & path) const inline
Check if a resource is marked as frequently used.
Parameters
path Path to the resource
Returns
true if the resource is frequently used
Definition at line 97 of file AssetManager.h.
References m_FrequentlyUsedPaths.
Referenced by UnloadAll(), and UnloadUnused().
LoadResource()
template<typename T > std::shared_ptr< T > Engine::AssetManager::LoadResource (const std::string & path) inline
Load a resource of specified type from path.
Template Parameters
T The resource type to load
Parameters
path Path to the resource file
Returns
Shared pointer to the loaded resource
Definition at line 37 of file AssetManager.h.
References LOG_ERROR_CONCAT, and m_ResourceCache.
Referenced by Engine::Shader::CreateFromFiles().
LoadResourceAsync()
template<typename T > std::future< std::shared_ptr< T > > Engine::AssetManager::LoadResourceAsync (const std::string & path) inline
Asynchronously load a resource.
Template Parameters
T The resource type to load
Parameters
path Path to the resource
Returns
Future containing the loaded resource
Definition at line 139 of file AssetManager.h.
MarkAsFrequentlyUsed()
template<typename T > void Engine::AssetManager::MarkAsFrequentlyUsed (const std::string & path) inline
Mark a resource as frequently used to prevent automatic unloading.
Template Parameters
T The resource type
Parameters
path Path to the resource
Definition at line 66 of file AssetManager.h.
References m_FrequentlyUsedPaths, m_FrequentResourceCache, and m_ResourceCache.
PreloadFrequentAssets()
void Engine::AssetManager::PreloadFrequentAssets () inline
Preload frequently used assets into memory.
Definition at line 102 of file AssetManager.h.
Referenced by Engine::Application::Application().
UnloadAll()
void Engine::AssetManager::UnloadAll () inline private
Unload all resources from memory.
Definition at line 224 of file AssetManager.h.
References IsFrequentlyUsed(), m_FrequentlyUsedPaths, m_FrequentResourceCache, m_ResourceCache, and m_TotalMemoryUsage.
Referenced by ~AssetManager().
UnloadResource()
void Engine::AssetManager::UnloadResource (const std::string & path) inline
Decrease reference count of a resource and potentially unload it.
Parameters
path Path to the resource
Definition at line 110 of file AssetManager.h.
References m_ResourceCache.
UnloadUnused()
void Engine::AssetManager::UnloadUnused () inline
Unload all resources that are not marked as frequently used and have no references.
Definition at line 121 of file AssetManager.h.
References IsFrequentlyUsed(), and m_ResourceCache.
Referenced by Engine::Application::~Application().
UnmarkAsFrequentlyUsed()
void Engine::AssetManager::UnmarkAsFrequentlyUsed (const std::string & path) inline
Remove a resource from the frequently used list.
Parameters
path Path to the resource
Definition at line 80 of file AssetManager.h.
References m_FrequentlyUsedPaths, m_FrequentResourceCache, and m_ResourceCache.
UpdateMemoryUsage()
void Engine::AssetManager::UpdateMemoryUsage (size_t delta) inline
Update the total memory usage counter.
Parameters
delta Change in memory usage
Definition at line 155 of file AssetManager.h.
References m_TotalMemoryUsage.
Member Data Documentation
m_FrequentlyUsedPaths
std::unordered_set<std::string> Engine::AssetManager::m_FrequentlyUsedPaths private
Set of paths marked as frequently used.
Definition at line 245 of file AssetManager.h.
Referenced by IsFrequentlyUsed(), MarkAsFrequentlyUsed(), UnloadAll(), and UnmarkAsFrequentlyUsed().
m_FrequentResourceCache
std::unordered_map<std::string, std::shared_ptr<Resource> > Engine::AssetManager::m_FrequentResourceCache private
Cache for frequently used resources.
Definition at line 244 of file AssetManager.h.
Referenced by MarkAsFrequentlyUsed(), UnloadAll(), and UnmarkAsFrequentlyUsed().
m_ResourceCache
std::unordered_map<std::string, std::shared_ptr<Resource> > Engine::AssetManager::m_ResourceCache private
Main resource cache.
Definition at line 243 of file AssetManager.h.
Referenced by LoadResource(), MarkAsFrequentlyUsed(), UnloadAll(), UnloadResource(), UnloadUnused(), and UnmarkAsFrequentlyUsed().
m_TotalMemoryUsage
size_t Engine::AssetManager::m_TotalMemoryUsage = 0 private
Total memory used by all resources.
Definition at line 246 of file AssetManager.h.
Referenced by GetTotalMemoryUsage(), UnloadAll(), and UpdateMemoryUsage().
The documentation for this class was generated from the following file:
src/Core/AssetManager.h