Voxel Engine: Engine::InputSystem Class Reference
Engine::InputSystem Class Reference
Handles all input processing for the application.
#include <InputSystem.h>
Public Types
using KeyCallback = std::function< void(int)>
Public Member Functions
InputSystem (Window *window, Renderer &renderer)
Constructs an input system.
void Update (float deltaTime)
Updates input state and handles continuous input.
void OnEvent (Event &e)
Processes input events.
bool IsKeyPressed (int keycode) const
Checks if a key is currently pressed.
bool IsMouseButtonPressed (int button) const
Checks if a mouse button is currently pressed.
std::pair< float, float > GetMousePosition () const
Gets the current mouse cursor position.
void SetSensitivity (float sensitivity)
Sets mouse sensitivity.
float GetSensitivity () const
void ToggleCameraControls ()
void ToggleSmoothCamera ()
void SetMovementSpeed (float speed)
float GetMovementSpeed () const
void ToggleMovementLock ()
void RegisterKeyCallback (int key, KeyCallback callback)
Registers a custom callback function for a specific key event.
void OnKey (int key, int scancode, int action, int mods)
Handles key press events for the input system.
Private Member Functions
void HandleMouseMovement (const MouseMovedEvent &e)
Handles mouse movement input.
void HandleKeyInput (float deltaTime)
Processes keyboard input.
void HandleCameraMovement (float deltaTime)
Updates camera position based on input.
void HandleSpeedModifiers (float &speed) const
void HandleSensitivityAdjustment ()
void SmoothDamp (glm::vec3 &current, const glm::vec3 &target, glm::vec3 &velocity, float smoothTime, float deltaTime)
void UpdateCursorState ()
Updates cursor visibility and lock state.
void OnKeyEvent (int key, int action)
Executes a registered callback for a specific key event.
Private Attributes
Window * m_Window
Pointer to application window.
Renderer & m_Renderer
Reference to renderer.
bool m_FirstMouse = true
First mouse input flag.
float m_LastMouseX = 0.0f
Last mouse X position.
float m_LastMouseY = 0.0f
Last mouse Y position.
float m_MouseSensitivity = 0.1f
Mouse movement sensitivity.
bool m_CameraEnabled = true
Toggle for camera controls.
bool m_SmoothCamera = true
Toggle for smooth camera movement.
const float FIXED_TIMESTEP = 1.0f / 60.0f
60Hz update rate
float m_MovementAccumulator = 0.0f
Time accumulator for movement updates.
float m_MovementSpeed = 250.0f
Base movement speed (blocks per second)
float m_SprintMultiplier = 2.0f
Sprint speed multiplier.
float m_SlowMultiplier = 1.0f
Slow movement multiplier.
glm::vec3 m_TargetPosition {0.0f}
Target position for smooth movement.
glm::vec3 m_CurrentVelocity {0.0f}
Current velocity for smooth damping.
float m_SmoothTime = 0.1f
Smoothing time factor.
bool m_LastVPressed = false
Previous frame V key state.
bool m_LastBPressed = false
Previous frame B key state.
bool m_MovementLocked = false
Global movement lock flag.
bool m_LastEscPressed = false
Previous frame ESC key state.
bool m_CursorLocked = false
Is cursor locked to window center.
std::unordered_map< int, KeyCallback > m_KeyCallbacks
Detailed Description
Handles all input processing for the application.
Manages keyboard and mouse input, camera controls, and input event handling. Provides an interface between GLFW input and the game systems.
Definition at line 17 of file InputSystem.h.
Member Typedef Documentation
KeyCallback
using Engine::InputSystem::KeyCallback = std::function<void(int)>
Definition at line 76 of file InputSystem.h.
Constructor & Destructor Documentation
InputSystem()
Engine::InputSystem::InputSystem (Window * window, Renderer & renderer)
Constructs an input system.
Parameters
window Pointer to the application window
renderer Reference to the renderer
Definition at line 17 of file InputSystem.cpp.
References m_CursorLocked, m_Window, and UpdateCursorState().
Member Function Documentation
GetMousePosition()
std::pair< float, float > Engine::InputSystem::GetMousePosition () const
Gets the current mouse cursor position.
Returns
Pair of x,y coordinates
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 192 of file InputSystem.cpp.
References Engine::Window::GetNativeWindow(), and m_Window.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetMovementSpeed()
float Engine::InputSystem::GetMovementSpeed () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 72 of file InputSystem.h.
References m_MovementSpeed.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetSensitivity()
float Engine::InputSystem::GetSensitivity () const inline
Returns
Current mouse sensitivity
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 66 of file InputSystem.h.
References m_MouseSensitivity.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
HandleCameraMovement()
void Engine::InputSystem::HandleCameraMovement (float deltaTime) private
Updates camera position based on input.
Parameters
deltaTime Time elapsed since last update
Definition at line 95 of file InputSystem.cpp.
References Engine::Renderer::GetCamera(), Engine::Renderer::GetCameraType(), Engine::Renderer::GetPerspectiveCamera(), HandleSpeedModifiers(), IsKeyPressed(), m_CameraEnabled, m_CurrentVelocity, m_MovementLocked, m_MovementSpeed, m_Renderer, m_SmoothCamera, m_SmoothTime, m_TargetPosition, Engine::Renderer::Perspective, and SmoothDamp().
Referenced by Update().
HandleKeyInput()
void Engine::InputSystem::HandleKeyInput (float deltaTime) private
Processes keyboard input.
Parameters
deltaTime Time elapsed since last update
Definition at line 43 of file InputSystem.cpp.
References HandleSensitivityAdjustment(), IsKeyPressed(), m_CursorLocked, m_LastBPressed, m_LastEscPressed, m_LastVPressed, m_Renderer, Engine::Renderer::Orthographic, Engine::Renderer::Perspective, Engine::Renderer::SetCameraType(), ToggleCameraControls(), ToggleMovementLock(), ToggleSmoothCamera(), and UpdateCursorState().
Referenced by Update().
HandleMouseMovement()
void Engine::InputSystem::HandleMouseMovement (const MouseMovedEvent & e) private
Handles mouse movement input.
Parameters
e Mouse moved event
Definition at line 158 of file InputSystem.cpp.
References Engine::Renderer::GetCameraType(), Engine::Renderer::GetPerspectiveCamera(), Engine::MouseMovedEvent::GetX(), Engine::MouseMovedEvent::GetY(), m_CameraEnabled, m_FirstMouse, m_LastMouseX, m_LastMouseY, m_MouseSensitivity, m_MovementLocked, m_Renderer, and Engine::Renderer::Perspective.
Referenced by OnEvent().
HandleSensitivityAdjustment()
void Engine::InputSystem::HandleSensitivityAdjustment () private
Definition at line 78 of file InputSystem.cpp.
References IsKeyPressed(), and m_MouseSensitivity.
Referenced by HandleKeyInput().
HandleSpeedModifiers()
void Engine::InputSystem::HandleSpeedModifiers (float & speed) const private
Definition at line 87 of file InputSystem.cpp.
References IsKeyPressed(), m_SlowMultiplier, and m_SprintMultiplier.
Referenced by HandleCameraMovement().
IsKeyPressed()
bool Engine::InputSystem::IsKeyPressed (int keycode) const
Checks if a key is currently pressed.
Parameters
keycode GLFW key code to check
Returns
true if key is pressed
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 182 of file InputSystem.cpp.
References Engine::Window::GetNativeWindow(), and m_Window.
Referenced by HandleCameraMovement(), HandleKeyInput(), HandleSensitivityAdjustment(), HandleSpeedModifiers(), and Engine::LuaScriptSystem::RegisterEngineAPI().
IsMouseButtonPressed()
bool Engine::InputSystem::IsMouseButtonPressed (int button) const
Checks if a mouse button is currently pressed.
Parameters
button GLFW mouse button code to check
Returns
true if button is pressed
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 187 of file InputSystem.cpp.
References Engine::Window::GetNativeWindow(), and m_Window.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
OnEvent()
void Engine::InputSystem::OnEvent (Event & e)
Processes input events.
Parameters
e Event to process
Definition at line 152 of file InputSystem.cpp.
References Engine::Event::GetEventType(), HandleMouseMovement(), and Engine::MouseMoved.
OnKey()
void Engine::InputSystem::OnKey (int key, int scancode, int action, int mods)
Handles key press events for the input system.
Processes registered key callbacks and manages built-in key actions, specifically toggling cursor lock when the ESC key is pressed.
Parameters
key The GLFW key code of the pressed/released key
scancode System-specific scancode of the key
action Key action (GLFW_PRESS, GLFW_RELEASE, or GLFW_REPEAT)
mods Bit field describing which modifier keys were held down
Note
First invokes any registered key callbacks, then handles specific built-in actions like ESC key cursor lock toggling
Definition at line 249 of file InputSystem.cpp.
References m_CursorLocked, OnKeyEvent(), and UpdateCursorState().
OnKeyEvent()
void Engine::InputSystem::OnKeyEvent (int key, int action) private
Executes a registered callback for a specific key event.
Checks if a callback is registered for the given key and invokes it with the current action. This method allows custom handling of key events through pre-registered callbacks.
Parameters
key The GLFW key code for which the event is being processed.
action The action performed on the key (e.g., GLFW_PRESS, GLFW_RELEASE, GLFW_REPEAT).
Definition at line 269 of file InputSystem.cpp.
References m_KeyCallbacks.
Referenced by OnKey().
RegisterKeyCallback()
void Engine::InputSystem::RegisterKeyCallback (int key, KeyCallback callback)
Registers a custom callback function for a specific key event.
Parameters
key The GLFW key code for which the callback is being registered.
callback A function to be called when the specified key is pressed or released.
This method allows dynamic registration of custom key event handlers. The callback will be stored in the internal key callbacks map and can be triggered during key events. Registering a new callback for an existing key will replace the previous callback.
Note
The callback is moved into the map to avoid unnecessary copying.
Definition at line 231 of file InputSystem.cpp.
References m_KeyCallbacks.
SetMovementSpeed()
void Engine::InputSystem::SetMovementSpeed (float speed) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 71 of file InputSystem.h.
References m_MovementSpeed.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SetSensitivity()
void Engine::InputSystem::SetSensitivity (float sensitivity) inline
Sets mouse sensitivity.
Parameters
sensitivity New sensitivity value
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 63 of file InputSystem.h.
References m_MouseSensitivity.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SmoothDamp()
void Engine::InputSystem::SmoothDamp (glm::vec3 & current, const glm::vec3 & target, glm::vec3 & velocity, float smoothTime, float deltaTime) private
Definition at line 139 of file InputSystem.cpp.
Referenced by HandleCameraMovement().
ToggleCameraControls()
void Engine::InputSystem::ToggleCameraControls () inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 69 of file InputSystem.h.
References m_CameraEnabled.
Referenced by HandleKeyInput(), and Engine::LuaScriptSystem::RegisterEngineAPI().
ToggleMovementLock()
void Engine::InputSystem::ToggleMovementLock () inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 73 of file InputSystem.h.
References m_MovementLocked.
Referenced by HandleKeyInput(), and Engine::LuaScriptSystem::RegisterEngineAPI().
ToggleSmoothCamera()
void Engine::InputSystem::ToggleSmoothCamera () inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 70 of file InputSystem.h.
References m_SmoothCamera.
Referenced by HandleKeyInput(), and Engine::LuaScriptSystem::RegisterEngineAPI().
Update()
void Engine::InputSystem::Update (float deltaTime)
Updates input state and handles continuous input.
Parameters
deltaTime Time elapsed since last update
Definition at line 30 of file InputSystem.cpp.
References FIXED_TIMESTEP, HandleCameraMovement(), HandleKeyInput(), and m_MovementAccumulator.
UpdateCursorState()
void Engine::InputSystem::UpdateCursorState () private
Updates cursor visibility and lock state.
Updates the cursor state in the window based on the current cursor lock status.
This method changes the cursor display mode using GLFW:
When cursor is locked (m_CursorLocked is true), the cursor is disabled and hidden
When cursor is unlocked, the cursor is set to normal mode and becomes visible
Note
Uses the native window handle obtained from the window object
Utilizes GLFW's input mode settings to control cursor visibility and behavior
Definition at line 209 of file InputSystem.cpp.
References Engine::Window::GetNativeWindow(), m_CursorLocked, and m_Window.
Referenced by HandleKeyInput(), InputSystem(), and OnKey().
Member Data Documentation
FIXED_TIMESTEP
const float Engine::InputSystem::FIXED_TIMESTEP = 1.0f / 60.0f private
60Hz update rate
Definition at line 114 of file InputSystem.h.
Referenced by Update().
m_CameraEnabled
bool Engine::InputSystem::m_CameraEnabled = true private
Toggle for camera controls.
Definition at line 110 of file InputSystem.h.
Referenced by HandleCameraMovement(), HandleMouseMovement(), and ToggleCameraControls().
m_CurrentVelocity
glm::vec3 Engine::InputSystem::m_CurrentVelocity {0.0f} private
Current velocity for smooth damping.
Definition at line 124 of file InputSystem.h.
Referenced by HandleCameraMovement().
m_CursorLocked
bool Engine::InputSystem::m_CursorLocked = false private
Is cursor locked to window center.
Definition at line 140 of file InputSystem.h.
Referenced by HandleKeyInput(), InputSystem(), OnKey(), and UpdateCursorState().
m_FirstMouse
bool Engine::InputSystem::m_FirstMouse = true private
First mouse input flag.
Definition at line 104 of file InputSystem.h.
Referenced by HandleMouseMovement().
m_KeyCallbacks
std::unordered_map<int, KeyCallback> Engine::InputSystem::m_KeyCallbacks private
Definition at line 146 of file InputSystem.h.
Referenced by OnKeyEvent(), and RegisterKeyCallback().
m_LastBPressed
bool Engine::InputSystem::m_LastBPressed = false private
Previous frame B key state.
Definition at line 135 of file InputSystem.h.
Referenced by HandleKeyInput().
m_LastEscPressed
bool Engine::InputSystem::m_LastEscPressed = false private
Previous frame ESC key state.
Definition at line 137 of file InputSystem.h.
Referenced by HandleKeyInput().
m_LastMouseX
float Engine::InputSystem::m_LastMouseX = 0.0f private
Last mouse X position.
Definition at line 105 of file InputSystem.h.
Referenced by HandleMouseMovement().
m_LastMouseY
float Engine::InputSystem::m_LastMouseY = 0.0f private
Last mouse Y position.
Definition at line 106 of file InputSystem.h.
Referenced by HandleMouseMovement().
m_LastVPressed
bool Engine::InputSystem::m_LastVPressed = false private
Previous frame V key state.
Definition at line 134 of file InputSystem.h.
Referenced by HandleKeyInput().
m_MouseSensitivity
float Engine::InputSystem::m_MouseSensitivity = 0.1f private
Mouse movement sensitivity.
Definition at line 107 of file InputSystem.h.
Referenced by GetSensitivity(), HandleMouseMovement(), HandleSensitivityAdjustment(), and SetSensitivity().
m_MovementAccumulator
float Engine::InputSystem::m_MovementAccumulator = 0.0f private
Time accumulator for movement updates.
Definition at line 115 of file InputSystem.h.
Referenced by Update().
m_MovementLocked
bool Engine::InputSystem::m_MovementLocked = false private
Global movement lock flag.
Definition at line 136 of file InputSystem.h.
Referenced by HandleCameraMovement(), HandleMouseMovement(), and ToggleMovementLock().
m_MovementSpeed
float Engine::InputSystem::m_MovementSpeed = 250.0f private
Base movement speed (blocks per second)
Definition at line 118 of file InputSystem.h.
Referenced by GetMovementSpeed(), HandleCameraMovement(), and SetMovementSpeed().
m_Renderer
Renderer& Engine::InputSystem::m_Renderer private
Reference to renderer.
Definition at line 102 of file InputSystem.h.
Referenced by HandleCameraMovement(), HandleKeyInput(), and HandleMouseMovement().
m_SlowMultiplier
float Engine::InputSystem::m_SlowMultiplier = 1.0f private
Slow movement multiplier.
Definition at line 120 of file InputSystem.h.
Referenced by HandleSpeedModifiers().
m_SmoothCamera
bool Engine::InputSystem::m_SmoothCamera = true private
Toggle for smooth camera movement.
Definition at line 111 of file InputSystem.h.
Referenced by HandleCameraMovement(), and ToggleSmoothCamera().
m_SmoothTime
float Engine::InputSystem::m_SmoothTime = 0.1f private
Smoothing time factor.
Definition at line 125 of file InputSystem.h.
Referenced by HandleCameraMovement().
m_SprintMultiplier
float Engine::InputSystem::m_SprintMultiplier = 2.0f private
Sprint speed multiplier.
Definition at line 119 of file InputSystem.h.
Referenced by HandleSpeedModifiers().
m_TargetPosition
glm::vec3 Engine::InputSystem::m_TargetPosition {0.0f} private
Target position for smooth movement.
Definition at line 123 of file InputSystem.h.
Referenced by HandleCameraMovement().
m_Window
Window* Engine::InputSystem::m_Window private
Pointer to application window.
Definition at line 101 of file InputSystem.h.
Referenced by GetMousePosition(), InputSystem(), IsKeyPressed(), IsMouseButtonPressed(), and UpdateCursorState().
The documentation for this class was generated from the following files:
src/Input/InputSystem.h
src/Input/InputSystem.cpp