Voxel Engine: Engine::ImGuiLayer Class Reference
Engine::ImGuiLayer Class Reference
Manages Dear ImGui integration with the application.
#include <ImGuiLayer.h>
Public Member Functions
ImGuiLayer ()=default
ImGuiLayer (Window *window)
~ImGuiLayer ()=default
void Init (Window *window)
Initializes ImGui context and bindings.
void Shutdown ()
Cleans up ImGui resources.
void Begin ()
Begins a new ImGui frame.
void End ()
Ends the current ImGui frame and renders.
void BlockEvents (bool block)
Controls whether ImGui should block events from reaching the application.
bool AreEventsBlocked () const
Private Attributes
bool m_BlockEvents = true
Whether ImGui should block events.
Window * m_Window = nullptr
Pointer to the application window.
Detailed Description
Manages Dear ImGui integration with the application.
Handles initialization, shutdown, and frame-by-frame rendering of Dear ImGui interface elements.
Definition at line 12 of file ImGuiLayer.h.
Constructor & Destructor Documentation
ImGuiLayer() [1/2]
Engine::ImGuiLayer::ImGuiLayer () default
ImGuiLayer() [2/2]
Engine::ImGuiLayer::ImGuiLayer (Window * window)
Definition at line 13 of file ImGuiLayer.cpp.
~ImGuiLayer()
Engine::ImGuiLayer::~ImGuiLayer () default
Member Function Documentation
AreEventsBlocked()
bool Engine::ImGuiLayer::AreEventsBlocked () const inline
Returns
Whether ImGui is currently blocking events
Definition at line 40 of file ImGuiLayer.h.
References m_BlockEvents.
Begin()
void Engine::ImGuiLayer::Begin ()
Begins a new ImGui frame.
Definition at line 90 of file ImGuiLayer.cpp.
BlockEvents()
void Engine::ImGuiLayer::BlockEvents (bool block) inline
Controls whether ImGui should block events from reaching the application.
Parameters
block True to block events, false to pass them through
Definition at line 37 of file ImGuiLayer.h.
References m_BlockEvents.
End()
void Engine::ImGuiLayer::End ()
Ends the current ImGui frame and renders.
Definition at line 96 of file ImGuiLayer.cpp.
References Engine::Window::GetHeight(), Engine::Window::GetWidth(), and m_Window.
Init()
void Engine::ImGuiLayer::Init (Window * window)
Initializes ImGui context and bindings.
Initializes the ImGui layer for the application window.
Parameters
window Pointer to the application window
window Pointer to the application window used for rendering.
This method sets up the ImGui context, configures rendering options, and initializes platform-specific backends for GLFW and OpenGL. It performs the following key tasks:
Creates an ImGui context
Enables keyboard navigation and docking
Configures viewport support based on the operating system
Sets up a dark color style
Initializes GLFW and OpenGL rendering backends
Note
Platform-specific behavior:
On Linux, viewports are disabled
On other platforms, viewports are enabled
Warning
Requires a valid Window pointer and working OpenGL context
Definition at line 35 of file ImGuiLayer.cpp.
References Engine::Window::GetNativeWindow(), LOG_TRACE, and m_Window.
Shutdown()
void Engine::ImGuiLayer::Shutdown ()
Cleans up ImGui resources.
Shuts down the ImGui rendering context and associated backends.
This method performs cleanup operations for the ImGui library, including:
Shutting down the OpenGL 3 backend
Shutting down the GLFW backend
Destroying the ImGui context
Note
Logs an informational message upon successful shutdown.
Definition at line 82 of file ImGuiLayer.cpp.
References LOG_INFO.
Member Data Documentation
m_BlockEvents
bool Engine::ImGuiLayer::m_BlockEvents = true private
Whether ImGui should block events.
Definition at line 43 of file ImGuiLayer.h.
Referenced by AreEventsBlocked(), and BlockEvents().
m_Window
Window* Engine::ImGuiLayer::m_Window = nullptr private
Pointer to the application window.
Definition at line 44 of file ImGuiLayer.h.
Referenced by End(), and Init().
The documentation for this class was generated from the following files:
src/ImGui/ImGuiLayer.h
src/ImGui/ImGuiLayer.cpp