Voxel Engine: VoidNoise Class Reference
VoidNoise Class Reference
Perlin noise implementation for terrain generation.
#include <VoidNoise.h>
Public Member Functions
VoidNoise (unsigned int seed=1234)
Construct a new Void Noise generator.
float noise (float x, float y) const override
Generate 2D noise value at given coordinates.
std::vector< float > generateHeightmap (int width, int height, float scale=1.0f) const override
Generate a heightmap using multiple octaves of noise.
Public Member Functions inherited from INoiseGenerator
virtual ~INoiseGenerator ()=default
Private Member Functions
float fade (float t) const
Smoothstep function for noise interpolation.
float lerp (float a, float b, float t) const
Linear interpolation between two values.
float grad (int hash, float x, float y) const
Generate gradient value for noise.
Private Attributes
std::mt19937 rng
std::array< int, PERM_SIZE *2 > perm
Static Private Attributes
static const int PERM_SIZE = 256
Detailed Description
Perlin noise implementation for terrain generation.
Provides methods for generating coherent noise and heightmaps
Definition at line 10 of file VoidNoise.h.
Constructor & Destructor Documentation
VoidNoise()
VoidNoise::VoidNoise (unsigned int seed = 1234)
Construct a new Void Noise generator.
Initialize the Perlin noise generator.
Parameters
seed Random seed value for noise generation
Definition at line 8 of file VoidNoise.cpp.
References perm, PERM_SIZE, and rng.
Member Function Documentation
fade()
float VoidNoise::fade (float t) const private
Smoothstep function for noise interpolation.
Apply smoothstep function for noise interpolation.
Parameters
t Value to fade
Returns
float Smoothed value
Parameters
t Input value to be smoothed (0-1)
Returns
Smoothed value
Definition at line 27 of file VoidNoise.cpp.
Referenced by noise().
generateHeightmap()
std::vector< float > VoidNoise::generateHeightmap (int width, int height, float scale = 1.0f) const override virtual
Generate a heightmap using multiple octaves of noise.
Parameters
width Width of the heightmap
height Height of the heightmap
scale Scale factor for noise coordinates
Returns
std::vector<float> Generated heightmap values
Parameters
width Width of the heightmap
height Height of the heightmap
scale Scale factor for noise coordinates
Returns
Vector containing heightmap values
Implements INoiseGenerator.
Definition at line 111 of file VoidNoise.cpp.
References LOG_TRACE_CONCAT, and noise().
grad()
float VoidNoise::grad (int hash, float x, float y) const private
Generate gradient value for noise.
Generate gradient value for noise calculation.
Parameters
hash Hash value
x X coordinate
y Y coordinate
Returns
float Gradient value
Parameters
hash Hash value for pseudo-random direction
x X coordinate
y Y coordinate
Returns
Gradient value
Definition at line 49 of file VoidNoise.cpp.
lerp()
float VoidNoise::lerp (float a, float b, float t) const private
Linear interpolation between two values.
Parameters
a First value
b Second value
t Interpolation factor (0-1)
Returns
float Interpolated value
Parameters
a First value
b Second value
t Interpolation factor (0-1)
Returns
Interpolated value
Definition at line 38 of file VoidNoise.cpp.
Referenced by noise().
noise()
float VoidNoise::noise (float x, float y) const override virtual
Generate 2D noise value at given coordinates.
Generate 2D Perlin noise value.
Parameters
x X coordinate
y Y coordinate
Returns
float Noise value between 0 and 1
Parameters
x X coordinate in noise space
y Y coordinate in noise space
Returns
Noise value between 0 and 1
Implements INoiseGenerator.
Definition at line 62 of file VoidNoise.cpp.
References fade(), lerp(), LOG_TRACE_CONCAT, and perm.
Referenced by VoxelChunk::generate(), generateHeightmap(), and VoxelTerrain::SaveHeightmapDebug().
Member Data Documentation
perm
std::array<int, PERM_SIZE * 2> VoidNoise::perm private
Definition at line 38 of file VoidNoise.h.
Referenced by noise(), and VoidNoise().
PERM_SIZE
const int VoidNoise::PERM_SIZE = 256 static private
Definition at line 36 of file VoidNoise.h.
Referenced by VoidNoise().
rng
std::mt19937 VoidNoise::rng mutable private
Definition at line 37 of file VoidNoise.h.
Referenced by VoidNoise().
The documentation for this class was generated from the following files:
src/Noise/VoidNoise/VoidNoise.h
src/Noise/VoidNoise/VoidNoise.cpp