Voxel Engine: Engine::Profiler::SmallVector< T, N > Class Template Reference
Engine::Profiler::SmallVector< T, N > Class Template Reference
Public Member Functions
void push_back (const T &value)
void clear ()
T * begin ()
T * end ()
const T * begin () const
const T * end () const
bool empty () const
size_t size () const
operator std::vector< T > () const
void reserve (size_t newCap)
void moveToHeap ()
T & back ()
const T & back () const
void set_back (const T &value)
T & operator[] (size_t index)
const T & operator[] (size_t index) const
Private Attributes
unsigned char inlineData [N *sizeof(T)]
std::vector< T > heap
T * data {reinterpret_cast<T*>(inlineData)}
size_t size_ {0}
bool isInline {true}
Detailed Description
template<typename T, size_t N>
class Engine::Profiler::SmallVector< T, N >
Definition at line 222 of file Profiler.h.
Member Function Documentation
back() [1/2]
template<typename T , size_t N> T & Engine::Profiler::SmallVector< T, N >::back () inline
Definition at line 285 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
back() [2/2]
template<typename T , size_t N> const T & Engine::Profiler::SmallVector< T, N >::back () const inline
Definition at line 286 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
begin() [1/2]
template<typename T , size_t N> T * Engine::Profiler::SmallVector< T, N >::begin () inline
Definition at line 255 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, and Engine::Profiler::SmallVector< T, N >::isInline.
Referenced by Engine::Profiler::ProfileData::AddSample(), and Engine::Profiler::ProfileData::begin().
begin() [2/2]
template<typename T , size_t N> const T * Engine::Profiler::SmallVector< T, N >::begin () const inline
Definition at line 257 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, and Engine::Profiler::SmallVector< T, N >::isInline.
clear()
template<typename T , size_t N> void Engine::Profiler::SmallVector< T, N >::clear () inline
Definition at line 244 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
empty()
template<typename T , size_t N> bool Engine::Profiler::SmallVector< T, N >::empty () const inline
Definition at line 259 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::empty().
end() [1/2]
template<typename T , size_t N> T * Engine::Profiler::SmallVector< T, N >::end () inline
Definition at line 256 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::AddSample(), and Engine::Profiler::ProfileData::end().
end() [2/2]
template<typename T , size_t N> const T * Engine::Profiler::SmallVector< T, N >::end () const inline
Definition at line 258 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
moveToHeap()
template<typename T , size_t N> void Engine::Profiler::SmallVector< T, N >::moveToHeap () inline
Definition at line 278 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::AddSample().
operator std::vector< T >()
template<typename T , size_t N> Engine::Profiler::SmallVector< T, N >::operator std::vector< T > () const inline
Definition at line 262 of file Profiler.h.
operator[]() [1/2]
template<typename T , size_t N> T & Engine::Profiler::SmallVector< T, N >::operator[] (size_t index) inline
Definition at line 298 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, and Engine::Profiler::SmallVector< T, N >::isInline.
operator[]() [2/2]
template<typename T , size_t N> const T & Engine::Profiler::SmallVector< T, N >::operator[] (size_t index) const inline
Definition at line 305 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, and Engine::Profiler::SmallVector< T, N >::isInline.
push_back()
template<typename T , size_t N> void Engine::Profiler::SmallVector< T, N >::push_back (const T & value) inline
Definition at line 230 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::INITIAL_VECTOR_CAPACITY, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::AddSample().
reserve()
template<typename T , size_t N> void Engine::Profiler::SmallVector< T, N >::reserve (size_t newCap) inline
Definition at line 270 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::heap, and Engine::Profiler::SmallVector< T, N >::isInline.
set_back()
template<typename T , size_t N> void Engine::Profiler::SmallVector< T, N >::set_back (const T & value) inline
Definition at line 289 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::data, Engine::Profiler::SmallVector< T, N >::heap, Engine::Profiler::SmallVector< T, N >::isInline, and Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::AddSample().
size()
template<typename T , size_t N> size_t Engine::Profiler::SmallVector< T, N >::size () const inline
Definition at line 260 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::size_.
Referenced by Engine::Profiler::ProfileData::AddSample(), and Engine::Profiler::ProfileData::size().
Member Data Documentation
data
template<typename T , size_t N> T* Engine::Profiler::SmallVector< T, N >::data {reinterpret_cast<T*>(inlineData)} private
Definition at line 225 of file Profiler.h.
Referenced by Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::clear(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::moveToHeap(), Engine::Profiler::SmallVector< float, SMALL_VECTOR_SIZE >::operator std::vector< float >(), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::push_back(), and Engine::Profiler::SmallVector< T, N >::set_back().
heap
template<typename T , size_t N> std::vector<T> Engine::Profiler::SmallVector< T, N >::heap private
Definition at line 224 of file Profiler.h.
Referenced by Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::clear(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::moveToHeap(), Engine::Profiler::SmallVector< float, SMALL_VECTOR_SIZE >::operator std::vector< float >(), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::push_back(), Engine::Profiler::SmallVector< T, N >::reserve(), and Engine::Profiler::SmallVector< T, N >::set_back().
inlineData
template<typename T , size_t N> unsigned char Engine::Profiler::SmallVector< T, N >::inlineData[N *sizeof(T)] private
Definition at line 223 of file Profiler.h.
isInline
template<typename T , size_t N> bool Engine::Profiler::SmallVector< T, N >::isInline {true} private
Definition at line 227 of file Profiler.h.
Referenced by Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::begin(), Engine::Profiler::SmallVector< T, N >::clear(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::moveToHeap(), Engine::Profiler::SmallVector< float, SMALL_VECTOR_SIZE >::operator std::vector< float >(), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::operator[](), Engine::Profiler::SmallVector< T, N >::push_back(), Engine::Profiler::SmallVector< T, N >::reserve(), and Engine::Profiler::SmallVector< T, N >::set_back().
size_
template<typename T , size_t N> size_t Engine::Profiler::SmallVector< T, N >::size_ {0} private
Definition at line 226 of file Profiler.h.
Referenced by Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::back(), Engine::Profiler::SmallVector< T, N >::clear(), Engine::Profiler::SmallVector< T, N >::empty(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::end(), Engine::Profiler::SmallVector< T, N >::moveToHeap(), Engine::Profiler::SmallVector< float, SMALL_VECTOR_SIZE >::operator std::vector< float >(), Engine::Profiler::SmallVector< T, N >::push_back(), Engine::Profiler::SmallVector< T, N >::set_back(), and Engine::Profiler::SmallVector< T, N >::size().
The documentation for this class was generated from the following file:
src/Debug/Profiler.h