Voxel Engine: Engine::Transform Class Reference
Engine::Transform Class Reference
#include <Transform.h>
Classes
struct TransformData
Public Member Functions
Transform ()=default
TransformData & GetData ()
const TransformData & GetData () const
void SetPosition (float x, float y, float z)
void SetPosition (const glm::vec3 &position)
glm::vec3 GetPosition () const
void SetRotation (float x, float y, float z)
void SetRotation (const glm::vec3 &rotation)
glm::vec3 GetRotation () const
void SetScale (float x, float y, float z)
void SetScale (const glm::vec3 &scale)
glm::vec3 GetScale () const
glm::mat4 GetModelMatrix () const
Private Attributes
TransformData m_Data
Detailed Description
Definition at line 5 of file Transform.h.
Constructor & Destructor Documentation
Transform()
Engine::Transform::Transform () default
Member Function Documentation
GetData() [1/2]
TransformData & Engine::Transform::GetData () inline
Definition at line 15 of file Transform.h.
References m_Data.
GetData() [2/2]
const TransformData & Engine::Transform::GetData () const inline
Definition at line 16 of file Transform.h.
References m_Data.
GetModelMatrix()
glm::mat4 Engine::Transform::GetModelMatrix () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 34 of file Transform.h.
References m_Data, Engine::Transform::TransformData::position, Engine::Transform::TransformData::rotation, and Engine::Transform::TransformData::scale.
Referenced by Engine::SceneObject::GetWorldTransform(), Engine::SceneObject::OnRender(), Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::TerrainSystem::Render().
GetPosition()
glm::vec3 Engine::Transform::GetPosition () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 21 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::position.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::TerrainSystem::Update().
GetRotation()
glm::vec3 Engine::Transform::GetRotation () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 26 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::rotation.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetScale()
glm::vec3 Engine::Transform::GetScale () const inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 31 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::scale.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::TerrainSystem::Update().
SetPosition() [1/2]
void Engine::Transform::SetPosition (const glm::vec3 & position) inline
Definition at line 20 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::position.
SetPosition() [2/2]
void Engine::Transform::SetPosition (float x, float y, float z) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 19 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::position.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::TerrainSystem::TerrainSystem().
SetRotation() [1/2]
void Engine::Transform::SetRotation (const glm::vec3 & rotation) inline
Definition at line 25 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::rotation.
SetRotation() [2/2]
void Engine::Transform::SetRotation (float x, float y, float z) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 24 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::rotation.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
SetScale() [1/2]
void Engine::Transform::SetScale (const glm::vec3 & scale) inline
Definition at line 30 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::scale.
SetScale() [2/2]
void Engine::Transform::SetScale (float x, float y, float z) inline
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 29 of file Transform.h.
References m_Data, and Engine::Transform::TransformData::scale.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI(), and Engine::TerrainSystem::TerrainSystem().
Member Data Documentation
m_Data
TransformData Engine::Transform::m_Data private
Definition at line 49 of file Transform.h.
Referenced by GetData(), GetData(), GetModelMatrix(), GetPosition(), GetRotation(), GetScale(), SetPosition(), SetPosition(), SetRotation(), SetRotation(), SetScale(), and SetScale().
The documentation for this class was generated from the following file:
src/Core/Transform.h