Voxel Engine: Engine::ImGuiOverlay Class Reference
Engine::ImGuiOverlay Class Reference
ImGui-based overlay for debug and control interfaces.
#include <ImGuiOverlay.h>
Public Member Functions
ImGuiOverlay (Window *window)
Constructs the ImGui overlay.
~ImGuiOverlay ()=default
void OnRender (RenderObject &renderObject, bool showFPSCounter, float currentFPS, float averageFPS, float frameTime, float fps1PercentLow, float fps1PercentHigh)
Renders performance statistics overlay.
void RenderTransformControls (RenderObject &renderObject)
Renders transform manipulation controls.
void RenderProfiler () const
Renders profiler information window.
void RenderRendererSettings ()
Renders renderer settings panel.
void RenderEventDebugger ()
Renders event debugging window.
void RenderTerrainControls ()
Renders terrain generation controls.
void ShowTransformControls (bool show)
void ShowProfiler (bool show)
void ShowRendererSettings (bool show)
void ShowEventDebugger (bool show)
void ShowTerrainControls (bool show)
void ShowFPSCounter (bool show)
Private Attributes
Window * m_Window
Pointer to application window.
Renderer * m_Renderer
Pointer to renderer.
bool m_ShowEventDebugger = true
Event debugger visibility flag.
FPSCounter m_FPSCounter
FPS counter.
ImGuiWidgetFlameGraph::FlameGraphSettings m_FlameGraphSettings
Flame graph settings.
bool m_ShowTransformControls = true
bool m_ShowProfiler = true
bool m_ShowRendererSettings = true
bool m_ShowTerrainControls = true
bool m_ShowFPSCounter = true
Detailed Description
ImGui-based overlay for debug and control interfaces.
Provides various debug windows and control panels for the engine, including performance metrics, transform controls, and debug info.
Definition at line 20 of file ImGuiOverlay.h.
Constructor & Destructor Documentation
ImGuiOverlay()
Engine::ImGuiOverlay::ImGuiOverlay (Window * window)
Constructs the ImGui overlay.
Constructor for ImGui overlay.
Parameters
window Pointer to the application window
window Pointer to the window instance
Definition at line 16 of file ImGuiOverlay.cpp.
References m_FlameGraphSettings.
~ImGuiOverlay()
Engine::ImGuiOverlay::~ImGuiOverlay () default
Member Function Documentation
OnRender()
void Engine::ImGuiOverlay::OnRender (RenderObject & renderObject, bool showFPSCounter, float currentFPS, float averageFPS, float frameTime, float fps1PercentLow, float fps1PercentHigh)
Renders performance statistics overlay.
Renders performance statistics overlay with detailed FPS and frame time information.
Parameters
renderObject Current render object
showFPSCounter Whether to show FPS counter
currentFPS Current frames per second
averageFPS Average frames per second
frameTime Time taken for last frame
fps1PercentLow 1% low FPS value
fps1PercentHigh 1% high FPS value
Displays a window in the top-right corner of the screen showing current performance metrics, including current and average FPS, frame time, 1% low and high FPS values. Provides interactive controls for VSync and flame graph visualization.
Parameters
renderObject The render object context (currently unused in implementation)
showFPSCounter Flag to control visibility of the FPS counter
currentFPS Instantaneous frames per second for the current frame
averageFPS Rolling average of frames per second
frameTime Duration of the last frame in seconds
fps1PercentLow 1% low performance frame rate
fps1PercentHigh 1% high performance frame rate
Note
The overlay can be toggled using the F3 key
Includes interactive VSync toggle and flame graph with configurable settings
Definition at line 40 of file ImGuiOverlay.cpp.
References ImGuiWidgetFlameGraph::FlameGraphSettings::enableZoom, Engine::Renderer::GetCameraType(), Engine::FPSCounter::GetFrameTimeHistory(), Engine::Window::IsVSync(), m_FlameGraphSettings, m_FPSCounter, m_Renderer, m_ShowFPSCounter, m_Window, Engine::Renderer::Orthographic, ImGuiWidgetFlameGraph::FlameGraphSettings::panOffset, ImGuiWidgetFlameGraph::PlotFlame(), Engine::Window::SetVSync(), ImGuiWidgetFlameGraph::FlameGraphSettings::showAverage, ImGuiWidgetFlameGraph::FlameGraphSettings::showTargetFPS, ImGuiWidgetFlameGraph::FlameGraphSettings::targetFPS, Engine::FPSCounter::Update(), and ImGuiWidgetFlameGraph::FlameGraphSettings::zoomLevel.
RenderEventDebugger()
void Engine::ImGuiOverlay::RenderEventDebugger ()
Renders event debugging window.
Renders a window displaying recent events with detailed information.
Displays a debug window showing the last 5 events in the event history. Each event can be expanded to reveal additional details such as:
Event name and time since occurrence
Event priority (High, Normal, Low)
Handled status
Detailed debug information
The events are color-coded based on their recency, with recently occurred events highlighted in green. If no events have been recorded, a placeholder message is shown.
Note
The window is only rendered if m_ShowEventDebugger is true
Uses ImGui for rendering the event debug interface
Definition at line 265 of file ImGuiOverlay.cpp.
References Engine::EventDebugger::Get(), Engine::EventDebugger::GetEventHistory(), Engine::High, m_ShowEventDebugger, and Engine::Normal.
RenderProfiler()
void Engine::ImGuiOverlay::RenderProfiler () const
Renders profiler information window.
Renders a comprehensive profiler window for performance metrics and analysis.
This method displays a window that allows users to control and view profiling information. Features include:
Enabling/disabling profiling
Clearing existing profiling data
Configuring number of frames to profile
Displaying detailed performance statistics for each profiled function
Note
The window is only rendered if m_ShowProfiler is true
Profiling data includes average, minimum, maximum execution times, and number of calls
Definition at line 166 of file ImGuiOverlay.cpp.
References Engine::Profiler::BeginSession(), Engine::Profiler::ClearProfiles(), Engine::Profiler::Get(), Engine::Profiler::GetProfiles(), Engine::Profiler::IsEnabled(), m_ShowProfiler, Engine::Profiler::ProfileFrames(), and Engine::Profiler::SetEnabled().
RenderRendererSettings()
void Engine::ImGuiOverlay::RenderRendererSettings ()
Renders renderer settings panel.
Renders the renderer settings window with back-face culling controls.
Provides an interactive ImGui window to toggle back-face culling in OpenGL. When enabled, back-face culling is set to cull back faces with counter-clockwise winding order. The current culling state is retrieved and can be modified through a checkbox.
Note
The window is only rendered if m_ShowRendererSettings is true
Precondition
OpenGL context must be initialized
Postcondition
OpenGL culling state may be modified based on user interaction
Definition at line 233 of file ImGuiOverlay.cpp.
References m_ShowRendererSettings.
RenderTerrainControls()
void Engine::ImGuiOverlay::RenderTerrainControls ()
Renders terrain generation controls.
Renders interactive controls for terrain generation and modification.
Provides a comprehensive ImGui window for adjusting terrain generation parameters. Allows users to:
Modify chunk rendering range
Regenerate terrain with a specific seed
Adjust terrain parameters like base height, height scale, and noise scale
Toggle automatic parameter updates
Note
Requires an active scene with a valid terrain system
Uses static variables to maintain parameter state between renders
Warning
Skips rendering if no active scene or terrain system is available
Definition at line 312 of file ImGuiOverlay.cpp.
References Engine::SceneManager::Get(), and Engine::SceneManager::GetActiveScene().
RenderTransformControls()
void Engine::ImGuiOverlay::RenderTransformControls (Engine::RenderObject & object)
Renders transform manipulation controls.
Renders interactive transform controls for a RenderObject.
Displays a window with drag controls for modifying an object's position, rotation, and scale. The window is only rendered if transform controls are enabled via m_ShowTransformControls.
Parameters
renderObject Reference to the RenderObject whose transform will be manipulated
Note
Controls use ImGui drag float widgets with a sensitivity of 0.1 units per drag
Position, rotation, and scale are modified directly on the object's transform
Definition at line 142 of file ImGuiOverlay.cpp.
ShowEventDebugger()
void Engine::ImGuiOverlay::ShowEventDebugger (bool show) inline
Definition at line 58 of file ImGuiOverlay.h.
References m_ShowEventDebugger.
ShowFPSCounter()
void Engine::ImGuiOverlay::ShowFPSCounter (bool show) inline
Definition at line 60 of file ImGuiOverlay.h.
References m_ShowFPSCounter.
ShowProfiler()
void Engine::ImGuiOverlay::ShowProfiler (bool show) inline
Definition at line 56 of file ImGuiOverlay.h.
References m_ShowProfiler.
ShowRendererSettings()
void Engine::ImGuiOverlay::ShowRendererSettings (bool show) inline
Definition at line 57 of file ImGuiOverlay.h.
References m_ShowRendererSettings.
ShowTerrainControls()
void Engine::ImGuiOverlay::ShowTerrainControls (bool show) inline
Definition at line 59 of file ImGuiOverlay.h.
References m_ShowTerrainControls.
ShowTransformControls()
void Engine::ImGuiOverlay::ShowTransformControls (bool show) inline
Definition at line 55 of file ImGuiOverlay.h.
References m_ShowTransformControls.
Member Data Documentation
m_FlameGraphSettings
ImGuiWidgetFlameGraph::FlameGraphSettings Engine::ImGuiOverlay::m_FlameGraphSettings private
Flame graph settings.
Definition at line 67 of file ImGuiOverlay.h.
Referenced by ImGuiOverlay(), and OnRender().
m_FPSCounter
FPSCounter Engine::ImGuiOverlay::m_FPSCounter private
FPS counter.
Definition at line 66 of file ImGuiOverlay.h.
Referenced by OnRender().
m_Renderer
Renderer* Engine::ImGuiOverlay::m_Renderer private
Pointer to renderer.
Definition at line 64 of file ImGuiOverlay.h.
Referenced by OnRender().
m_ShowEventDebugger
bool Engine::ImGuiOverlay::m_ShowEventDebugger = true private
Event debugger visibility flag.
Definition at line 65 of file ImGuiOverlay.h.
Referenced by RenderEventDebugger(), and ShowEventDebugger().
m_ShowFPSCounter
bool Engine::ImGuiOverlay::m_ShowFPSCounter = true private
Definition at line 72 of file ImGuiOverlay.h.
Referenced by OnRender(), and ShowFPSCounter().
m_ShowProfiler
bool Engine::ImGuiOverlay::m_ShowProfiler = true private
Definition at line 69 of file ImGuiOverlay.h.
Referenced by RenderProfiler(), and ShowProfiler().
m_ShowRendererSettings
bool Engine::ImGuiOverlay::m_ShowRendererSettings = true private
Definition at line 70 of file ImGuiOverlay.h.
Referenced by RenderRendererSettings(), and ShowRendererSettings().
m_ShowTerrainControls
bool Engine::ImGuiOverlay::m_ShowTerrainControls = true private
Definition at line 71 of file ImGuiOverlay.h.
Referenced by ShowTerrainControls().
m_ShowTransformControls
bool Engine::ImGuiOverlay::m_ShowTransformControls = true private
Definition at line 68 of file ImGuiOverlay.h.
Referenced by ShowTransformControls().
m_Window
Window* Engine::ImGuiOverlay::m_Window private
Pointer to application window.
Definition at line 63 of file ImGuiOverlay.h.
Referenced by OnRender().
The documentation for this class was generated from the following files:
src/UI/ImGuiOverlay.h
src/UI/ImGuiOverlay.cpp