Voxel Engine: SimplexNoise Class Reference
SimplexNoise Class Reference
#include <SimplexNoise.h>
Public Member Functions
SimplexNoise (unsigned int seed=1234)
~SimplexNoise () override=default
float noise (float x, float y) const override
Generate 2D noise value at given coordinates.
std::vector< float > generateHeightmap (int width, int height, float scale=1.0f) const override
Generate a heightmap using multiple octaves of noise.
Public Member Functions inherited from INoiseGenerator
virtual ~INoiseGenerator ()=default
Static Private Member Functions
static float grad (int hash, float x, float y)
static float dot2 (const float *grad, float x, float y)
Private Attributes
unsigned char perm [512]
Static Private Attributes
static const float F2 = 0.366025403784439f
static const float G2 = 0.211324865405187f
static const int gradients [12][2]
Detailed Description
Definition at line 5 of file SimplexNoise.h.
Constructor & Destructor Documentation
SimplexNoise()
SimplexNoise::SimplexNoise (unsigned int seed = 1234) explicit
Definition at line 14 of file SimplexNoise.cpp.
References perm.
~SimplexNoise()
SimplexNoise::~SimplexNoise () override default
Member Function Documentation
dot2()
float SimplexNoise::dot2 (const float * grad, float x, float y) static private
Definition at line 29 of file SimplexNoise.cpp.
References grad().
Referenced by grad().
generateHeightmap()
std::vector< float > SimplexNoise::generateHeightmap (int width, int height, float scale = 1.0f) const override virtual
Generate a heightmap using multiple octaves of noise.
Parameters
width Width of the heightmap
height Height of the heightmap
scale Scale factor for noise coordinates
Returns
std::vector<float> Generated heightmap values
Implements INoiseGenerator.
Definition at line 93 of file SimplexNoise.cpp.
References noise().
grad()
float SimplexNoise::grad (int hash, float x, float y) static private
Definition at line 33 of file SimplexNoise.cpp.
References dot2(), and gradients.
Referenced by dot2(), and noise().
noise()
float SimplexNoise::noise (float x, float y) const override virtual
Generate 2D noise value at given coordinates.
Parameters
x X coordinate
y Y coordinate
Returns
float Noise value between 0 and 1
Implements INoiseGenerator.
Definition at line 38 of file SimplexNoise.cpp.
References F2, G2, grad(), and perm.
Referenced by generateHeightmap().
Member Data Documentation
F2
const float SimplexNoise::F2 = 0.366025403784439f static private
Definition at line 18 of file SimplexNoise.h.
Referenced by noise().
G2
const float SimplexNoise::G2 = 0.211324865405187f static private
Definition at line 19 of file SimplexNoise.h.
Referenced by noise().
gradients
const int SimplexNoise::gradients static private
Initial value:
= {
    {1,1}, {-1,1}, {1,-1}, {-1,-1},
    {1,0}, {-1,0}, {1,0}, {-1,0},
    {0,1}, {0,-1}, {0,1}, {0,-1}
}
Definition at line 8 of file SimplexNoise.h.
Referenced by grad().
perm
unsigned char SimplexNoise::perm[512] private
Definition at line 17 of file SimplexNoise.h.
Referenced by noise(), and SimplexNoise().
The documentation for this class was generated from the following files:
src/Noise/SimplexNoise/SimplexNoise.h
src/Noise/SimplexNoise/SimplexNoise.cpp