Voxel Engine: PerlinNoise Class Reference
PerlinNoise Class Reference
#include <PerlinNoise.h>
Public Member Functions
PerlinNoise (unsigned int seed=1234)
float noise (float x, float y) const override
Generate 2D noise value at given coordinates.
std::vector< float > generateHeightmap (int width, int height, float scale=1.0f) const override
Generate a heightmap using multiple octaves of noise.
void setOctaves (int octaves)
void setPersistence (float persistence)
void setLacunarity (float lacunarity)
Public Member Functions inherited from INoiseGenerator
virtual ~INoiseGenerator ()=default
Private Member Functions
float fade (float t) const
float lerp (float a, float b, float t) const
float gradient (int hash, float x, float y) const
void generateGradients (unsigned int seed)
Private Attributes
std::array< int, PERM_SIZE *2 > p
std::array< glm::vec2, PERM_SIZE > gradients
int m_Octaves = 4
float m_Persistence = 0.5f
float m_Lacunarity = 2.0f
Static Private Attributes
static const int PERM_SIZE = 256
Detailed Description
Definition at line 7 of file PerlinNoise.h.
Constructor & Destructor Documentation
PerlinNoise()
PerlinNoise::PerlinNoise (unsigned int seed = 1234)
Definition at line 4 of file PerlinNoise.cpp.
References generateGradients(), p, and PERM_SIZE.
Member Function Documentation
fade()
float PerlinNoise::fade (float t) const private
Definition at line 32 of file PerlinNoise.cpp.
Referenced by noise().
generateGradients()
void PerlinNoise::generateGradients (unsigned int seed) private
Definition at line 20 of file PerlinNoise.cpp.
References gradient(), gradients, and PERM_SIZE.
Referenced by PerlinNoise().
generateHeightmap()
std::vector< float > PerlinNoise::generateHeightmap (int width, int height, float scale = 1.0f) const override virtual
Generate a heightmap using multiple octaves of noise.
Parameters
width Width of the heightmap
height Height of the heightmap
scale Scale factor for noise coordinates
Returns
std::vector<float> Generated heightmap values
Implements INoiseGenerator.
Definition at line 79 of file PerlinNoise.cpp.
References m_Lacunarity, m_Octaves, m_Persistence, and noise().
gradient()
float PerlinNoise::gradient (int hash, float x, float y) const private
Definition at line 40 of file PerlinNoise.cpp.
References gradients, and PERM_SIZE.
Referenced by generateGradients(), and noise().
lerp()
float PerlinNoise::lerp (float a, float b, float t) const private
Definition at line 36 of file PerlinNoise.cpp.
Referenced by noise().
noise()
float PerlinNoise::noise (float x, float y) const override virtual
Generate 2D noise value at given coordinates.
Parameters
x X coordinate
y Y coordinate
Returns
float Noise value between 0 and 1
Implements INoiseGenerator.
Definition at line 45 of file PerlinNoise.cpp.
References fade(), gradient(), lerp(), and p.
Referenced by generateHeightmap().
setLacunarity()
void PerlinNoise::setLacunarity (float lacunarity) inline
Definition at line 16 of file PerlinNoise.h.
References m_Lacunarity.
setOctaves()
void PerlinNoise::setOctaves (int octaves) inline
Definition at line 14 of file PerlinNoise.h.
References m_Octaves.
setPersistence()
void PerlinNoise::setPersistence (float persistence) inline
Definition at line 15 of file PerlinNoise.h.
References m_Persistence.
Member Data Documentation
gradients
std::array<glm::vec2, PERM_SIZE> PerlinNoise::gradients private
Definition at line 21 of file PerlinNoise.h.
Referenced by generateGradients(), and gradient().
m_Lacunarity
float PerlinNoise::m_Lacunarity = 2.0f private
Definition at line 25 of file PerlinNoise.h.
Referenced by generateHeightmap(), and setLacunarity().
m_Octaves
int PerlinNoise::m_Octaves = 4 private
Definition at line 23 of file PerlinNoise.h.
Referenced by generateHeightmap(), and setOctaves().
m_Persistence
float PerlinNoise::m_Persistence = 0.5f private
Definition at line 24 of file PerlinNoise.h.
Referenced by generateHeightmap(), and setPersistence().
p
std::array<int, PERM_SIZE * 2> PerlinNoise::p private
Definition at line 20 of file PerlinNoise.h.
Referenced by noise(), and PerlinNoise().
PERM_SIZE
const int PerlinNoise::PERM_SIZE = 256 static private
Definition at line 19 of file PerlinNoise.h.
Referenced by generateGradients(), gradient(), and PerlinNoise().
The documentation for this class was generated from the following files:
src/Noise/PerlinNoise/PerlinNoise.h
src/Noise/PerlinNoise/PerlinNoise.cpp