Voxel Engine: Engine::Window Class Reference
Engine::Window Class Reference abstract
Abstract window interface.
#include <Window.h>
Public Member Functions
virtual ~Window ()=default
virtual void OnUpdate ()=0
Updates window state.
virtual uint32_t GetWidth () const =0
virtual uint32_t GetHeight () const =0
virtual void SetVSync (bool enabled)=0
Sets vertical sync mode.
virtual bool IsVSync () const =0
virtual void SetClear (float a, float b, float c, float d)=0
Sets clear color.
virtual void SetContext ()=0
Sets rendering context.
virtual void CreateVBO ()=0
Creates vertex buffer object.
virtual void * GetNativeWindow () const =0
virtual void SetEventCallback (const EventCallbackFn &callback)=0
Sets event callback function.
Static Public Member Functions
static Window * Create (const WindowProps &props=WindowProps())
Creates platform-specific window.
Detailed Description
Abstract window interface.
Provides platform-independent window functionality
Definition at line 47 of file Window.h.
Constructor & Destructor Documentation
~Window()
virtual Engine::Window::~Window () virtual default
Member Function Documentation
Create()
Window * Engine::Window::Create (const WindowProps & props = WindowProps()) static
Creates platform-specific window.
Create a new Window instance.
Parameters
props Window properties
Returns
New window instance
Parameters
props Window properties for initialization
Returns
Pointer to created Window instance
Definition at line 16 of file OpenGLWindow.cpp.
Referenced by Engine::Application::InitWindow().
CreateVBO()
virtual void Engine::Window::CreateVBO () pure virtual
Creates vertex buffer object.
Implemented in Engine::OpenGLWindow.
GetHeight()
virtual uint32_t Engine::Window::GetHeight () const pure virtual
Returns
Window height
Implemented in Engine::OpenGLWindow.
Referenced by Engine::ImGuiLayer::End().
GetNativeWindow()
virtual void * Engine::Window::GetNativeWindow () const pure virtual
Returns
Native window handle
Implemented in Engine::OpenGLWindow.
Referenced by Engine::InputSystem::GetMousePosition(), Engine::ImGuiLayer::Init(), Engine::InputSystem::IsKeyPressed(), Engine::InputSystem::IsMouseButtonPressed(), and Engine::InputSystem::UpdateCursorState().
GetWidth()
virtual uint32_t Engine::Window::GetWidth () const pure virtual
Returns
Window width
Implemented in Engine::OpenGLWindow.
Referenced by Engine::ImGuiLayer::End().
IsVSync()
virtual bool Engine::Window::IsVSync () const pure virtual
Returns
Whether VSync is enabled
Implemented in Engine::OpenGLWindow.
Referenced by Engine::ImGuiOverlay::OnRender().
OnUpdate()
virtual void Engine::Window::OnUpdate () pure virtual
Updates window state.
Implemented in Engine::OpenGLWindow.
SetClear()
virtual void Engine::Window::SetClear (float a, float b, float c, float d) pure virtual
Sets clear color.
Implemented in Engine::OpenGLWindow.
SetContext()
virtual void Engine::Window::SetContext () pure virtual
Sets rendering context.
Implemented in Engine::OpenGLWindow.
SetEventCallback()
virtual void Engine::Window::SetEventCallback (const EventCallbackFn & callback) pure virtual
Sets event callback function.
Implemented in Engine::OpenGLWindow.
SetVSync()
virtual void Engine::Window::SetVSync (bool enabled) pure virtual
Sets vertical sync mode.
Implemented in Engine::OpenGLWindow.
Referenced by Engine::ImGuiOverlay::OnRender().
The documentation for this class was generated from the following files:
src/Window/Window.h
src/Window/OpenGLWindow.cpp