Voxel Engine: Engine::ShaderLibrary Class Reference
Engine::ShaderLibrary Class Reference
#include <ShaderLibrary.h>
Static Public Member Functions
static std::shared_ptr< Shader > Load (const std::string &name, const std::string &vertexPath, const std::string &fragmentPath)
static std::shared_ptr< Shader > LoadFromSource (const std::string &name, const std::string &vertexSrc, const std::string &fragmentSrc)
static std::shared_ptr< Shader > Get (const std::string &name)
static bool Exists (const std::string &name)
static std::shared_ptr< Shader > CreateBasicShader ()
static std::shared_ptr< Shader > CreateColorShader ()
static std::shared_ptr< Shader > CreateTextureShader ()
static std::shared_ptr< Shader > CreateBatchRenderer2DShader ()
static std::shared_ptr< Shader > LoadTexturedShader ()
Static Private Attributes
static std::unordered_map< std::string, std::shared_ptr< Shader > > s_Shaders
Detailed Description
Definition at line 9 of file ShaderLibrary.h.
Member Function Documentation
CreateBasicShader()
std::shared_ptr< Shader > Engine::ShaderLibrary::CreateBasicShader () static
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 10 of file ShaderLibrary.cpp.
References Exists(), Get(), and Load().
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
CreateBatchRenderer2DShader()
std::shared_ptr< Shader > Engine::ShaderLibrary::CreateBatchRenderer2DShader () static
Definition at line 43 of file ShaderLibrary.cpp.
References Exists(), Get(), and Load().
Referenced by Engine::Renderer2D::Initialize().
CreateColorShader()
std::shared_ptr< Shader > Engine::ShaderLibrary::CreateColorShader () static
Definition at line 21 of file ShaderLibrary.cpp.
References Exists(), Get(), and Load().
CreateTextureShader()
std::shared_ptr< Shader > Engine::ShaderLibrary::CreateTextureShader () static
Definition at line 32 of file ShaderLibrary.cpp.
References Exists(), Get(), and Load().
Referenced by LoadTexturedShader().
Exists()
bool Engine::ShaderLibrary::Exists (const std::string & name) static
Definition at line 88 of file ShaderLibrary.cpp.
References s_Shaders.
Referenced by CreateBasicShader(), CreateBatchRenderer2DShader(), CreateColorShader(), and CreateTextureShader().
Get()
std::shared_ptr< Shader > Engine::ShaderLibrary::Get (const std::string & name) static
Definition at line 79 of file ShaderLibrary.cpp.
References LOG_ERROR, and s_Shaders.
Referenced by CreateBasicShader(), CreateBatchRenderer2DShader(), CreateColorShader(), and CreateTextureShader().
Load()
std::shared_ptr< Shader > Engine::ShaderLibrary::Load (const std::string & name, const std::string & vertexPath, const std::string & fragmentPath) static
Definition at line 56 of file ShaderLibrary.cpp.
References Engine::Shader::CreateFromFiles(), LOG_ERROR, and s_Shaders.
Referenced by CreateBasicShader(), CreateBatchRenderer2DShader(), CreateColorShader(), and CreateTextureShader().
LoadFromSource()
std::shared_ptr< Shader > Engine::ShaderLibrary::LoadFromSource (const std::string & name, const std::string & vertexSrc, const std::string & fragmentSrc) static
Definition at line 67 of file ShaderLibrary.cpp.
References Engine::Shader::CreateFromSource(), LOG_ERROR, and s_Shaders.
LoadTexturedShader()
std::shared_ptr< Shader > Engine::ShaderLibrary::LoadTexturedShader () static
Definition at line 92 of file ShaderLibrary.cpp.
References CreateTextureShader().
Referenced by Engine::TerrainSystem::TerrainSystem().
Member Data Documentation
s_Shaders
std::unordered_map< std::string, std::shared_ptr< Shader > > Engine::ShaderLibrary::s_Shaders static private
Definition at line 27 of file ShaderLibrary.h.
Referenced by Exists(), Get(), Load(), and LoadFromSource().
The documentation for this class was generated from the following files:
src/Shader/ShaderLibrary.h
src/Shader/ShaderLibrary.cpp