Voxel Engine: Engine::Profiler::ProfileDataPool Class Reference
Engine::Profiler::ProfileDataPool Class Reference
Public Member Functions
ProfileData * allocate ()
void deallocate (ProfileData *data)
Private Attributes
std::array< ProfileData, MEMORY_POOL_SIZE > pool
std::array< bool, MEMORY_POOL_SIZE > used {}
std::mutex poolMutex
Detailed Description
Definition at line 383 of file Profiler.h.
Member Function Documentation
allocate()
ProfileData * Engine::Profiler::ProfileDataPool::allocate () inline
Definition at line 389 of file Profiler.h.
References Engine::Profiler::MEMORY_POOL_SIZE, pool, poolMutex, and used.
Referenced by Engine::Profiler::PreserveProfilingState(), Engine::Profiler::RestoreProfilingState(), and Engine::Profiler::WriteProfile().
deallocate()
void Engine::Profiler::ProfileDataPool::deallocate (ProfileData * data) inline
Definition at line 400 of file Profiler.h.
References Engine::Profiler::MEMORY_POOL_SIZE, pool, poolMutex, and used.
Referenced by Engine::Profiler::RestoreProfilingState(), and Engine::Profiler::~Profiler().
Member Data Documentation
pool
std::array<ProfileData, MEMORY_POOL_SIZE> Engine::Profiler::ProfileDataPool::pool private
Definition at line 384 of file Profiler.h.
Referenced by allocate(), and deallocate().
poolMutex
std::mutex Engine::Profiler::ProfileDataPool::poolMutex private
Definition at line 386 of file Profiler.h.
Referenced by allocate(), and deallocate().
used
std::array<bool, MEMORY_POOL_SIZE> Engine::Profiler::ProfileDataPool::used {} private
Definition at line 385 of file Profiler.h.
Referenced by allocate(), and deallocate().
The documentation for this class was generated from the following file:
src/Debug/Profiler.h