Voxel Engine: Engine::Renderer Class Reference
Engine::Renderer Class Reference
Main renderer class handling all rendering operations.
#include <Renderer.h>
Public Types
enum class CameraType { Orthographic , Perspective }
Camera types supported by the renderer.
Public Member Functions
Renderer ()
The Renderer class handles all rendering operations in the engine.
~Renderer ()
void Initialize ()
Initialize the renderer and graphics context.
void Draw ()
Trigger a draw operation.
void Submit (const std::shared_ptr< VertexArray > &vertexArray, const std::shared_ptr< Material > &material, const glm::mat4 &transformMatrix=glm::mat4(1.0f), GLenum primitiveType=GL_TRIANGLES)
Submit an object for rendering.
void Flush ()
Process and execute all queued render commands.
std::shared_ptr< OrthographicCamera > & GetCamera ()
Get the current orthographic camera.
void SetCamera (const std::shared_ptr< OrthographicCamera > &camera)
Set the orthographic camera.
void SetCameraType (CameraType type)
Set the camera type.
CameraType GetCameraType () const
Get the current camera type.
std::shared_ptr< PerspectiveCamera > & GetPerspectiveCamera ()
Get the current perspective camera.
void SetPerspectiveCamera (const std::shared_ptr< PerspectiveCamera > &camera)
Set the perspective camera.
void SetViewport (int x, int y, int width, int height) const
Set the viewport dimensions.
void Clear (const glm::vec4 &color) const
Clear the screen with specified color.
void Render ()
Triggers the rendering process by flushing all queued render commands.
Static Public Member Functions
static Renderer & Get ()
Get the singleton instance of the renderer.
Private Attributes
std::mutex m_QueueMutex
Mutex for command queue access.
std::mutex m_RenderMutex
Mutex for render queue access.
std::shared_ptr< Shader > m_Shader
Current active shader.
std::shared_ptr< VertexArray > m_VertexArray
Current vertex array.
std::queue< RenderCommand > m_CommandQueue
Queue of pending render commands.
std::vector< PreprocessedRenderCommand > m_ProcessingQueue
Commands being processed.
std::vector< PreprocessedRenderCommand > m_RenderQueue
Commands ready to render.
std::shared_ptr< Engine::OrthographicCamera > m_Camera
Orthographic camera.
CameraType m_CameraType = CameraType::Orthographic
Current camera type.
std::shared_ptr< PerspectiveCamera > m_PerspectiveCamera
Perspective camera.
std::atomic< bool > m_ProcessingFrame {false}
Frame processing flag.
Detailed Description
Main renderer class handling all rendering operations.
Manages render queues, cameras, and graphics state
Definition at line 67 of file Renderer.h.
Member Enumeration Documentation
CameraType
enum class Engine::Renderer::CameraType strong
Camera types supported by the renderer.
Enumerator
Orthographic
2D orthographic camera
Perspective
3D perspective camera
Definition at line 72 of file Renderer.h.
Constructor & Destructor Documentation
Renderer()
Engine::Renderer::Renderer ()
The Renderer class handles all rendering operations in the engine.
Definition at line 17 of file Renderer.cpp.
~Renderer()
Engine::Renderer::~Renderer ()
Definition at line 19 of file Renderer.cpp.
Member Function Documentation
Clear()
void Engine::Renderer::Clear (const glm::vec4 & color) const inline
Clear the screen with specified color.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 159 of file Renderer.h.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Draw()
void Engine::Renderer::Draw ()
Trigger a draw operation.
Trigger a draw operation by flushing the command queue.
Definition at line 152 of file Renderer.cpp.
References Engine::Profiler::EndFrame(), Flush(), and Engine::Profiler::Get().
Flush()
void Engine::Renderer::Flush ()
Process and execute all queued render commands.
Processes commands in parallel using the TaskSystem and renders on the main thread
Definition at line 79 of file Renderer.cpp.
References ASSERT, Engine::TaskSystem::Get(), Engine::TaskSystem::Initialize(), m_Camera, m_CameraType, m_CommandQueue, m_PerspectiveCamera, m_ProcessingFrame, m_QueueMutex, and Orthographic.
Referenced by Draw(), and Render().
Get()
static Renderer & Engine::Renderer::Get () inline static
Get the singleton instance of the renderer.
Returns
Reference to the renderer instance
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 108 of file Renderer.h.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
GetCamera()
std::shared_ptr< OrthographicCamera > & Engine::Renderer::GetCamera () inline
Get the current orthographic camera.
Returns
Reference to the orthographic camera
Definition at line 117 of file Renderer.h.
References m_Camera.
Referenced by Engine::InputSystem::HandleCameraMovement().
GetCameraType()
CameraType Engine::Renderer::GetCameraType () const inline
Get the current camera type.
Returns
Current camera type
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 135 of file Renderer.h.
References m_CameraType.
Referenced by Engine::InputSystem::HandleCameraMovement(), Engine::InputSystem::HandleMouseMovement(), Engine::ImGuiOverlay::OnRender(), and Engine::LuaScriptSystem::RegisterEngineAPI().
GetPerspectiveCamera()
std::shared_ptr< PerspectiveCamera > & Engine::Renderer::GetPerspectiveCamera () inline
Get the current perspective camera.
Returns
Reference to the perspective camera
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 141 of file Renderer.h.
References m_PerspectiveCamera.
Referenced by Engine::InputSystem::HandleCameraMovement(), Engine::InputSystem::HandleMouseMovement(), and Engine::LuaScriptSystem::RegisterEngineAPI().
Initialize()
void Engine::Renderer::Initialize ()
Initialize the renderer and graphics context.
Sets up GLAD and creates camera instances
Definition at line 25 of file Renderer.cpp.
References ASSERT, m_Camera, and m_PerspectiveCamera.
Render()
void Engine::Renderer::Render ()
Triggers the rendering process by flushing all queued render commands.
This method calls the Flush() method to process and execute all pending render commands in the render queue. It serves as a simple wrapper method to initiate the rendering pipeline.
Note
This method ensures that all queued rendering commands are processed and drawn to the screen.
Definition at line 186 of file Renderer.cpp.
References Flush().
SetCamera()
void Engine::Renderer::SetCamera (const std::shared_ptr< OrthographicCamera > & camera) inline
Set the orthographic camera.
Parameters
camera Shared pointer to the orthographic camera
Definition at line 123 of file Renderer.h.
References m_Camera.
SetCameraType()
void Engine::Renderer::SetCameraType (CameraType type)
Set the camera type.
Sets the active camera type for rendering.
Parameters
type Camera type to set
type The camera type to use for subsequent rendering operations Must be either Orthographic or Perspective
Precondition
The provided camera type must be either CameraType::Orthographic or CameraType::Perspective
Exceptions
Assertion error if an invalid camera type is provided
Note
This method updates the internal camera type used by the renderer
Definition at line 170 of file Renderer.cpp.
References ASSERT, m_CameraType, Orthographic, and Perspective.
Referenced by Engine::InputSystem::HandleKeyInput().
SetPerspectiveCamera()
void Engine::Renderer::SetPerspectiveCamera (const std::shared_ptr< PerspectiveCamera > & camera) inline
Set the perspective camera.
Parameters
camera Shared pointer to the perspective camera
Definition at line 147 of file Renderer.h.
References m_PerspectiveCamera.
SetViewport()
void Engine::Renderer::SetViewport (int x, int y, int width, int height) const inline
Set the viewport dimensions.
Examples
/home/runner/work/voxels/voxels/src/Scripting/LuaScriptSystem.cpp.
Definition at line 152 of file Renderer.h.
Referenced by Engine::LuaScriptSystem::RegisterEngineAPI().
Submit()
void Engine::Renderer::Submit (const std::shared_ptr< VertexArray > & vertexArray, const std::shared_ptr< Material > & material, const glm::mat4 & transformMatrix = glm::mat4(1.0f), GLenum primitiveType = GL_TRIANGLES)
Submit an object for rendering.
Submit a render command to the queue.
Parameters
vertexArray Vertex array containing geometry
material Material to use for rendering
transformMatrix Transform matrix of the object
primitiveType Type of primitives to render
vertexArray The vertex array object to render
material The material to use for rendering
transformMatrix The transform matrix for the object
primitiveType The OpenGL primitive type to render
Definition at line 52 of file Renderer.cpp.
References ASSERT, m_CommandQueue, m_QueueMutex, Engine::RenderCommand::material, Engine::RenderCommand::primitiveType, Engine::RenderCommand::transformMatrix, and Engine::RenderCommand::vertexArray.
Referenced by Engine::RenderableObject::OnRender(), Engine::SceneObject::OnRender(), Engine::TerrainSystem::Render(), and Engine::Scene::RenderObject().
Member Data Documentation
m_Camera
std::shared_ptr<Engine::OrthographicCamera> Engine::Renderer::m_Camera private
Orthographic camera.
Definition at line 174 of file Renderer.h.
Referenced by Flush(), GetCamera(), Initialize(), and SetCamera().
m_CameraType
CameraType Engine::Renderer::m_CameraType = CameraType::Orthographic private
Current camera type.
Definition at line 175 of file Renderer.h.
Referenced by Flush(), GetCameraType(), and SetCameraType().
m_CommandQueue
std::queue<RenderCommand> Engine::Renderer::m_CommandQueue private
Queue of pending render commands.
Definition at line 171 of file Renderer.h.
Referenced by Flush(), and Submit().
m_PerspectiveCamera
std::shared_ptr<PerspectiveCamera> Engine::Renderer::m_PerspectiveCamera private
Perspective camera.
Definition at line 176 of file Renderer.h.
Referenced by Flush(), GetPerspectiveCamera(), Initialize(), and SetPerspectiveCamera().
m_ProcessingFrame
std::atomic<bool> Engine::Renderer::m_ProcessingFrame {false} private
Frame processing flag.
Definition at line 177 of file Renderer.h.
Referenced by Flush().
m_ProcessingQueue
std::vector<PreprocessedRenderCommand> Engine::Renderer::m_ProcessingQueue private
Commands being processed.
Definition at line 172 of file Renderer.h.
m_QueueMutex
std::mutex Engine::Renderer::m_QueueMutex private
Mutex for command queue access.
Definition at line 167 of file Renderer.h.
Referenced by Flush(), and Submit().
m_RenderMutex
std::mutex Engine::Renderer::m_RenderMutex private
Mutex for render queue access.
Definition at line 168 of file Renderer.h.
m_RenderQueue
std::vector<PreprocessedRenderCommand> Engine::Renderer::m_RenderQueue private
Commands ready to render.
Definition at line 173 of file Renderer.h.
m_Shader
std::shared_ptr<Shader> Engine::Renderer::m_Shader private
Current active shader.
Definition at line 169 of file Renderer.h.
m_VertexArray
std::shared_ptr<VertexArray> Engine::Renderer::m_VertexArray private
Current vertex array.
Definition at line 170 of file Renderer.h.
The documentation for this class was generated from the following files:
src/Renderer/Renderer.h
src/Renderer/Renderer.cpp