Voxel Engine: Engine Namespace Reference
Engine Namespace Reference
Core engine namespace containing the main application and system components.
Namespaces
namespace LogColors
namespace MeshTemplates
Collection of predefined mesh templates.
Classes
class Application
Main application class handling window, rendering and game loop.
class AssetManager
Manages loading, caching, and unloading of game assets.
class BatchRenderer2D
struct BatchVertex
struct BufferElement
Describes a single element in a buffer layout.
class BufferLayout
Describes the layout of a vertex buffer.
class Event
Base class for all event types.
struct EventCompare
Comparator for event priority queue ordering.
class EventDebugger
class EventDispatcher
class EventQueue
Thread-safe event queue for storing and processing events.
class FileSystem
class FileWatcher
A utility class for monitoring file changes.
class FPSCounter
struct GLCommand
Structure representing a low-level GL command.
class ImGuiLayer
Manages Dear ImGui integration with the application.
class ImGuiOverlay
ImGui-based overlay for debug and control interfaces.
class IndexBuffer
Abstract index buffer interface.
class InputSystem
Handles all input processing for the application.
class IRenderer
class KeyEvent
Base class for keyboard events.
class KeyPressedEvent
Event for key press with repeat detection.
class KeyReleasedEvent
Event for key release.
struct KeyToggleState
Stores state for key toggle functionality.
class Light
Class representing a light source in the scene.
class Logger
Singleton logger class for application-wide logging.
class LuaScriptSystem
class Material
Manages shader parameters and textures for rendering.
class MouseButtonEvent
Base class for mouse button events.
class MouseButtonPressedEvent
Event for mouse button press.
class MouseButtonReleasedEvent
Event for mouse button release.
class MouseMovedEvent
Event for mouse cursor movement.
class MouseScrolledEvent
Event for mouse wheel scrolling.
class OpenGLIndexBuffer
OpenGL implementation of index buffer.
class OpenGLVertexArray
OpenGL implementation of vertex array object.
class OpenGLVertexBuffer
OpenGL implementation of vertex buffer.
class OpenGLWindow
OpenGL-specific window implementation.
class OrthographicCamera
An orthographic camera class for 2D rendering.
class PerspectiveCamera
A perspective camera class for 3D rendering.
struct PreprocessedRenderCommand
Preprocessed version of render command with computed model matrix.
class Profiler
Singleton class for managing performance profiling.
class ProfilerTimer
RAII-style timer for profiling code blocks.
struct QuadVertex
class RenderableObject
Interface for objects that can be rendered.
class RenderAPI
struct RenderCommand
Structure containing information for a render command.
class Renderer
Main renderer class handling all rendering operations.
class Renderer2D
Specialized renderer for 2D graphics with batching support.
struct Renderer2DData
class RenderObject
Class representing a renderable object with geometry, material, and transform.
class Resource
Base class for all loadable game resources.
class Scene
class SceneManager
class SceneObject
class Shader
OpenGL shader program wrapper.
class ShaderFactory
class ShaderHotReload
Manages hot-reloading of shader files.
class ShaderLibrary
class TaskSystem
Thread pool-based task system for concurrent execution.
class TerrainSystem
Manages voxel terrain generation and rendering.
class Texture
Represents a 2D texture resource that can be loaded from file or created empty.
class ThreadPool
Thread pool for parallel task execution.
class Transform
struct Vertex
Basic vertex structure with position.
class VertexArray
Abstract base class for vertex array objects.
class VertexBuffer
Abstract vertex buffer interface.
class Window
Abstract window interface.
class WindowCloseEvent
Event triggered when window is closed.
struct WindowProps
Window creation properties.
class WindowResizeEvent
Event triggered when window is resized.
Typedefs
using EventCallbackFn = std::function< bool(Event &)>
Enumerations
enum class RenderType { Render2D , Render3D }
enum class CameraType { Orthographic , Perspective }
enum class ResourceType {
Texture , Shader , Mesh , Sound ,
Model
}
Enumerates different types of game resources.
enum class LogLevel {
Trace , Info , Warn , Error ,
Fatal
}
Logging severity levels.
enum class EventType {
None = 0 , WindowClose , WindowResize , WindowFocus ,
WindowLostFocus , WindowMoved , KeyPressed , KeyReleased ,
KeyTyped , MouseButtonPressed , MouseButtonReleased , MouseMoved ,
MouseScrolled , AppTick , AppUpdate , AppRender ,
None = 0 , WindowClose , WindowResize , WindowFocus ,
WindowLostFocus , WindowMoved , KeyPressed , KeyReleased ,
KeyTyped , MouseButtonPressed , MouseButtonReleased , MouseMoved ,
MouseScrolled
}
Enumeration of all possible event types in the system.
enum class EventCategory {
None = 0 , Application = 1 << 0 , Input = 1 << 1 , Keyboard = 1 << 2 ,
Mouse = 1 << 3 , MouseButton = 1 << 4 , None = 0 , None = 0 ,
EventCategoryApplication = (1 << 0) , EventCategoryInput = (1 << 1) , EventCategoryKeyboard = (1 << 2) , EventCategoryMouse = (1 << 3) ,
EventCategoryMouseButton = (1 << 4)
}
Categories for event filtering and routing.
enum class EventPriority { Low = 0 , Normal = 1 , High = 2 }
Priority levels for event processing.
enum class EventType {
None = 0 , WindowClose , WindowResize , WindowFocus ,
WindowLostFocus , WindowMoved , KeyPressed , KeyReleased ,
KeyTyped , MouseButtonPressed , MouseButtonReleased , MouseMoved ,
MouseScrolled , AppTick , AppUpdate , AppRender ,
None = 0 , WindowClose , WindowResize , WindowFocus ,
WindowLostFocus , WindowMoved , KeyPressed , KeyReleased ,
KeyTyped , MouseButtonPressed , MouseButtonReleased , MouseMoved ,
MouseScrolled
}
Enumeration of all possible event types in the system.
enum EventCategory {
None = 0 , Application = 1 << 0 , Input = 1 << 1 , Keyboard = 1 << 2 ,
Mouse = 1 << 3 , MouseButton = 1 << 4
}
Event category flags for filtering events.
enum KeyCode {
Key_Space = 32 , Key_Apostrophe = 39 , Key_Comma = 44 , Key_Minus = 45 ,
Key_Period = 46 , Key_Slash = 47 , Key_0 = 48 , Key_1 = 49 ,
Key_2 = 50 , Key_3 = 51 , Key_4 = 52 , Key_5 = 53 ,
Key_6 = 54 , Key_7 = 55 , Key_8 = 56 , Key_9 = 57 ,
Key_Semicolon = 59 , Key_Equal = 61 , Key_A = 65 , Key_B = 66 ,
Key_C = 67 , Key_D = 68 , Key_E = 69 , Key_F = 70 ,
Key_G = 71 , Key_H = 72 , Key_I = 73 , Key_J = 74 ,
Key_K = 75 , Key_L = 76 , Key_M = 77 , Key_N = 78 ,
Key_O = 79 , Key_P = 80 , Key_Q = 81 , Key_R = 82 ,
Key_S = 83 , Key_T = 84 , Key_U = 85 , Key_V = 86 ,
Key_W = 87 , Key_X = 88 , Key_Y = 89 , Key_Z = 90 ,
NUM_0 = 48 , NUM_1 = 49 , NUM_2 = 50 , NUM_3 = 51 ,
NUM_4 = 52 , NUM_5 = 53 , NUM_6 = 54 , NUM_7 = 55 ,
NUM_8 = 56 , NUM_9 = 57
}
Key codes for keyboard input.
enum class ShaderDataType {
None = 0 , Float , Float2 , Float3 ,
Float4 , Mat3 , Mat4 , Int ,
Int2 , Int3 , Int4 , Bool
}
Types of data that can be stored in shader buffers.
enum class RenderAPI { None = 0 , OpenGL , Vulkan , DirectX11 }
Supported rendering APIs.
Functions
Application * CreateApplication ()
Creates the application instance.
template<typename T >
std::string ToString (const T &value)
Converts any type to its string representation.
std::string ToString (bool value)
std::string ToString (const char *value)
template<typename T >
std::string ToString (const std::unique_ptr< T > &ptr)
std::string ToString (const Window &window)
std::string KeyCodeToString (int keycode)
Converts a key code to its string representation.
static uint32_t ShaderDataTypeSize (ShaderDataType type)
Gets the size in bytes of a shader data type.
static uint32_t GetComponentCount (ShaderDataType type)
Gets the number of components in a shader data type.
static GLenum ShaderDataTypeToOpenGLBaseType (ShaderDataType type)
Converts engine shader data types to OpenGL types.
Variables
constexpr float EVENT_PROCESS_RATE = 60.0f
constexpr float EVENT_PROCESS_INTERVAL = 1.0f / EVENT_PROCESS_RATE
static thread_local std::chrono::steady_clock::time_point s_LastSampleTime = std::chrono::steady_clock::now()
static constexpr std::chrono::duration< float > SAMPLE_INTERVAL {1.0f/60.0f}
static Renderer2DData s_Data
Detailed Description
Core engine namespace containing the main application and system components.
Main engine namespace containing all core functionality.
Core engine namespace containing fundamental engine components.
Updates the FPS counter with new frame time data.
The Engine namespace encapsulates all core functionality of the voxel engine including:
Application lifecycle management
Window handling and event processing
Rendering systems and ImGui integration
Input processing
Terrain generation and management
Asset management
Performance profiling and debugging tools
Key components:
Application: Main application class managing the game loop and subsystems
TerrainSystem: Handles voxel terrain generation and rendering
InputSystem: Processes user input and dispatches events
ImGuiLayer: Handles debug UI rendering
Renderer: Manages graphics rendering
The engine uses a component-based architecture with systems for:
Event handling through EventQueue
Asset management via AssetManager
Performance profiling with Profiler
Scene management through SceneManager
Note
All engine components should be initialized through the Application class
This method updates the FPS counter by:
Calculating current FPS from delta time
Maintaining a rolling window of FPS samples
Every 0.5 seconds:
Calculates average FPS across all samples
Calculates 1% low FPS (average of lowest 1% of samples)
Calculates 1% high FPS (average of highest 1% of samples)
Parameters
deltaTime Time elapsed since last frame in seconds
Typedef Documentation
EventCallbackFn
using Engine::EventCallbackFn = typedef std::function<bool(Event&)>
Definition at line 7 of file Window.h.
Enumeration Type Documentation
CameraType
enum class Engine::CameraType strong
Enumerator
Orthographic
Perspective
Definition at line 5 of file CameraTypes.h.
EventCategory [1/2]
enum class Engine::EventCategory strong
Categories for event filtering and routing.
Enumerator
None
Application
Input
Keyboard
Mouse
MouseButton
None
None
EventCategoryApplication
Application events.
EventCategoryInput
Input events.
EventCategoryKeyboard
Keyboard events.
EventCategoryMouse
Mouse events.
EventCategoryMouseButton
Mouse button events.
Definition at line 20 of file Event.h.
EventCategory [2/2]
enum Engine::EventCategory
Event category flags for filtering events.
Enumerator
None
Application
Input
Keyboard
Mouse
MouseButton
Definition at line 28 of file Events.h.
EventPriority
enum class Engine::EventPriority strong
Priority levels for event processing.
Enumerator
Low
Low priority events.
Normal
Normal priority events.
High
High priority events.
Definition at line 32 of file Event.h.
EventType [1/2]
enum class Engine::EventType strong
Enumeration of all possible event types in the system.
Enumerator
None
WindowClose
WindowResize
WindowFocus
WindowLostFocus
WindowMoved
KeyPressed
KeyReleased
KeyTyped
MouseButtonPressed
MouseButtonReleased
MouseMoved
MouseScrolled
AppTick
AppUpdate
AppRender
None
WindowClose
Window close event.
WindowResize
Window resize event.
WindowFocus
Window focus gained event.
WindowLostFocus
Window focus lost event.
WindowMoved
Window moved event.
KeyPressed
Keyboard key pressed event.
KeyReleased
Keyboard key released event.
KeyTyped
Keyboard key typed event.
MouseButtonPressed
Mouse button pressed event.
MouseButtonReleased
Mouse button released event.
MouseMoved
Mouse moved event.
MouseScrolled
Mouse wheel scrolled event.
Definition at line 9 of file Event.h.
EventType [2/2]
enum class Engine::EventType strong
Enumeration of all possible event types in the system.
Enumerator
None
WindowClose
WindowResize
WindowFocus
WindowLostFocus
WindowMoved
KeyPressed
KeyReleased
KeyTyped
MouseButtonPressed
MouseButtonReleased
MouseMoved
MouseScrolled
AppTick
AppUpdate
AppRender
None
WindowClose
Window close event.
WindowResize
Window resize event.
WindowFocus
Window focus gained event.
WindowLostFocus
Window focus lost event.
WindowMoved
Window moved event.
KeyPressed
Keyboard key pressed event.
KeyReleased
Keyboard key released event.
KeyTyped
Keyboard key typed event.
MouseButtonPressed
Mouse button pressed event.
MouseButtonReleased
Mouse button released event.
MouseMoved
Mouse moved event.
MouseScrolled
Mouse wheel scrolled event.
Definition at line 9 of file Events.h.
KeyCode
enum Engine::KeyCode
Key codes for keyboard input.
Maps to GLFW key codes for consistent cross-platform behavior
Enumerator
Key_Space
Key_Apostrophe
Key_Comma
Key_Minus
Key_Period
Key_Slash
Key_0
Key_1
Key_2
Key_3
Key_4
Key_5
Key_6
Key_7
Key_8
Key_9
Key_Semicolon
Key_Equal
Key_A
Key_B
Key_C
Key_D
Key_E
Key_F
Key_G
Key_H
Key_I
Key_J
Key_K
Key_L
Key_M
Key_N
Key_O
Key_P
Key_Q
Key_R
Key_S
Key_T
Key_U
Key_V
Key_W
Key_X
Key_Y
Key_Z
NUM_0
NUM_1
NUM_2
NUM_3
NUM_4
NUM_5
NUM_6
NUM_7
NUM_8
NUM_9
Definition at line 12 of file KeyCodes.h.
LogLevel
enum class Engine::LogLevel strong
Logging severity levels.
Enumerator
Trace
Detailed debugging information.
Info
General information messages.
Warn
Warning messages.
Error
Error messages.
Fatal
Critical errors that require immediate attention.
Definition at line 13 of file Logging.h.
RenderAPI
enum class Engine::RenderAPI strong
Supported rendering APIs.
Enumerator
None
No rendering API.
OpenGL
OpenGL rendering.
Vulkan
Vulkan rendering.
DirectX11
DirectX 11 rendering.
Definition at line 12 of file Window.h.
RenderType
enum class Engine::RenderType strong
Enumerator
Render2D
Render3D
Definition at line 22 of file Application.h.
ResourceType
enum class Engine::ResourceType strong
Enumerates different types of game resources.
Enumerator
Texture
2D or 3D texture resource
Shader
Shader program resource.
Mesh
3D mesh resource
Sound
Audio resource.
Model
3D model resource
Definition at line 10 of file Resource.h.
ShaderDataType
enum class Engine::ShaderDataType strong
Types of data that can be stored in shader buffers.
Enumerator
None
No type specified.
Float
Single precision float.
Float2
2D vector of floats
Float3
3D vector of floats
Float4
4D vector of floats
Mat3
3x3 matrix
Mat4
4x4 matrix
Int
32-bit integer
Int2
2D vector of integers
Int3
3D vector of integers
Int4
4D vector of integers
Bool
Boolean value.
Definition at line 8 of file Buffer.h.
Function Documentation
CreateApplication()
Engine::Application * Engine::CreateApplication ()
Creates the application instance.
Returns
Pointer to newly created Application
Definition at line 8 of file EntryPoint.cpp.
Referenced by main().
GetComponentCount()
static uint32_t Engine::GetComponentCount (ShaderDataType type) static
Gets the number of components in a shader data type.
Parameters
type The shader data type
Returns
Number of components
Definition at line 50 of file Buffer.h.
References Bool, Float, Float2, Float3, Float4, Int, Int2, Int3, Int4, Mat3, and Mat4.
Referenced by Engine::OpenGLVertexArray::AddVertexBuffer().
KeyCodeToString()
std::string Engine::KeyCodeToString (int keycode) inline
Converts a key code to its string representation.
Parameters
keycode Key code to convert
Returns
String representation of the key
Definition at line 74 of file KeyCodes.h.
References Key_0, Key_9, Key_A, Key_Apostrophe, Key_Comma, Key_Equal, Key_Minus, Key_Period, Key_Semicolon, Key_Slash, Key_Space, and Key_Z.
ShaderDataTypeSize()
static uint32_t Engine::ShaderDataTypeSize (ShaderDataType type) static
Gets the size in bytes of a shader data type.
Parameters
type The shader data type
Returns
Size in bytes
Definition at line 28 of file Buffer.h.
References Bool, Float, Float2, Float3, Float4, Int, Int2, Int3, Int4, Mat3, and Mat4.
ShaderDataTypeToOpenGLBaseType()
static GLenum Engine::ShaderDataTypeToOpenGLBaseType (ShaderDataType type) static
Converts engine shader data types to OpenGL types.
Parameters
type Engine shader data type
Returns
Corresponding OpenGL data type
Definition at line 14 of file OpenGLVertexArray.cpp.
References Bool, Float, Float2, Float3, Float4, Int, Int2, Int3, Int4, Mat3, and Mat4.
Referenced by Engine::OpenGLVertexArray::AddVertexBuffer().
ToString() [1/5]
std::string Engine::ToString (bool value) inline
Definition at line 36 of file Logging.h.
ToString() [2/5]
std::string Engine::ToString (const char * value) inline
Definition at line 39 of file Logging.h.
ToString() [3/5]
template<typename T > std::string Engine::ToString (const std::unique_ptr< T > & ptr)
Definition at line 43 of file Logging.h.
ToString() [4/5]
template<typename T > std::string Engine::ToString (const T & value)
Converts any type to its string representation.
Template Parameters
T Type to convert
Parameters
value Value to convert
Returns
String representation
Definition at line 29 of file Logging.h.
Referenced by Engine::Logger::LogValue(), and Engine::Logger::LogValueImpl().
ToString() [5/5]
std::string Engine::ToString (const Window & window) inline
Variable Documentation
EVENT_PROCESS_INTERVAL
constexpr float Engine::EVENT_PROCESS_INTERVAL = 1.0f / EVENT_PROCESS_RATE constexpr
Definition at line 55 of file Application.cpp.
Referenced by Engine::Application::ProcessEvents().
EVENT_PROCESS_RATE
constexpr float Engine::EVENT_PROCESS_RATE = 60.0f constexpr
Definition at line 54 of file Application.cpp.
s_Data
Renderer2DData Engine::s_Data static
Definition at line 41 of file Renderer2D.cpp.
Referenced by Engine::Renderer2D::BeginScene(), Engine::Renderer2D::DrawQuad(), Engine::Renderer2D::DrawQuad(), Engine::Renderer2D::Flush(), Engine::Renderer2D::Initialize(), Engine::Renderer2D::Shutdown(), and Engine::Renderer2D::StartBatch().
s_LastSampleTime
thread_local std::chrono::steady_clock::time_point Engine::s_LastSampleTime = std::chrono::steady_clock::now() static
Definition at line 19 of file Profiler.cpp.
Referenced by Engine::Profiler::WriteProfile().
SAMPLE_INTERVAL
constexpr std::chrono::duration<float> Engine::SAMPLE_INTERVAL {1.0f/60.0f} static constexpr
Definition at line 20 of file Profiler.cpp.
Referenced by Engine::Profiler::WriteProfile().