Voxel Engine: AssertLib Namespace Reference
AssertLib Namespace Reference
A utility namespace providing assertion functionality for debugging and testing.
Classes
class AssertionError
Functions
std::string createMessage (const std::string &file, int line, const std::string &msg)
template<typename T >
void assertEquals (const T &expected, const T &actual, const std::string &file, int line)
template<typename T , typename U >
void assertType (const U &value, const std::string &file, int line)
Detailed Description
A utility namespace providing assertion functionality for debugging and testing.
Function Documentation
assertEquals()
template<typename T > void AssertLib::assertEquals (const T & expected, const T & actual, const std::string & file, int line)
Definition at line 97 of file AssertLib.h.
References createMessage().
assertType()
template<typename T , typename U > void AssertLib::assertType (const U & value, const std::string & file, int line)
Definition at line 111 of file AssertLib.h.
References createMessage().
createMessage()
std::string AssertLib::createMessage (const std::string & file, int line, const std::string & msg) inline
Definition at line 83 of file AssertLib.h.
Referenced by assertEquals(), and assertType().