Voxel Engine: Engine::Profiler::FastPathCache Struct Reference
Engine::Profiler::FastPathCache Struct Reference
Classes
struct Entry
Public Member Functions
ProfileData * find (const ProfileName &name)
void insert (const ProfileName &name, ProfileData *data)
Public Attributes
std::array< Entry, FAST_PATH_SIZE > entries
uint64_t accessCount {0}
Detailed Description
Definition at line 477 of file Profiler.h.
Member Function Documentation
find()
ProfileData * Engine::Profiler::FastPathCache::find (const ProfileName & name) inline
Definition at line 487 of file Profiler.h.
References accessCount, and entries.
Referenced by Engine::Profiler::WriteProfile().
insert()
void Engine::Profiler::FastPathCache::insert (const ProfileName & name, ProfileData * data) inline
Definition at line 498 of file Profiler.h.
References accessCount, entries, and Engine::Profiler::FAST_PATH_SIZE.
Referenced by Engine::Profiler::RestoreProfilingState(), and Engine::Profiler::WriteProfile().
Member Data Documentation
accessCount
uint64_t Engine::Profiler::FastPathCache::accessCount {0}
Definition at line 485 of file Profiler.h.
Referenced by find(), and insert().
entries
std::array<Entry, FAST_PATH_SIZE> Engine::Profiler::FastPathCache::entries
Definition at line 484 of file Profiler.h.
Referenced by find(), and insert().
The documentation for this struct was generated from the following file:
src/Debug/Profiler.h