Voxel Engine: Engine::Profiler::ProfileData Struct Reference
Engine::Profiler::ProfileData Struct Reference
Public Member Functions
void AddSample (float time) noexcept
bool empty () const
size_t size () const
auto begin () const
auto end () const
ProfileData & operator= (const ProfileData &other)
Public Attributes
float localSamples [LOCAL_SAMPLES]
SmallVector< float, SMALL_VECTOR_SIZE > samples
uint32_t calls {0}
uint32_t localCount {0}
float minTime {std::numeric_limits<float>::max()}
float maxTime {std::numeric_limits<float>::lowest()}
float totalTime {0.0f}
float avgTime {0.0f}
float recentAvg {0.0f}
Static Public Attributes
static constexpr size_t LOCAL_SAMPLES = 8
static constexpr size_t MAX_SAMPLES = 1000
Detailed Description
Definition at line 313 of file Profiler.h.
Member Function Documentation
AddSample()
void Engine::Profiler::ProfileData::AddSample (float time) inline noexcept
Definition at line 327 of file Profiler.h.
References avgTime, Engine::Profiler::SmallVector< T, N >::begin(), calls, Engine::Profiler::SmallVector< T, N >::end(), LOCAL_SAMPLES, localCount, localSamples, MAX_SAMPLES, maxTime, minTime, Engine::Profiler::SmallVector< T, N >::moveToHeap(), Engine::Profiler::SmallVector< T, N >::push_back(), recentAvg, samples, Engine::Profiler::SmallVector< T, N >::set_back(), Engine::Profiler::SmallVector< T, N >::size(), and totalTime.
Referenced by Engine::Profiler::WriteProfile().
begin()
auto Engine::Profiler::ProfileData::begin () const inline
Definition at line 363 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::begin(), and samples.
empty()
bool Engine::Profiler::ProfileData::empty () const inline
Definition at line 361 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::empty(), and samples.
end()
auto Engine::Profiler::ProfileData::end () const inline
Definition at line 364 of file Profiler.h.
References Engine::Profiler::SmallVector< T, N >::end(), and samples.
operator=()
ProfileData & Engine::Profiler::ProfileData::operator= (const ProfileData & other) inline
Definition at line 367 of file Profiler.h.
References avgTime, calls, localCount, localSamples, maxTime, minTime, recentAvg, samples, and totalTime.
size()
size_t Engine::Profiler::ProfileData::size () const inline
Definition at line 362 of file Profiler.h.
References samples, and Engine::Profiler::SmallVector< T, N >::size().
Member Data Documentation
avgTime
float Engine::Profiler::ProfileData::avgTime {0.0f}
Definition at line 324 of file Profiler.h.
Referenced by AddSample(), and operator=().
calls
uint32_t Engine::Profiler::ProfileData::calls {0}
Definition at line 319 of file Profiler.h.
Referenced by AddSample(), and operator=().
LOCAL_SAMPLES
constexpr size_t Engine::Profiler::ProfileData::LOCAL_SAMPLES = 8 static constexpr
Definition at line 314 of file Profiler.h.
Referenced by AddSample().
localCount
uint32_t Engine::Profiler::ProfileData::localCount {0}
Definition at line 320 of file Profiler.h.
Referenced by AddSample(), and operator=().
localSamples
float Engine::Profiler::ProfileData::localSamples[LOCAL_SAMPLES]
Definition at line 317 of file Profiler.h.
Referenced by AddSample(), and operator=().
MAX_SAMPLES
constexpr size_t Engine::Profiler::ProfileData::MAX_SAMPLES = 1000 static constexpr
Definition at line 315 of file Profiler.h.
Referenced by AddSample().
maxTime
float Engine::Profiler::ProfileData::maxTime {std::numeric_limits<float>::lowest()}
Definition at line 322 of file Profiler.h.
Referenced by AddSample(), and operator=().
minTime
float Engine::Profiler::ProfileData::minTime {std::numeric_limits<float>::max()}
Definition at line 321 of file Profiler.h.
Referenced by AddSample(), and operator=().
recentAvg
float Engine::Profiler::ProfileData::recentAvg {0.0f}
Definition at line 325 of file Profiler.h.
Referenced by AddSample(), and operator=().
samples
SmallVector<float, SMALL_VECTOR_SIZE> Engine::Profiler::ProfileData::samples
Definition at line 318 of file Profiler.h.
Referenced by AddSample(), begin(), empty(), end(), operator=(), and size().
totalTime
float Engine::Profiler::ProfileData::totalTime {0.0f}
Definition at line 323 of file Profiler.h.
Referenced by AddSample(), and operator=().
The documentation for this struct was generated from the following file:
src/Debug/Profiler.h